/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class PCPersistentTimer;

@interface VSAssetUpdateListener : NSObject
{
    BOOL _isListening;
    PCPersistentTimer *_assetCleanupTimer;
}

+ (id)sharedListener;
- (id)init;
- (id)_initShared;
- (void)dealloc;
- (void)_rescheduleAssetCleanup;
- (void)startListening;
- (void)stopListening;
- (void)_flushLanguageChanges;
- (void)_cleanupAssets;
- (void)_spokenLanguageChanged:(id)arg1;
- (void)_updateNextCleanupDate;
- (void)_scheduleNextCleanupForDate:(id)arg1;
- (void)_cancelAssetCleanupTimer;

@end

