/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <VoiceServices/VSRecognitionRecognizeAction.h>

@class VSRecognitionAction;

@interface VSRecognitionConfirmAction : VSRecognitionRecognizeAction
{
    VSRecognitionAction *_confirmedAction;
    VSRecognitionAction *_deniedAction;
    struct {
        unsigned int initializing:1;
        unsigned int confirmed:1;
    } _confirmFlags;
}

- (id)init;
- (id)initWithModelIdentifier:(id)arg1;
- (void)dealloc;
- (int)completionType;
- (void)_setConfirmed:(BOOL)arg1;
- (void)setConfirmedAction:(id)arg1;
- (id)confirmedAction;
- (void)setDeniedAction:(id)arg1;
- (id)deniedAction;

@end

