/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSAttributedString, NSString, VSRecognitionSession;

@interface VSRecognitionAction : NSObject
{
    NSString *_resultString;
    NSString *_statusString;
    union {
        NSString *stringValue;
        NSAttributedString *attributedStringValue;
    } _spokenString;
    VSRecognitionSession *_session;
    unsigned int _spokenStringIsAttributed:1;
}

- (id)_session;
- (void)_setSession:(id)arg1;
- (void)dealloc;
- (id)resultDisplayString;
- (void)setResultDisplayString:(id)arg1;
- (id)statusDisplayString;
- (void)setStatusDisplayString:(id)arg1;
- (id)spokenFeedbackString;
- (void)setSpokenFeedbackString:(id)arg1;
- (id)spokenFeedbackAttributedString;
- (void)setSpokenFeedbackAttributedString:(id)arg1;
- (int)completionType;
- (id)perform;
- (id)cancel;
- (void)completeWithNextAction:(id)arg1 error:(id)arg2;
- (BOOL)_hasDeferredStartCallback;
- (BOOL)sensitiveActionsEnabled;
- (void)_continueAfterDeferredStart;

@end

