/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface VSRecognitionResult : NSObject
{
}

+ (void)initialize;
+ (id)recognitionResultWithModelIdentifier:(id)arg1 classIdentifiers:(id)arg2 values:(id)arg3;
- (id)init;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)retain;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)recognitionResultByReplacingValueForClassIdentifier:(id)arg1 withValue:(id)arg2;
- (id)modelIdentifier;
- (int)elementCount;
- (BOOL)getElementClassIdentifier:(id *)arg1 value:(id *)arg2 atIndex:(int)arg3;
- (id)valueOfFirstElementWithClassIdentifier:(id)arg1;
- (id)createHandler;
- (void)setRecognitionAction:(id)arg1;
- (id)recognitionAction;
- (id)description;

@end

