/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <VoiceServices/VSRecognitionAction.h>

@class NSArray, NSString;

@interface VSRecognitionRecognizeAction : VSRecognitionAction
{
    NSString *_modelIdentifier;
    NSArray *_keywords;
    void *_recognition;
    NSArray *_results;
    NSString *_debugDumpPath;
    NSString *_audioInputPath;
    double _levelInterval;
    struct {
        unsigned int debugDumpEnabled:1;
        unsigned int preferredEngine:2;
        unsigned int resetEngine:1;
        unsigned int bluetoothAllowed:1;
        unsigned int hasStarted:1;
    } _recognizeFlags;
}

- (id)initWithModelIdentifier:(id)arg1;
- (void)dealloc;
- (int)completionType;
- (id)modelIdentifier;
- (BOOL)_isRecognizing;
- (BOOL)_isActivelyRecognizing;
- (BOOL)_hasDeferredStartCallback;
- (BOOL)_setBluetoothInputAllowed:(BOOL)arg1;
- (BOOL)_setInputLevelUpdateInterval:(double)arg1;
- (float)_inputLevel;
- (id)_keywords;
- (id)_keywordAtIndex:(int)arg1;
- (int)_keywordCount;
- (BOOL)_keywordIndexChanged;
- (BOOL)_setDebugDumpEnabled:(BOOL)arg1 dumpPath:(id)arg2;
- (BOOL)_setDebugDumpEnabled:(BOOL)arg1;
- (BOOL)_setDebugDumpPath:(id)arg1;
- (id)_debugDumpPath;
- (BOOL)_setPreferredEngine:(int)arg1;
- (BOOL)_setAudioInputPath:(id)arg1;
- (BOOL)_setEngineResetRequired:(BOOL)arg1;
- (struct __VSRecognition *)_createRecognitionInstanceWithCallbacks:(CDStruct_90f67059 *)arg1 info:(void *)arg2;
- (void)_configureNewRecognitionInstance;
- (id)perform;
- (id)cancel;
- (void)_releaseFromPrepare;
- (void)_continueAfterDeferredStart;
- (id)_actionForEmptyResults;
- (void)_setResults:(id)arg1;
- (void)_reset;
- (void)_handleRecognitionPrepared:(struct __VSRecognition *)arg1;
- (void)_handleRecognitionStarted:(struct __VSRecognition *)arg1;
- (void)_handleRecognitionCompleted:(struct __VSRecognition *)arg1 withResults:(struct __CFArray *)arg2 error:(struct __CFError *)arg3;
- (void)_handledThreadedResults:(id)arg1 nextAction:(id)arg2;

@end

