/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@interface VMUBacktrace : NSObject <NSCopying>
{
    int _flavor;
    struct {
        struct {
            double t_begin;
            double t_end;
            int pid;
            unsigned int thread;
            int run_state;
            unsigned long long dispatch_queue_serial_num;
        } context;
        unsigned long long *frames;
        char *frame_types;
        unsigned int length;
    } _callstack;
}

- (struct _CSTypeRef)_symbolicator;
- (id)initWithSamplingContext:(struct sampling_context_t *)arg1 thread:(unsigned int)arg2;
- (id)initWithTask:(unsigned int)arg1 thread:(unsigned int)arg2 is64Bit:(BOOL)arg3;
- (id)initWithTask:(unsigned int)arg1 thread:(unsigned int)arg2 is64Bit:(BOOL)arg3 taskMemoryCache:(id)arg4;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)fixupStackWithTask:(unsigned int)arg1 symbolicator:(struct _CSTypeRef)arg2 taskMemoryCache:(id)arg3;
- (void)fixupStackWithSamplingContext:(struct sampling_context_t *)arg1 symbolicator:(struct _CSTypeRef)arg2;
- (BOOL)hasSameCallstack:(id)arg1;
- (unsigned long long)topmostFrame;
- (void)removeTopmostFrame;
- (void)setStartTime:(double)arg1;
- (void)setEndTime:(double)arg1;
- (void)setLengthTime:(double)arg1;
- (unsigned long long *)backtrace;
- (unsigned int)backtraceLength;
- (unsigned int)thread;
- (void)setThreadState:(int)arg1;
- (int)threadState;
- (unsigned long long)dispatchQueueSerialNumber;

@end

