/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface VMUClassInfo : NSObject <NSCoding>
{
    id _reader;
    unsigned long long _remoteIsa;
    unsigned int _remotePointerSize;
    unsigned int _ivarCount;
    unsigned int _superclassOffset;
    unsigned int _instanceSize;
    unsigned int _ro_flags;
    unsigned int _rw_flags;
    struct objc_ivar **_localIvarList;
    int *_ivarSizes;
    int _remoteType;
    NSString *_remoteClassName;
    NSString *_remoteBinaryName;
    VMUClassInfo *_superclassLayout;
    char *_weakLayout;
    char *_strongLayout;
    char *_weakMap;
    char *_strongMap;
}

+ (void)initialize;
+ (id)classInfoWithClassName:(id)arg1 binaryName:(id)arg2 type:(int)arg3;
+ (id)descriptionForTypeEncoding:(const char *)arg1 ivarName:(const char *)arg2;
- (int)_readRemoteIntAt:(unsigned long long)arg1;
- (unsigned long long)_readRemotePointerAt:(unsigned long long)arg1;
- (const char *)_copyRemoteStringAt:(unsigned long long)arg1;
- (struct objc_ivar *)_copyRemoteIvarAt:(unsigned long long)arg1;
- (const char *)_copyRemoteLayout:(unsigned long long)arg1;
- (char *)_processARRLayout:(const char *)arg1;
- (void)_parseIvarsAndLayouts;
- (void)_setClassNameWithAddress:(unsigned long long)arg1;
- (id)initWithClassName:(id)arg1 binaryName:(id)arg2 type:(int)arg3;
- (id)initWithIsaPointer:(unsigned int)arg1 symbolicator:(struct _CSTypeRef)arg2;
- (id)initWithClass:(unsigned long long)arg1 infoMap:(id)arg2 symbolicator:(struct _CSTypeRef)arg3 type:(int)arg4 memoryReader:(id)arg5;
- (id)_initWithClass:(unsigned long long)arg1 doLayouts:(BOOL)arg2 infoMap:(id)arg3 symbolicator:(struct _CSTypeRef)arg4 type:(int)arg5 memoryReader:(id)arg6;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)_ivarDescription:(unsigned int)arg1 withSpacing:(unsigned int)arg2;
- (void)_logDescriptionWithSuperclasses:(BOOL)arg1 indentation:(int)arg2 toLogger:(id)arg3;
- (void)_scanFieldsToOffset:(unsigned int)arg1 withBlock:(id)arg2;
- (void)scanObject:(unsigned long long)arg1 ofSize:(unsigned int)arg2 withBlock:(id)arg3;
- (void)setMemoryReader:(id)arg1;
- (void)enumerateIvarsWithBlock:(id)arg1;
@property(readonly) NSString *binaryName; // @synthesize binaryName=_remoteBinaryName;
- (id)type;
@property(readonly) NSString *typeName;
@property(readonly) int infoType;
@property(readonly) NSString *fullIvarDescription;
@property(readonly) NSString *shortIvarDescription;
- (id)debugDescription;
- (id)description;
@property(readonly) BOOL isARR;
@property(readonly) BOOL isRealized;
@property(readonly) BOOL isMetaClass;
@property(readonly) BOOL isRootClass;
@property(readonly) BOOL hasCppConstructorOrDestructor;
@property(readonly) NSString *className; // @synthesize className=_remoteClassName;
@property(readonly) unsigned long long remoteIsa; // @synthesize remoteIsa=_remoteIsa;
@property(readonly) unsigned int instanceSize; // @synthesize instanceSize=_instanceSize;

@end

