/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface VMUHeader : NSObject
{
}

+ (id)extractMachOHeadersFromHeader:(id)arg1 matchingArchitecture:(id)arg2 considerArchives:(BOOL)arg3;
+ (id)headerWithMemory:(id)arg1 address:(unsigned long long)arg2 name:(id)arg3 path:(id)arg4 timestamp:(id)arg5;
+ (id)headerWithUniverse:(id)arg1 memory:(id)arg2 name:(id)arg3 path:(id)arg4 timestamp:(id)arg5;
- (BOOL)isFat;
- (BOOL)isMachO;
- (BOOL)isMachO32;
- (BOOL)isMachO64;
- (BOOL)isArchive;
- (id)signature;

@end

