/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class VMULinkedListEntry;

@interface VMULinkedList : NSObject
{
    VMULinkedListEntry *_head;
    VMULinkedListEntry *_tail;
}

+ (id)linkedList;
- (id)init;
- (id)head;
- (id)tail;
- (void)removeAllObjects;
- (void)pushHead:(id)arg1;
- (id)popTail;
- (void)remove:(id)arg1;

@end

