/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDictionary, NSString;

@interface VMULazySymbolOwner : NSObject
{
    NSString *_name;
    NSDictionary *_signature;
    NSArray *_regions;
    unsigned int _flags;
}

+ (id)lazySymbolOwnerWithName:(id)arg1 signature:(id)arg2 regions:(id)arg3 flags:(unsigned int)arg4;
- (id)initWithName:(id)arg1 signature:(id)arg2 regions:(id)arg3 flags:(unsigned int)arg4;
- (id)regions;
- (BOOL)isLazy;
- (BOOL)isProtected;
- (id)name;
- (id)signature;
- (id)path;
- (id)architecture;
- (BOOL)containsAddress:(unsigned long long)arg1;
- (BOOL)overlapsAddressRange:(struct _VMURange)arg1;
- (BOOL)hasRegionsForName:(id)arg1;
- (unsigned int)flags;
- (void)slideToSegmentAddresses:(id)arg1;
- (BOOL)validate;
- (id)description;
- (void)dealloc;

@end

