/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface VMULoadCommand : NSObject
{
    unsigned long long _cmdSize;
    unsigned int _command;
}

+ (id)loadCommandWithMemory:(id)arg1;
- (id)initWithMemory:(id)arg1;
- (unsigned long long)cmdSize;
- (BOOL)isUUID;
- (BOOL)isSymTab;
- (BOOL)isDySymTab;
- (BOOL)isDyLinker;
- (BOOL)isLoadDyLib;
- (BOOL)isIDDyLib;
- (BOOL)isSegment;
- (BOOL)isSegment32;
- (BOOL)isSegment64;

@end

