/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Symbolication/VMURangeArray.h>

@interface VMUNonOverlappingRangeArray : VMURangeArray
{
}

- (void)addRange:(struct _VMURange)arg1;
- (void)sortAndMergeRanges;
- (void)mergeRange:(struct _VMURange)arg1;
- (void)mergeRanges:(id)arg1;
- (void)mergeRange:(struct _VMURange)arg1 excludingRanges:(id)arg2;
- (void)mergeRanges:(id)arg1 excludingRanges:(id)arg2;
- (void)_mergeAllBitsOfRange:(struct _VMURange)arg1 excludingRanges:(id)arg2 mergeRanges:(BOOL)arg3;
- (id)subtract:(id)arg1 mergeRanges:(BOOL)arg2;
- (struct _VMURange)largestUnusedWithInUse:(id)arg1;

@end

