/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSHashTable, NSMutableSet, VMUClassInfoMap, VMUNonOverlappingRangeArray;

@interface VMUObjectIdentifier : NSObject
{
    unsigned int _task;
    struct _CSTypeRef _symbolicator;
    id _memoryReader;
    VMUClassInfoMap *_isaToClassInfo;
    VMUClassInfoMap *_cfTypeIDtoClassInfo;
    NSHashTable *_objcRuntimeMallocBlocksHash;
    NSMutableSet *_objcRuntimeMallocBlocks;
    unsigned int _cfTypeCount;
    unsigned int _objcClassCount;
    unsigned int _cPlusPlusClassCount;
    NSHashTable *_invalidPointers;
    VMUNonOverlappingRangeArray *_targetProcessVMranges;
    int peeksAtRemoteObjectIsa;
}

- (id)initWithTask:(unsigned int)arg1;
- (id)initWithTask:(unsigned int)arg1 symbolicator:(id)arg2;
- (void)dealloc;
- (unsigned int)CFTypeCount;
- (unsigned int)ObjCclassCount;
- (unsigned int)CPlusPlusClassCount;
- (id)objcRuntimeMallocBlocksHash;
- (id)objcRuntimeMallocBlocks;
- (BOOL)isValidRemotePointer:(unsigned long long)arg1;
- (id)classInfoForIsaPointer:(unsigned int)arg1;
- (id)classInfoForCFType:(struct __CFRuntimeBase *)arg1;
- (id)classInfoForObject:(unsigned long long)arg1;
- (id)_classInfoForObject:(unsigned long long)arg1;
- (id)nullClassInfo;
- (id)classInfoForObjectWithRange:(struct _VMURange)arg1;
- (void)findCFTypes;
- (void)findObjCclasses;
- (struct _VMURange)vmRegionRangeForAddress:(unsigned long long)arg1;

@end

