/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMapTable;

@interface VMUProcList : NSObject
{
    NSLock *procLock;
    NSMapTable *allProcs;
    NSMapTable *filteredProcs;
    BOOL appsOnly;
    BOOL ownedOnly;
}

- (id)init;
- (void)dealloc;
- (void)finalize;
- (void)setProcInfos:(id)arg1;
- (void)addProcInfo:(id)arg1;
- (void)removeProcInfo:(id)arg1;
- (BOOL)update;
- (void)_populateFromSystem;
- (BOOL)updateFromSystem;
- (void)setOwnedOnly:(BOOL)arg1;
- (BOOL)ownedOnly:(BOOL)arg1;
- (void)setAppsOnly:(BOOL)arg1;
- (BOOL)appsOnly;
- (unsigned int)count;
- (id)allProcInfos;
- (id)allPIDs;
- (id)allNames;
- (id)allPathNames;
- (id)newestProcInfo;
- (id)newestProcInfoWithName:(id)arg1;
- (id)newestProcInfoSatisfyingCondition:(SEL)arg1 forTarget:(id)arg2 withContext:(void *)arg3;
- (id)newestProcInfoSatisfyingCondition:(SEL)arg1 forTarget:(id)arg2;
- (id)procInfoWithPID:(int)arg1;

@end

