/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSCalendarDate, NSDictionary, NSMutableArray, NSString;

@interface VMUProcessDescription : NSObject
{
    unsigned int _task;
    int _pid;
    struct _CSTypeRef _symbolicator;
    NSString *_processName;
    BOOL _processNameNeedsCorrection;
    NSString *_executablePath;
    BOOL _executablePathNeedsCorrection;
    unsigned long long _executableLoadAddress;
    int _cpuType;
    BOOL _isNative;
    BOOL _is64Bit;
    NSDictionary *_lsApplicationInformation;
    NSMutableArray *_binaryImages;
    NSArray *_sortedBinaryImages;
    NSDictionary *_binaryImageHints;
    NSArray *_unreadableBinaryImagePaths;
    BOOL _binaryImagePostProcessingComplete;
    NSDictionary *_buildVersionDictionary;
    NSDictionary *_osVersionDictionary;
    NSString *_parentProcessName;
    NSString *_parentExecutablePath;
    int _ppid;
    NSCalendarDate *_date;
    NSString *_internalError;
}

- (id)initWithPid:(int)arg1 orTask:(unsigned int)arg2;
- (double)_extractDyldInfoFromSymbolOwner:(struct _CSTypeRef)arg1 withNonContiguousMemory:(id)arg2;
- (id)_readDataFromMemory:(id)arg1 atAddress:(unsigned long long)arg2 size:(unsigned long)arg3;
- (id)_extractInfoPlistFromSymbolOwner:(struct _CSTypeRef)arg1 withNonContiguousMemory:(id)arg2;
- (void)_extractBinaryImageInfoFromSymbolOwner:(struct _CSTypeRef)arg1;
- (id)date;
- (unsigned int)task;
- (int)pid;
- (int)cpuType;
- (id)processName;
- (id)processIdentifier;
- (id)displayName;
- (id)parentProcessName;
- (id)processVersionDictionary;
- (id)_sanitizeVersion:(id)arg1;
- (id)processVersion;
- (id)executablePath;
- (id)bundleIdentifier;
- (BOOL)isTranslated;
- (BOOL)isAppleApplication;
- (id)_bundleLock;
- (id)binaryImages;
- (id)binaryImageDictionaryForAddress:(unsigned long long)arg1;
- (id)_cpuTypeDescription;
- (id)_binaryImagesDescriptionForRanges:(id)arg1;
- (id)_rangesOfBinaryImages:(id)arg1 forBacktraces:(id)arg2;
- (id)binaryImagesDescriptionForBacktraces:(id)arg1;
- (id)binaryImagesDescription;
- (id)_buildVersionDictionary;
- (id)_buildInfoDescription;
- (id)_osVersionDictionary;
- (id)_systemVersionDescription;
- (id)processDescriptionHeader;
- (id)dateAndVersionDescription;
- (id)description;
- (void)dealloc;

@end

