/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Symbolication/VMUAddressRange.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString, VMUSymbolOwner;

@interface VMURegion : VMUAddressRange <NSCoding, NSCopying>
{
    VMUSymbolOwner *_owner;
    NSString *_name;
}

+ (id)regionWithOwner:(id)arg1 name:(id)arg2 addressRange:(struct _VMURange)arg3;
- (id)initWithOwner:(id)arg1 name:(id)arg2 addressRange:(struct _VMURange)arg3;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)owner;
- (id)name;
- (struct _VMURange)addressRange;
- (int)compare:(id)arg1;
- (BOOL)isEqualToRegion:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

