/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Symbolication/VMUSymbolOwner.h>

@interface VMUSymbolOwner (Private)
- (BOOL)isLazy;
- (id)symbolOwnerByAddingContentsOfOwner:(id)arg1;
- (void)slideToSegmentAddresses:(id)arg1;
- (id)programTextForAddress:(unsigned long long)arg1;
- (id)programTextForAddressRange:(struct _VMURange)arg1;
- (unsigned long long)size;
- (BOOL)validate;
@end

