/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Symbolication/VMULoadCommand.h>

@class NSArray, NSString;

@interface VMUSegmentLoadCommand : VMULoadCommand
{
    NSString *_name;
    unsigned long long _vmaddr;
    unsigned long long _vmsize;
    unsigned long long _fileoff;
    unsigned long long _filesize;
    int _maxprot;
    int _initprot;
    unsigned int _flags;
    NSArray *_sections;
}

- (BOOL)isSegment;
- (id)name;
- (unsigned long long)vmaddr;
- (unsigned long long)vmsize;
- (unsigned long long)fileoff;
- (unsigned long long)filesize;
- (int)maxprot;
- (int)initprot;
- (unsigned int)flags;
- (id)sections;
- (id)sectionNamed:(id)arg1;
- (id)description;
- (void)dealloc;

@end

