/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, VMUMachTaskContainer;

@interface VMUTask : NSObject
{
    id <VMUMemory> _memory;
    VMUMachTaskContainer *_machTaskContainer;
    BOOL _isTranslated;
    NSArray *_headers;
}

+ (BOOL)pidIsTranslated:(int)arg1;
+ (id)findDyldHeaderInMemory:(id)arg1 address:(unsigned long long)arg2;
+ (id)taskWithMachTaskContainer:(id)arg1;
- (id)initWithMachTaskContainer:(id)arg1;
- (BOOL)isTranslated;
- (int)pid;
- (id)memory;
- (unsigned int)task;
- (id)headers;
- (void)dealloc;

@end

