/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    float width;
    float height;
};

struct _NSRange {
    unsigned int _field1;
    unsigned int _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned char length;
    float v[4];
} CDStruct_d27e73f0;

typedef struct {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
    double _field7;
    double _field8;
    double _field9;
} CDStruct_afa449f9;

typedef struct {
    unsigned int *data;
    struct __IOSurface *ioSurface;
    unsigned int textureID;
    unsigned int width;
    unsigned int height;
    unsigned int textureWidth;
    unsigned int textureHeight;
    float centerX;
    float centerY;
    float scale;
    float rotationAngle;
    unsigned char orientation;
} CDStruct_911c9307;

