/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCFilter, MCPlug, MCSlide, NSArray, NSMutableSet, NSRecursiveLock, NSSet, NSString;

@interface MCAnimationPath : MCObject
{
    NSString *mKey;
    NSMutableSet *mKeyframes;
    NSRecursiveLock *mKeyframesLock;
    MCPlug *mPlugIfPlugAnimationPath;
    MCSlide *mSlideIfSlideAnimationPath;
    MCFilter *mFilterIfFilterAnimationPath;
    MCPlug *mCachedParentPlug;
    NSArray *mCachedOrderedKeyframes;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(readonly) NSSet *keyframes;
- (unsigned int)countOfKeyframes;
@property(readonly) NSArray *orderedKeyframes;
- (double)relativeTimeForKeyframe:(id)arg1;
- (id)createKeyframeWithScalar:(float)arg1 atTime:(double)arg2;
- (id)createKeyframeWithScalar:(float)arg1 atTime:(double)arg2 offsetKind:(int)arg3;
- (id)createKeyframeWithFunction:(id)arg1 atTime:(double)arg2 offsetKind:(int)arg3 forDuration:(double)arg4;
- (id)createKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2;
- (id)createKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2 offsetKind:(int)arg3;
- (id)createKeyframeWithVector:(CDStruct_d27e73f0)arg1 atTime:(double)arg2;
- (id)createKeyframeWithVector:(CDStruct_d27e73f0)arg1 atTime:(double)arg2 offsetKind:(int)arg3;
- (void)removeKeyframe:(id)arg1;
- (void)removeAllKeyframes;
- (id)description;
@property MCFilter *filterIfFilterAnimationPath; // @synthesize filterIfFilterAnimationPath=mFilterIfFilterAnimationPath;
@property MCSlide *slideIfSlideAnimationPath; // @synthesize slideIfSlideAnimationPath=mSlideIfSlideAnimationPath;
@property MCPlug *plugIfPlugAnimationPath; // @synthesize plugIfPlugAnimationPath=mPlugIfPlugAnimationPath;
@property(copy) NSString *key; // @synthesize key=mKey;

@end

