/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCAnimationKeyframe.h>

@class NSString;

@interface MCAnimationKeyframeFunction : MCAnimationKeyframe
{
    double mDuration;
    NSString *mFunction;
    double mFunctionTimeOffset;
    double mFunctionTimeFactor;
    double mInnerEaseInControl;
    double mInnerEaseOutControl;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)dealloc;
- (id)imprint;
@property(nonatomic) double duration; // @synthesize duration=mDuration;
@property(copy) NSString *function;
@property(nonatomic) double functionTimeOffset; // @synthesize functionTimeOffset=mFunctionTimeOffset;
@property(nonatomic) double functionTimeFactor; // @synthesize functionTimeFactor=mFunctionTimeFactor;
@property(nonatomic) double innerEaseInControl; // @synthesize innerEaseInControl=mInnerEaseInControl;
@property(nonatomic) double innerEaseOutControl; // @synthesize innerEaseOutControl=mInnerEaseOutControl;
- (id)description;

@end

