/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCAnimationPath, NSString;

@interface MCAnimationKeyframe : MCObject
{
    double mTimeOffset;
    int mTimeOffsetKind;
    NSString *mTimeOffsetArgument;
    double mPreControl;
    double mPostControl;
    MCAnimationPath *mAnimationPath;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(nonatomic) double timeOffset; // @synthesize timeOffset=mTimeOffset;
@property(nonatomic) int timeOffsetKind; // @synthesize timeOffsetKind=mTimeOffsetKind;
@property(copy) NSString *timeOffsetArgument;
@property(nonatomic) double preControl; // @synthesize preControl=mPreControl;
@property(nonatomic) double postControl; // @synthesize postControl=mPostControl;
- (id)description;
@property MCAnimationPath *animationPath; // @synthesize animationPath=mAnimationPath;

@end

