/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCAnimationKeyframe.h>

@interface MCAnimationKeyframe1D : MCAnimationKeyframe
{
    float mValue;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (id)imprint;
@property(nonatomic) float value; // @synthesize value=mValue;
- (id)description;

@end

