/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCAnimationKeyframe.h>

@interface MCAnimationKeyframe2D : MCAnimationKeyframe
{
    struct CGPoint mPoint;
    struct CGPoint mC1;
    struct CGPoint mC2;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (id)imprint;
@property(nonatomic) struct CGPoint point; // @synthesize point=mPoint;
@property(nonatomic) struct CGPoint c1; // @synthesize c1=mC1;
@property(nonatomic) struct CGPoint c2; // @synthesize c2=mC2;

@end

