/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol MCAssetPathDelegate
- (id)absolutePathForAssetPath:(id)arg1;
- (id)absolutePathForAssetPath:(id)arg1 andSize:(struct CGSize)arg2;
- (struct CGImage *)retainedCGImageForAssetPath:(id)arg1 andSize:(struct CGSize)arg2 orientation:(char *)arg3;
- (struct __IOSurface *)retainedIOSurfaceForAssetPath:(id)arg1 andSize:(struct CGSize)arg2 orientation:(char *)arg3;
@end

