/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class NSMutableSet, NSString;

@interface MCAsset : MCObject
{
    NSString *mPath;
    NSString *mCachedWorkingPath;
    NSMutableSet *mTexts;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(copy, nonatomic) NSString *path; // @synthesize path=mPath;
@property(copy) NSString *workingPath;
@property(readonly) BOOL isInUse;
- (void)learnText:(id)arg1;
- (void)forgetText:(id)arg1;
- (id)snapshot;
- (void)_copySelfToSnapshot:(id)arg1;

@end

