/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCAsset.h>

@class NSMutableDictionary, NSMutableSet;

@interface MCAssetVideo : MCAsset
{
    NSMutableSet *mSlides;
    NSMutableDictionary *mCachedWorkingPaths;
}

- (id)init;
- (void)demolish;
- (void)setPath:(id)arg1;
- (id)workingPathForSize:(struct CGSize)arg1;
- (struct CGImage *)retainedCGImageForSize:(struct CGSize)arg1 orientation:(char *)arg2;
- (struct __IOSurface *)retainedIOSurfaceForSize:(struct CGSize)arg1 orientation:(char *)arg2;
- (void)setWorkingPath:(id)arg1;
- (BOOL)isInUse;
- (void)learnSlide:(id)arg1;
- (void)forgetSlide:(id)arg1;

@end

