/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCContainer, NSArray, NSMutableSet, NSRecursiveLock, NSSet;

@interface MCAudioPlaylist : MCObject
{
    NSMutableSet *mSongs;
    NSRecursiveLock *mSongsLock;
    NSArray *mCachedOrderedSongs;
    float mVolume;
    double mFadeInDuration;
    double mFadeOutDuration;
    float mDuckLevel;
    double mDuckInDuration;
    double mDuckOutDuration;
    MCContainer *mContainer;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly) NSSet *songs;
- (unsigned int)countOfSongs;
- (id)songAtIndex:(unsigned int)arg1;
- (id)addSongForAsset:(id)arg1;
- (id)addSongsForAssets:(id)arg1;
- (id)insertSongForAsset:(id)arg1 atIndex:(unsigned int)arg2;
- (id)insertSongsForAssets:(id)arg1 atIndex:(unsigned int)arg2;
- (void)removeSongsAtIndices:(id)arg1;
- (void)removeAllSongs;
- (void)moveSongsAtIndices:(id)arg1 toIndex:(unsigned int)arg2;
@property(readonly) NSArray *orderedSongs;
@property MCContainer *container; // @synthesize container=mContainer;
@property double duckOutDuration; // @synthesize duckOutDuration=mDuckOutDuration;
@property double duckInDuration; // @synthesize duckInDuration=mDuckInDuration;
@property float duckLevel; // @synthesize duckLevel=mDuckLevel;
@property double fadeOutDuration; // @synthesize fadeOutDuration=mFadeOutDuration;
@property double fadeInDuration; // @synthesize fadeInDuration=mFadeInDuration;
@property float volume; // @synthesize volume=mVolume;

@end

