/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCContainer.h>

@class NSArray, NSMutableSet, NSRecursiveLock, NSSet, NSString;

@interface MCContainerParallelizer : MCContainer
{
    NSMutableSet *mPlugs;
    NSRecursiveLock *mPlugsLock;
    NSArray *mCachedZOrderedPlugs;
    struct CGColor *mBackgroundColor;
    NSString *mPageIDAtStart;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property struct CGColor *backgroundColor; // @synthesize backgroundColor=mBackgroundColor;
@property(readonly) NSSet *plugs;
- (unsigned int)countOfPlugs;
- (id)plugForID:(id)arg1;
- (id)setPlugForContainer:(id)arg1 forID:(id)arg2;
- (void)removePlug:(id)arg1;
- (void)removePlugForID:(id)arg1;
@property(readonly) NSArray *zOrderedPlugs;
@property(copy) NSString *pageIDAtStart; // @synthesize pageIDAtStart=mPageIDAtStart;

@end

