/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCContainer.h>

@class NSArray, NSDictionary, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSSet, NSString;

@interface MCContainerEffect : MCContainer
{
    NSMutableSet *mSlides;
    NSRecursiveLock *mSlidesLock;
    NSArray *mCachedOrderedSlides;
    NSMutableSet *mTexts;
    NSRecursiveLock *mTextsLock;
    NSArray *mCachedOrderedTexts;
    NSString *mEffectID;
    NSMutableDictionary *mEffectAttributes;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initFromScratchWithMontage:(id)arg1;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly) NSSet *slides;
@property(readonly) NSArray *orderedSlides;
- (unsigned int)countOfSlides;
- (id)slideAtIndex:(unsigned int)arg1;
- (id)addSlide;
- (id)addSlides:(int)arg1;
- (id)insertSlideAtIndex:(int)arg1;
- (id)addSlideForAsset:(id)arg1;
- (id)addSlidesForAssets:(id)arg1;
- (id)insertSlideForAsset:(id)arg1 atIndex:(unsigned int)arg2;
- (id)insertSlidesForAssets:(id)arg1 atIndex:(unsigned int)arg2;
- (void)removeSlidesAtIndices:(id)arg1;
- (void)removeAllSlides;
- (void)moveSlidesAtIndices:(id)arg1 toIndex:(unsigned int)arg2;
@property(readonly) NSSet *texts;
@property(readonly) NSArray *orderedTexts;
- (unsigned int)countOfTexts;
- (id)textAtIndex:(unsigned int)arg1;
- (id)addTextForAttributedString:(id)arg1;
- (id)addTextsForAttributedStrings:(id)arg1;
- (id)addTextForAsset:(id)arg1 andKey:(id)arg2;
- (id)addTextsForAssets:(id)arg1 andKey:(id)arg2;
- (id)insertTextForAttributedString:(id)arg1 atIndex:(unsigned int)arg2;
- (id)insertTextsForAttributedStrings:(id)arg1 atIndex:(unsigned int)arg2;
- (id)insertTextForAsset:(id)arg1 andKey:(id)arg2 atIndex:(unsigned int)arg3;
- (id)insertTextsForAssets:(id)arg1 andKey:(id)arg2 atIndex:(unsigned int)arg3;
- (void)removeTextsAtIndices:(id)arg1;
- (void)removeAllTexts;
- (void)moveTextsAtIndices:(id)arg1 toIndex:(unsigned int)arg2;
- (id)effectAttributeForKey:(id)arg1;
- (void)setEffectAttribute:(id)arg1 forKey:(id)arg2;
@property(copy) NSDictionary *effectAttributes;
@property(copy) NSString *effectID; // @synthesize effectID=mEffectID;

@end

