/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCContainer.h>

@class NSArray, NSMutableSet, NSRecursiveLock, NSSet;

@interface MCContainerSerializer : MCContainer
{
    NSMutableSet *mPlugs;
    NSRecursiveLock *mPlugsLock;
    NSArray *mCachedOrderedPlugs;
    double mCachedDuration;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(readonly) double duration;
@property(readonly) NSSet *plugs;
- (unsigned int)countOfPlugs;
- (id)plugAtIndex:(unsigned int)arg1;
- (id)addPlugForContainer:(id)arg1;
- (id)addPlugsForContainers:(id)arg1;
- (id)insertPlugForContainer:(id)arg1 atIndex:(unsigned int)arg2;
- (id)insertPlugsForContainers:(id)arg1 atIndex:(unsigned int)arg2;
- (void)removePlugsAtIndices:(id)arg1;
- (void)movePlugsAtIndices:(id)arg1 toIndex:(unsigned int)arg2;
@property(readonly) NSArray *orderedPlugs;
- (double)timeInForPlug:(id)arg1;

@end

