/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCPlug, MCSlide, NSDictionary, NSMutableDictionary, NSMutableSet, NSRecursiveLock, NSString;

@interface MCFilter : MCObject
{
    NSString *mFilterID;
    NSMutableDictionary *mAttributes;
    unsigned int mIndex;
    NSMutableSet *mAnimationPaths;
    NSRecursiveLock *mAnimationPathsLock;
    MCPlug *mPlugIfPlugFilter;
    MCSlide *mSlideIfSlideFilter;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)attributeForKey:(id)arg1;
- (void)setAttribute:(id)arg1 forKey:(id)arg2;
@property(copy) NSDictionary *attributes;
@property MCSlide *slideIfSlideFilter; // @synthesize slideIfSlideFilter=mSlideIfSlideFilter;
@property MCPlug *plugIfPlugFilter; // @synthesize plugIfPlugFilter=mPlugIfPlugFilter;
@property(copy) NSString *filterID; // @synthesize filterID=mFilterID;
@property unsigned int index; // @synthesize index=mIndex;

@end

