/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MCPlug, NSDictionary, NSMutableDictionary, NSRecursiveLock, NSString;

@interface MCMontage : NSObject
{
    MCPlug *mRootPlug;
    double mAudioFadeOutDuration;
    NSString *mBasePath;
    id <MCAssetPathDelegate> mAssetPathDelegate;
    NSDictionary *mImprintWhileLoading;
    NSMutableDictionary *mVideoAssetsForFilePaths;
    NSMutableDictionary *mVideoAssetsForObjectIDs;
    NSMutableDictionary *mAudioAssetsForFilePaths;
    NSMutableDictionary *mAudioAssetsForObjectIDs;
    NSMutableDictionary *mContainersForObjectIDs;
    NSRecursiveLock *mLock;
}

- (id)init;
- (id)initFromScratch;
- (id)initWithData:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (void)demolish;
- (id)data;
- (void)lock;
- (void)unlock;
- (id)createSerializerContainer;
- (id)createParallelizerContainer;
- (id)createEffectContainer;
- (id)videoAssetForFileAtPath:(id)arg1;
- (id)audioAssetForFileAtPath:(id)arg1;
- (id)assetForObjectID:(id)arg1;
- (id)videoAssetForObjectID:(id)arg1;
- (id)audioAssetForObjectID:(id)arg1;
- (id)assets;
- (id)videoAssets;
- (id)audioAssets;
- (id)containerForObjectID:(id)arg1;
- (void)forgetAboutContainer:(id)arg1;
@property id <MCAssetPathDelegate> assetPathDelegate; // @synthesize assetPathDelegate=mAssetPathDelegate;
@property(copy) NSString *basePath; // @synthesize basePath=mBasePath;
@property double audioFadeOutDuration; // @synthesize audioFadeOutDuration=mAudioFadeOutDuration;
@property(readonly) MCPlug *rootPlug; // @synthesize rootPlug=mRootPlug;

@end

