/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCPlug.h>

@class MCContainerSerializer, NSDictionary, NSMutableDictionary, NSString;

@interface MCPlugSerial : MCPlug
{
    unsigned int mIndex;
    NSString *mTransitionID;
    double mTransitionDuration;
    NSMutableDictionary *mTransitionAttributes;
    MCContainerSerializer *mSupercontainer;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(nonatomic) double transitionDuration; // @synthesize transitionDuration=mTransitionDuration;
- (id)transitionAttributeForKey:(id)arg1;
- (void)setTransitionAttribute:(id)arg1 forKey:(id)arg2;
@property(copy) NSDictionary *transitionAttributes;
- (id)snapshot;
- (void)_copySelfToSnapshot:(id)arg1;
@property MCContainerSerializer *supercontainer; // @synthesize supercontainer=mSupercontainer;
@property(copy) NSString *transitionID; // @synthesize transitionID=mTransitionID;
@property unsigned int index; // @synthesize index=mIndex;

@end

