/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCContainer, MCLink, NSArray, NSMutableSet, NSRecursiveLock;

@interface MCPlug : MCObject
{
    MCContainer *mContainer;
    NSMutableSet *mAnimationPaths;
    NSRecursiveLock *mAnimationPathsLock;
    NSMutableSet *mFilters;
    NSRecursiveLock *mFiltersLock;
    NSArray *mCachedOrderedFilters;
    double mPhaseInDuration;
    double mMainDuration;
    double mPhaseOutDuration;
    double mNumberOfLoops;
    MCLink *mLink;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property(retain) MCContainer *container;
@property(retain) MCLink *link;
@property(nonatomic) double phaseInDuration; // @synthesize phaseInDuration=mPhaseInDuration;
@property(nonatomic) double mainDuration; // @synthesize mainDuration=mMainDuration;
@property(nonatomic) double phaseOutDuration; // @synthesize phaseOutDuration=mPhaseOutDuration;
@property(readonly) double fullDuration;
@property(nonatomic) double numberOfLoops; // @synthesize numberOfLoops=mNumberOfLoops;
- (id)snapshot;
- (void)_copySelfToSnapshot:(id)arg1;

@end

