/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCPlug.h>

@class MCContainerParallelizer, NSString;

@interface MCPlugParallel : MCPlug
{
    NSString *mIDInSupercontainer;
    NSString *mPageID;
    double mTimeIn;
    struct CGPoint mPosition;
    struct CGSize mSize;
    float mZPosition;
    int mZIndex;
    float mRotationAngle;
    float mXRotationAngle;
    float mYRotationAngle;
    float mOpacity;
    int mAudioPriority;
    MCContainerParallelizer *mSupercontainer;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(nonatomic) struct CGSize size; // @synthesize size=mSize;
@property(nonatomic) double timeIn; // @synthesize timeIn=mTimeIn;
@property(nonatomic) float opacity; // @synthesize opacity=mOpacity;
- (id)snapshot;
- (void)_copySelfToSnapshot:(id)arg1;
@property MCContainerParallelizer *supercontainer; // @synthesize supercontainer=mSupercontainer;
@property int audioPriority; // @synthesize audioPriority=mAudioPriority;
@property float yRotationAngle; // @synthesize yRotationAngle=mYRotationAngle;
@property float xRotationAngle; // @synthesize xRotationAngle=mXRotationAngle;
@property float rotationAngle; // @synthesize rotationAngle=mRotationAngle;
@property int zIndex; // @synthesize zIndex=mZIndex;
@property float zPosition; // @synthesize zPosition=mZPosition;
@property struct CGPoint position; // @synthesize position=mPosition;
@property(copy) NSString *pageID; // @synthesize pageID=mPageID;
@property(copy, getter=idInSupercontainer, setter=setIDInSupercontainer:) NSString *idInSupercontainer; // @synthesize idInSupercontainer=mIDInSupercontainer;

@end

