/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCAssetAudio, MCAudioPlaylist, MCSlide;

@interface MCSong : MCObject
{
    MCAssetAudio *mAsset;
    float mVolume;
    double mFadeInDuration;
    double mFadeOutDuration;
    unsigned int mIndex;
    double mStartTime;
    double mDuration;
    BOOL mStartTimeIsDefined;
    BOOL mDurationIsDefined;
    MCAudioPlaylist *mAudioPlaylistIfAudioPlaylistSong;
    MCSlide *mSlideIfSlideSong;
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property(retain) MCAssetAudio *asset;
- (void)undefineStartTime;
@property(nonatomic) double startTime; // @synthesize startTime=mStartTime;
- (void)undefineDuration;
@property(nonatomic) double duration; // @synthesize duration=mDuration;
- (id)snapshot;
- (void)_copySelfToSnapshot:(id)arg1;
@property MCSlide *slideIfSlideSong; // @synthesize slideIfSlideSong=mSlideIfSlideSong;
@property MCAudioPlaylist *audioPlaylistIfAudioPlaylistSong; // @synthesize audioPlaylistIfAudioPlaylistSong=mAudioPlaylistIfAudioPlaylistSong;
@property(readonly) BOOL durationIsDefined; // @synthesize durationIsDefined=mDurationIsDefined;
@property(readonly) BOOL startTimeIsDefined; // @synthesize startTimeIsDefined=mStartTimeIsDefined;
@property unsigned int index; // @synthesize index=mIndex;
@property double fadeOutDuration; // @synthesize fadeOutDuration=mFadeOutDuration;
@property double fadeInDuration; // @synthesize fadeInDuration=mFadeInDuration;
@property float volume; // @synthesize volume=mVolume;

@end

