/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MCObject.h>

@class MCAsset, MCContainerEffect, NSAttributedString, NSString;

@interface MCText : MCObject
{
    unsigned int mIndex;
    NSAttributedString *mAttributedString;
    MCAsset *mAsset;
    NSString *mKeyInAsset;
    MCContainerEffect *mContainer;
}

- (id)init;
- (id)initWithImprint:(id)arg1 andMontage:(id)arg2;
- (void)demolish;
- (id)imprint;
@property MCContainerEffect *container; // @synthesize container=mContainer;
@property(copy) NSAttributedString *attributedString; // @synthesize attributedString=mAttributedString;
@property(copy) NSString *keyInAsset; // @synthesize keyInAsset=mKeyInAsset;
@property(retain) MCAsset *asset; // @synthesize asset=mAsset;
@property unsigned int index; // @synthesize index=mIndex;

@end

