/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface MPAnimationManager : NSObject
{
    NSMutableDictionary *mAnimations;
    NSMutableDictionary *mAnimationSets;
}

+ (id)sharedManager;
+ (void)releaseSharedManager;
- (void)dealloc;
- (id)animationDescriptionForAnimationID:(id)arg1;

@end

