/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAnimationKeyframe.h>

@class MPVector;

@interface MPAnimationKeyframeVector : MPAnimationKeyframe
{
    MPVector *_vector;
}

+ (id)keyframeVectorWithVector:(id)arg1 atTime:(double)arg2;
+ (id)keyframeVectorWithVector:(id)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)initKeyframeVectorWithVector:(id)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)vector;
- (void)setVector:(id)arg1;

@end

