/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAnimationKeyframe.h>

@interface MPAnimationKeyframe1D : MPAnimationKeyframe
{
    float _scalar;
}

+ (id)keyframe1DWithScalar:(float)arg1 atTime:(double)arg2;
+ (id)keyframe1DWithScalar:(float)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)initKeyframe1DWithScalar:(float)arg1 atTime:(double)arg2 offset:(int)arg3;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (float)scalar;
- (void)setScalar:(float)arg1;

@end

