/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCAnimationPath, NSMutableSet, NSObject<MPAnimationSupport>;

@interface MPAnimationPath : NSObject <NSCoding, NSCopying>
{
    MCAnimationPath *_animationPath;
    NSMutableSet *_keyframes;
    BOOL _postKeyframeChange;
    NSObject<MPAnimationSupport> *_parentObject;
}

+ (id)animationPath;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)key;
- (id)keyframes;
- (id)orderedKeyframes;
- (void)addKeyframe:(id)arg1;
- (void)addKeyframes:(id)arg1;
- (void)removeKeyframe:(id)arg1;
- (void)removeKeyframes:(id)arg1;
- (void)removeAllKeyframes;
- (id)createKeyframeWithScalar:(float)arg1 atTime:(double)arg2;
- (id)createKeyframeWithScalar:(float)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)createKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2;
- (id)createKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)createKeyframeWithVector:(id)arg1 atTime:(double)arg2;
- (id)createKeyframeWithVector:(id)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)newKeyframeWithScalar:(float)arg1 atTime:(double)arg2;
- (id)newKeyframeWithScalar:(float)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)newKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2;
- (id)newKeyframeWithPoint:(struct CGPoint)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)newKeyframeWithVector:(id)arg1 atTime:(double)arg2;
- (id)newKeyframeWithVector:(id)arg1 atTime:(double)arg2 offset:(int)arg3;
- (id)parent;
- (BOOL)postsKeyframeChangeNotifications;
- (void)setPostsKeyframeChangeNotifications:(BOOL)arg1;
- (double)relativeTimeForKeyframe:(id)arg1;

@end

