/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPAssetManager : NSObject
{
}

+ (id)sharedManager;
+ (void)releaseSharedManager;
- (id)thumbnailForAssetAtPath:(id)arg1;
- (double)durationForAssetAtPath:(id)arg1;
- (double)startTimeForAssetAtPath:(id)arg1;
- (double)stopTimeForAssetAtPath:(id)arg1;
- (struct CGSize)resolutionForAssetAtPath:(id)arg1;
- (id)creationDateForAssetAtPath:(id)arg1;
- (id)keywordsForAssetAtPath:(id)arg1;
- (id)latitudeForAssetAtPath:(id)arg1;
- (id)longitudeForAssetAtPath:(id)arg1;
- (id)altitudeForAssetAtPath:(id)arg1;
- (BOOL)isAssetAtPathASupportedImage:(id)arg1;
- (BOOL)isAssetAtPathASupportedMovie:(id)arg1;
- (BOOL)isAssetAtPathASupportedAudio:(id)arg1;
- (id)regionsOfInterestForAssetAtPath:(id)arg1;

@end

