/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAssetManager.h>

@interface MPAssetManager (Private)
- (void)tryToSaveCache;
- (struct CGRect)regionOfInterestAtIndex:(int)arg1 forAssetAtPath:(id)arg2;
- (void)addRegionOfInterest:(struct CGRect)arg1 forAssetAtPath:(id)arg2 saveToCache:(BOOL)arg3;
- (void)setRegionOfInterest:(struct CGRect)arg1 atIndex:(int)arg2 forAssetAtPath:(id)arg3 saveToCache:(BOOL)arg4;
- (void)updateRegionOfInterestAtIndex:(int)arg1 atPath:(id)arg2 to:(struct CGRect)arg3 saveToCache:(BOOL)arg4;
- (void)moveRegionOfInterestWithPath:(id)arg1 fromIndex:(int)arg2 toIndex:(int)arg3 saveToCache:(BOOL)arg4;
- (void)setForceOrderForRegionsOfInterest:(BOOL)arg1 forPath:(id)arg2 saveToCache:(BOOL)arg3;
- (void)removeRegionOfInterestAtIndex:(int)arg1 forAssetAtPath:(id)arg2 saveToCache:(BOOL)arg3;
- (id)prepareInfoForAssetsAtPaths:(id)arg1;
@end

