/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAssetManager.h>

@interface MPAssetManager (MediaManagementProtocol)
- (BOOL)isSupportedMovie:(id)arg1;
- (struct CGSize)resolutionForAsset:(id)arg1;
- (id)attributeForAsset:(id)arg1 forKey:(id)arg2;
- (double)startTimeForAsset:(id)arg1;
- (double)stopTimeForAsset:(id)arg1;
@end

