/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAuthoringController.h>

@interface MPAuthoringController (Manipulation_Internal)
- (void)_reorderImagesInDocument:(id)arg1 withOptions:(id)arg2;
- (void)_addVideoPaths:(id)arg1 toEndOfLayer:(id)arg2 inDocument:(id)arg3 withOptions:(id)arg4;
- (id)_grabAndRemoveTitleEffectFromDocument:(id)arg1 withOptions:(id)arg2;
- (void)_readdTitleEffect:(id)arg1 toDocument:(id)arg2 withOptions:(id)arg3;
- (void)_checkForEmptyLayersInDocument:(id)arg1;
- (int)_numberOfSlidesForOutroInLayer:(id)arg1 withOptions:(id)arg2;
- (int)_countOfEmptyContainersInIntroOfLayer:(id)arg1 withOptions:(id)arg2;
@end

