/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MPDocument, MPWeighter, NSMutableDictionary, NSRecursiveLock;

@interface MPAuthoringController : NSObject
{
    BOOL _isAuthoring;
    MPDocument *_authoredDocument;
    unsigned int _seed;
    NSRecursiveLock *_beatLock;
    NSMutableDictionary *_cachedROIInformation;
    MPWeighter *_weighter;
    MPWeighter *_transitionWeighter;
    NSMutableDictionary *_stats;
    id _delegate;
    int _logLevel;
    double _logTiming;
}

+ (id)sharedController;
- (id)init;
- (void)dealloc;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (unsigned int)authorDocument:(id)arg1 withOptions:(id)arg2;
- (void)upgradeDocument:(id)arg1 withOptions:(id)arg2;
- (id)effectContainersWithPaths:(id)arg1 forDocument:(id)arg2 withOptions:(id)arg3;
- (id)transitionFromOptions:(id)arg1;
- (void)beatAlignLayers:(id)arg1 toAudioPlaylist:(id)arg2 forDocument:(id)arg3 withOptions:(id)arg4;
- (void)scaleDurationsInDocument:(id)arg1 withOptions:(id)arg2;
- (void)reconfigureImagesInDocument:(id)arg1 withOptions:(id)arg2;
- (void)reconfigureTitleEffectInDocument:(id)arg1 withOptions:(id)arg2;
- (void)reconfigureColorSchemeInDocument:(id)arg1 withOptions:(id)arg2;
- (BOOL)prepareDocumentForExport:(id)arg1 withOptions:(id)arg2;
- (void)prepareDocumentForPlayback:(id)arg1 withOptions:(id)arg2;
- (BOOL)canDocumentFitToAudio:(id)arg1 withOptions:(id)arg2 requiredAudioDuration:(double *)arg3;
- (BOOL)canScaleToAudioInDocument:(id)arg1 withOptions:(id)arg2;

@end

