/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAudioPlaylist.h>

@interface MPAudioPlaylist (Internal)
- (void)copyStruct:(id)arg1;
- (void)copySongs:(id)arg1;
- (void)cleanup;
- (id)montage;
- (void)setMontage:(id)arg1;
- (void)setAudioPlaylist:(id)arg1;
- (void)setPlug:(id)arg1;
- (void)setParentObject:(id)arg1;
- (void)setDuration:(double)arg1;
- (void)recreateFromPlaylist:(id)arg1;
- (id)parentDocument;
@end

