/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAudioPlaylist.h>

@interface MPAudioPlaylist (AppleScript)
- (int)countOfSongs;
- (id)objectInSongsAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inSongsAtIndex:(int)arg2;
- (void)removeObjectFromSongsAtIndex:(int)arg1;
- (void)replaceObjectInSongsAtIndex:(int)arg1 withObject:(id)arg2;
@end

