/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPAuthoringController.h>

@interface MPAuthoringController (Manipulation)
- (void)moveSlidesFromIndicies:(id)arg1 toIndex:(int)arg2 inDocument:(id)arg3 withOptions:(id)arg4;
- (void)insertVideoPaths:(id)arg1 atIndex:(int)arg2 inDocument:(id)arg3 withOptions:(id)arg4;
- (void)removeSlidesAtIndicies:(id)arg1 inDocument:(id)arg2 withOptions:(id)arg3;
@end

