/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPAuthoringUtilities : NSObject
{
}

+ (void)cacheOptions:(id)arg1;
+ (void)updateCacheToLayerIndex:(int)arg1;
+ (BOOL)hasCache;
+ (void)clearCache;
+ (BOOL)ignoreClusteringForImages:(id)arg1 withOptions:(id)arg2;
+ (id)urlsFromPaths:(id)arg1;
+ (id)styleFromOptions:(id)arg1;
+ (int)layerIndexFromOptions:(id)arg1;
+ (double)audioDurationFromOptions:(id)arg1;
+ (int)audioScalingModeFromOptions:(id)arg1;
+ (int)croppingModeFromOptions:(id)arg1;
+ (float)kenBurnsLikelihoodFromOptions:(id)arg1;
+ (float)maxKenBurnsZoomFromOptions:(id)arg1;
+ (float)kenBurnsPanFactorFromOptions:(id)arg1;
+ (int)kenBurnsLevelFromOptions:(id)arg1;
+ (BOOL)layerCanSkipScaleCalculationFromOptions:(id)arg1;
+ (BOOL)alignToBeatsFromOptions:(id)arg1;
+ (BOOL)createBeatsFromOptions:(id)arg1;
+ (BOOL)lockTransitionDurationFromOptions:(id)arg1;
+ (double)layerTimeScaleFromOptions:(id)arg1;
+ (double)beatFactorFromOptions:(id)arg1;
+ (BOOL)replaceAudioPlaylistFromOptions:(id)arg1;
+ (struct CGColor *)backgroundColorFromOptions:(id)arg1;
+ (BOOL)matchPhasesWithTransitionFromOptions:(id)arg1;
+ (double)durationPerEffectFromOptions:(id)arg1;
+ (double)layerOffsetFromOptions:(id)arg1;
+ (BOOL)canRepeatPresets:(id)arg1;
+ (double)transitionDurationFromOptions:(id)arg1;
+ (BOOL)useBestAspectRatioFromOptions:(id)arg1;
+ (BOOL)useROIFromOptions:(id)arg1;
+ (BOOL)useTitleEffectFromOptions:(id)arg1;
+ (BOOL)useDefaultAudioFromOptions:(id)arg1;
+ (unsigned int)randomSeedFromOptions:(id)arg1;
+ (float)aspectRatioFromOptions:(id)arg1;
+ (id)effectListFromOptions:(id)arg1;
+ (float)kenBurnsZoomFactorFromOptions:(id)arg1;
+ (BOOL)collectVersionInformationFromOptions:(id)arg1;
+ (BOOL)repeatTransitionsFromOptions:(id)arg1;
+ (id)ignoreTransitionListFromOptions:(id)arg1;
+ (id)transitionListFromOptions:(id)arg1;
+ (id)outroEffectIDFromOptions:(id)arg1;
+ (BOOL)scaleOutroEffectFromOptions:(id)arg1;
+ (id)introEffectIDFromOptions:(id)arg1;
+ (id)titleEffectFromOptions:(id)arg1;
+ (id)idFromPresetID:(id)arg1;
+ (id)presetIDFromPresetID:(id)arg1;
+ (BOOL)shouldComputeFramesFromOptions:(id)arg1;
+ (BOOL)shouldComputeTransitionsFromOptions:(id)arg1;
+ (BOOL)shouldComputeSlideFiltersFromOptions:(id)arg1;
+ (BOOL)shouldComputeLoopTransitionFromOptions:(id)arg1;
+ (float)effectPadding:(id)arg1;
+ (id)loopTransitionIDFromOptions:(id)arg1;
+ (id)exportTransitionIDFromOptions:(id)arg1;
+ (double)exportTransitionDurationFromOptions:(id)arg1;
+ (id)layerDescriptionForLayerWithZIndex:(int)arg1 forStyle:(id)arg2;
+ (BOOL)layerHasImagesFromOptions:(id)arg1;
+ (int)numberOfLayersFromOptions:(id)arg1;
+ (double)minimumTransitionDurationFromOptions:(id)arg1;
+ (double)minimumEffectDurationFromOptions:(id)arg1;
+ (BOOL)useUniformDurations:(id)arg1;
+ (BOOL)padTextOnlyEffects:(id)arg1;
+ (float)movieVolumeFromOptions:(id)arg1;
+ (id)colorSchemeFromOptions:(id)arg1;
+ (int)reorderModeFromOptions:(id)arg1;
+ (BOOL)useROIAspectRatioFromOptions:(id)arg1;
+ (BOOL)fadeOutAudioFromOptions:(id)arg1;
+ (int)numberOfEffectsFromOptions:(id)arg1;
+ (id)absolutePathForPath:(id)arg1 withOptions:(id)arg2;
+ (BOOL)shouldDuckMoviesFromOptions:(id)arg1;
+ (int)presentationOrderFromOptions:(id)arg1;
+ (id)layerTypeFromOptions:(id)arg1;
+ (struct _NSRange)reconfigureRangeFromOptions:(id)arg1;
+ (struct _NSRange)videoPathsRangeFromOptions:(id)arg1;
+ (id)absolutePathAtIndex:(int)arg1 inPaths:(id)arg2 withOptions:(id)arg3;
+ (id)absolutePathsForPaths:(id)arg1 withOptions:(id)arg2;
+ (struct CGRect)rectToFitIn:(struct CGRect)arg1 withAspectRatio:(float)arg2;
+ (struct CGPoint)kbCenterPointFromRect:(struct CGRect)arg1;
+ (double)distanceBetween:(struct CGPoint)arg1 andPoint:(struct CGPoint)arg2;

@end

