/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface MPClusterSlide : NSObject <NSCopying>
{
    NSDate *mCaptureDate;
    NSString *mPath;
    NSString *mAbsolutePath;
    int mReferenceCounter;
    NSMutableDictionary *mUsageCounterPerLayer;
    NSMutableArray *mUsableSlideClusters;
    int mIndex;
}

- (id)init;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)increaseUsageCounterForLayer:(id)arg1;
- (int)usageCounterForLayer:(id)arg1;
- (void)setUsageCounterForLayer:(id)arg1 to:(int)arg2;
- (int)overallUsageCounter;
- (void)resetAllUsageCounters;
- (id)usageCountDescription;
- (id)description;
@property(retain) NSMutableArray *usableSlideClusters; // @synthesize usableSlideClusters=mUsableSlideClusters;
@property(retain) NSMutableDictionary *usageCounterPerLayer; // @synthesize usageCounterPerLayer=mUsageCounterPerLayer;
@property int index; // @synthesize index=mIndex;
@property int referenceCounter; // @synthesize referenceCounter=mReferenceCounter;
@property(copy) NSDate *captureDate; // @synthesize captureDate=mCaptureDate;
@property(copy) NSString *absolutePath; // @synthesize absolutePath=mAbsolutePath;
@property(copy) NSString *path; // @synthesize path=mPath;

@end

