/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MPCluster, MPDocument, NSDate, NSMutableDictionary;

@interface MPClusterController : NSObject
{
    NSMutableDictionary *mSlides;
    NSMutableDictionary *mSlideClusters;
    MPCluster *mAllSlidesCluster;
    float mMinimumRequiredClusterRating;
    MPDocument *mAuthoredDocument;
    NSDate *mOldestSlideTimestamp;
    NSDate *mNewestSlideTimestamp;
}

+ (id)sharedController;
+ (void)releaseSharedController;
- (id)init;
- (void)dealloc;
- (void)flush;
- (void)setAuthoredDocument:(id)arg1;
- (int)addSlideForPath:(id)arg1 withIndex:(int)arg2;
- (void)setLocationForSlide:(id)arg1 usingPath:(id)arg2;
- (void)addKeywords:(id)arg1 forSlide:(id)arg2;
- (id)allSlides;
- (id)slideForPath:(id)arg1;
- (id)allSlidesSortedByUsage;
- (id)nextLeastUsedSlides:(int)arg1 forLayer:(id)arg2 markAsUsed:(BOOL)arg3;
- (id)allSlidesSortedChronologically;
- (id)clusterSlidesSortedChronologically:(id)arg1;
- (id)clusterSlidesSortedByUserDefinedSortOrder:(id)arg1 userDefinedSlideOrder:(id)arg2;
- (void)sortClusterSlidesChronologically:(id *)arg1;
- (id)clustersBasedOnOrderedPaths:(id)arg1;
- (int)lowestAvailableUsageCountForSlides:(id)arg1;
- (void)resetAllUsageCounters;
- (void)flushClusters;
- (id)findBestCluster:(id)arg1;
- (id)findBestChronologicalCluster:(id)arg1 startingWithSlide:(id)arg2;
- (id)findBestClusterBasedOnUserDefinedSlideOrder:(id)arg1 startingWithSlide:(id)arg2;
- (id)findTitleSlides:(int)arg1;
- (void)removeAllSingleSlideClusters;
- (void)updateKeywordClusters;
- (void)updateLocationClusters;
- (void)updateAllSlidesClusterWithSlide:(id)arg1;
- (id)yearClusters;
- (id)monthClusters;
- (id)monthOfYearClusters;
- (id)dayOfYearClusters;
- (id)hourOfYearClusters;
- (id)minuteOfYearClusters;
- (id)keywordClusters;
- (id)locationClusters;
- (id)userProvidedClusters;
- (id)yearClusterForAssetAtPath:(id)arg1;
- (id)monthClusterForAssetAtPath:(id)arg1;
- (id)monthOfYearClusterForAssetAtPath:(id)arg1;
- (id)dayOfYearClusterForAssetAtPath:(id)arg1;
- (id)hourOfYearClusterForAssetAtPath:(id)arg1;
- (id)minuteOfYearClusterForAssetAtPath:(id)arg1;
- (void)addPaths:(id)arg1 toUserDefinedCluster:(id)arg2;
- (id)orderedAndPrioritizedSlideClusters;
- (id)prioritizedSlideClustersDictionary;
- (void)updateClusterRatings;
- (void)updateRatingsForYearClusters;
- (void)updateRatingsForMonthClusters;
- (void)updateRatingsForMonthOfYearClusters;
- (void)updateRatingsForDayOfYearClusters;
- (void)updateRatingsForHourOfYearClusters;
- (void)updateRatingsForMinuteOfYearClusters;
- (void)updateRatingsForKeywordClusters;
- (void)updateRatingsForLocationClusters;
- (void)dumpClustersStatistics;
- (void)dumpSlidesStatistics;

@end

