/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSString;

@interface MPCluster : NSObject
{
    NSMutableArray *mSlides;
    NSMutableSet *mPathsInCluster;
    NSString *mName;
    float mRating;
    NSMutableDictionary *mUsageCounterPerLayer;
}

- (id)init;
- (void)dealloc;
- (void)addSlide:(id)arg1;
- (void)removeAllSlides;
- (int)slideCount;
- (id)allSlides;
- (BOOL)clusterContainsSlideAtPath:(id)arg1;
- (id)allSlidesSortedChronologically;
- (void)setUsageCountForLayer:(id)arg1 to:(float)arg2;
- (float)usageCountForLayer:(id)arg1;
- (void)resetAllUsageCounters;
- (id)usageCountDescription;
- (void)detailedDescription;
- (id)description;
@property(retain) NSMutableDictionary *usageCounterPerLayer; // @synthesize usageCounterPerLayer=mUsageCounterPerLayer;
@property float rating; // @synthesize rating=mRating;
@property(copy) NSString *name; // @synthesize name=mName;
@property(retain) NSMutableArray *items; // @synthesize items=mSlides;

@end

