/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MPDocument;

@interface MPCropController : NSObject
{
    id _delegate;
    BOOL _hasCache;
    MPDocument *_authoredDocument;
}

+ (id)sharedController;
- (id)init;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (void)batchCrop:(id)arg1;
- (void)cropSlidesInDocument:(id)arg1 withOptions:(id)arg2;
- (void)applyCropToSlidesInEffectContainers:(id)arg1 inDocument:(id)arg2 withOptions:(id)arg3;
- (void)applyCropToSlide:(id)arg1 inDocument:(id)arg2 withOptions:(id)arg3;

@end

