/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPDocument.h>

@interface MPDocument (Model)
- (id)layers;
- (void)addLayer:(id)arg1;
- (void)addLayers:(id)arg1;
- (void)insertLayers:(id)arg1 atIndex:(int)arg2;
- (void)removeAllLayers;
- (void)removeLayersAtIndices:(id)arg1;
- (void)moveLayersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (double)duration;
- (double)videoDuration;
- (id)audioPlaylist;
- (void)setAudioPlaylist:(id)arg1;
- (id)mainLayers;
@end

