/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPDocument.h>

@interface MPDocument (Automatic)
- (void)addVideoPath:(id)arg1;
- (void)addVideoPaths:(id)arg1;
- (void)addAudioPath:(id)arg1;
- (void)addAudioPaths:(id)arg1;
- (void)addStacks:(id)arg1;
- (void)removePath:(id)arg1;
- (void)removePaths:(id)arg1;
- (id)stacks;
- (void)setStacks:(id)arg1;
- (id)videoPaths;
- (id)orderedVideoPaths;
- (void)setVideoPaths:(id)arg1;
- (id)audioPaths;
- (void)setAudioPaths:(id)arg1;
- (void)removeAllVideoPaths;
- (void)removeAllAudioPaths;
- (void)removeAllStacks;
@end

