/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPDocument.h>

@interface MPDocument (AppleScript)
- (int)countOfLayers;
- (id)objectInLayersAtIndex:(int)arg1;
- (id)valueInLayersWithName:(id)arg1;
- (void)insertObject:(id)arg1 inLayersAtIndex:(int)arg2;
- (void)removeObjectFromLayersAtIndex:(int)arg1;
- (void)replaceObjectInLayersAtIndex:(int)arg1 withObject:(id)arg2;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)styleID;
- (void)setStyleID:(id)arg1;
@end

