/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPDocument.h>

@interface MPDocument (Private)
- (id)montage;
- (void)dump;
- (id)fullDebugLog;
- (id)documentAttributes;
- (id)titleEffect;
- (id)outroEffect;
- (id)allEffectContainers;
- (id)allEffects;
- (id)allSlides;
- (double)posterTime;
@end

