/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPDocument.h>

#import "MCAssetPathDelegate-Protocol.h"

@interface MPDocument (Internal) <MCAssetPathDelegate>
- (void)upgradeDocument;
- (void)cleanup;
- (void)setMontage:(id)arg1;
- (void)resetDuration;
- (void)recreate;
- (void)reconfigureLoopingMode;
- (void)_setMediaProperties:(id)arg1;
- (id)absolutePathForAssetPath:(id)arg1;
- (id)absolutePathForAssetPath:(id)arg1 andSize:(struct CGSize)arg2;
- (struct CGImage *)retainedCGImageForAssetPath:(id)arg1 andSize:(struct CGSize)arg2 orientation:(char *)arg3;
- (struct __IOSurface *)retainedIOSurfaceForAssetPath:(id)arg1 andSize:(struct CGSize)arg2 orientation:(char *)arg3;
- (id)absoluteVideoPaths;
- (struct CGSize)resolutionForPath:(id)arg1;
- (double)startTimeForPath:(id)arg1;
- (double)stopTimeForPath:(id)arg1;
- (double)durationForPath:(id)arg1;
- (float)volumeForPath:(id)arg1;
- (BOOL)isImageAtPath:(id)arg1;
- (BOOL)isMovieAtPath:(id)arg1;
- (id)regionsOfInterestForPath:(id)arg1;
- (id)creationDateForPath:(id)arg1;
- (id)keywordsForPath:(id)arg1;
- (id)latitudeForPath:(id)arg1;
- (id)longitudeForPath:(id)arg1;
- (id)altitudeForPath:(id)arg1;
- (double)durationPadding;
- (void)setDurationPadding:(double)arg1;
- (void)reconnectAll;
- (id)descriptionForRandomTransitionPresetID:(id)arg1;
- (id)lastRandomTransition;
- (void)setLastRandomTransition:(id)arg1;
- (void)organizeRandomTransitions;
- (id)organizedRandomTransitions;
- (void)setCGBackgroundColor:(struct CGColor *)arg1;
- (void)setAspectRatio:(id)arg1;
- (BOOL)addAnEffectToSlideshowAndCleanUpEffectsUpToTime:(double)arg1;
- (void)setLastSlideUsed:(int)arg1;
- (int)lastSlideUsed;
@end

