/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class MCMontage, MPAudioPlaylist, MPDocumentInternal, NSMutableArray, NSMutableDictionary, NSString;

@interface MPDocument : NSObject <NSCoding>
{
    MCMontage *_montage;
    NSMutableArray *_userProvidedVideoPaths;
    NSMutableArray *_userProvidedAudioPaths;
    NSMutableArray *_userProvidedStacks;
    NSMutableDictionary *_documentAttributes;
    NSMutableDictionary *_fileProperties;
    NSMutableArray *_layers;
    BOOL _preserveMedia;
    MPAudioPlaylist *_audioPlaylist;
    id <MPAssetKeyDelegate> _assetKeyDelegate;
    NSString *_aspectRatio;
    MPDocumentInternal *_internal;
}

+ (id)unarchiveDocumentFromData:(id)arg1 error:(id *)arg2;
+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)writableTypes;
+ (id)readableTypes;
+ (BOOL)isNativeType:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (BOOL)readFromPath:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (void)finialize;
- (void)dealloc;
- (id)displayName;
- (id)currentStyle;
- (unsigned int)applyStyle:(id)arg1;
- (id)documentAttributeForKey:(id)arg1;
- (void)setDocumentAttribute:(id)arg1 forKey:(id)arg2;
- (BOOL)preserveMedia;
- (void)setPreserveMedia:(BOOL)arg1;
- (id)mediaProperties;
- (void)setMediaProperties:(id)arg1;
- (id)propertiesForMediaPath:(id)arg1;
- (void)setProperties:(id)arg1 forMediaPath:(id)arg2;
- (void)removePropertiesForMediaPath:(id)arg1;
- (int)loopingMode;
- (void)setLoopingMode:(int)arg1;
- (double)numberOfLoops;
- (void)setNumberOfLoops:(double)arg1;
- (id)assetKeyDelegate;
- (void)setAssetKeyDelegate:(id)arg1;
- (BOOL)repeatLiveSlideshow;
- (void)setRepeatLiveSlideshow:(BOOL)arg1;
@property(copy) NSString *aspectRatio; // @synthesize aspectRatio=_aspectRatio;

@end

