/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSMutableDictionary, NSString;

@interface MPDocumentInternal : NSObject
{
    double durationPadding;
    NSString *lastRandomTransition;
    NSMutableDictionary *orderedRandomTransitions;
    NSLock *propertiesLock;
    int lastSlideIndexUsed;
    BOOL repeatLiveSlideshow;
}

- (void)dealloc;
@property(nonatomic) BOOL repeatLiveSlideshow; // @synthesize repeatLiveSlideshow;
@property(nonatomic) int lastSlideIndexUsed; // @synthesize lastSlideIndexUsed;
@property(retain, nonatomic) NSLock *propertiesLock; // @synthesize propertiesLock;
@property(retain, nonatomic) NSMutableDictionary *orderedRandomTransitions; // @synthesize orderedRandomTransitions;
@property(retain, nonatomic) NSString *lastRandomTransition; // @synthesize lastRandomTransition;
@property(nonatomic) double durationPadding; // @synthesize durationPadding;

@end

