/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAudioSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCContainerParallelizer, MCPlug, MPAudioPlaylist, MPEffectContainerInternal, MPLayer, MPTransition, NSMutableArray, NSMutableDictionary;

@interface MPEffectContainer : NSObject <NSCoding, NSCopying, MPFilterSupport, MPAudioSupport>
{
    MCPlug *_containerPlug;
    MCContainerParallelizer *_containerParallelizer;
    NSMutableArray *_effects;
    NSMutableArray *_filters;
    NSMutableDictionary *_attributes;
    MPTransition *_transition;
    MPLayer *_parentLayer;
    MPEffectContainerInternal *_internal;
    MPAudioPlaylist *_audioPlaylist;
    BOOL _transitionDisconnected;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)effectContainer;
- (id)init;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)finialize;
- (void)dealloc;
- (id)effects;
- (void)addEffect:(id)arg1;
- (void)addEffects:(id)arg1;
- (void)insertEffects:(id)arg1 atIndex:(int)arg2;
- (void)removeEffectsAtIndices:(id)arg1;
- (void)removeAllEffects;
- (void)moveEffectsFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)transition;
- (void)setTransition:(id)arg1;
- (id)filters;
- (void)addFilter:(id)arg1;
- (void)addFilters:(id)arg1;
- (void)insertFilters:(id)arg1 atIndex:(int)arg2;
- (void)removeFiltersAtIndices:(id)arg1;
- (void)removeAllFilters;
- (void)moveFiltersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (id)audioPlaylist;
- (void)setAudioPlaylist:(id)arg1;
- (int)index;
- (id)parentLayer;
- (double)startTime;
- (double)duration;
- (void)setDuration:(double)arg1;
- (double)beginingTransitionTime;
- (double)introTransitionDuration;
- (double)outroTransitionDuration;
- (double)endTransitionTime;

@end

