/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPEffect.h>

@interface MPEffect (Private)
- (id)plug;
- (id)container;
- (void)createTextsWithDefaultStrings;
- (void)replaceTextsWitStrings:(id)arg1;
- (void)createTextsWithStrings:(id)arg1;
- (void)createSlidesWithPaths:(id)arg1;
- (void)reconfigureSlides;
- (double)fullDuration;
- (void)setFullDuration:(double)arg1;
- (void)dump;
- (id)fullDebugLog;
@end

