/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface MPEffectManager : NSObject
{
    NSMutableDictionary *mEffects;
    NSMutableDictionary *mCategories;
}

+ (void)initialize;
+ (id)sharedManager;
+ (void)releaseSharedManager;
- (void)dealloc;
- (id)versionOfEffectID:(id)arg1;
- (unsigned int)numOfImagesForEffectID:(id)arg1;
- (unsigned int)numOfTextsForEffectID:(id)arg1;
- (id)thumbnailForEffectID:(id)arg1;
- (id)imageResourceForEffectID:(id)arg1 withFileName:(id)arg2;
- (id)categoryIDsForEffectID:(id)arg1;
- (id)effectIDsForCategoryID:(id)arg1;
- (id)localizedEffectNameForEffectID:(id)arg1;
- (id)localizedCategoryNameFromCategoryID:(id)arg1;
- (id)localizedSettingsUITitleForTitleKey:(id)arg1 inEffect:(id)arg2;
- (id)controlForAttribute:(id)arg1 forEffectID:(id)arg2;
- (id)settingsUIControlDescriptionsForEffect:(id)arg1;
- (id)effectsWithNumOfImages:(unsigned int)arg1;
- (id)allEffectIDs;
- (id)allCategoryIDs;
- (float)maxFontSizeInEffectID:(id)arg1 presetID:(id)arg2 atIndex:(int)arg3;
- (id)presetIDsForEffectID:(id)arg1;
- (id)attributesForEffectID:(id)arg1 andPresetID:(id)arg2;
- (id)mediaAspectRatiosForEffectID:(id)arg1 usingPresetID:(id)arg2;
- (float)mediaAspectRatioForEffectID:(id)arg1 usingPresetID:(id)arg2 atIndex:(int)arg3;
- (float)mediaAspectRatioForEffectID:(id)arg1 usingAttributes:(id)arg2 atIndex:(int)arg3 defaultAspectRatio:(float)arg4;
- (id)slideSettingsForEffectID:(id)arg1 usingPresetID:(id)arg2;
- (id)imageInputInfoForEffectID:(id)arg1;
- (BOOL)canChangeFontForTextAtIndex:(int)arg1 inEffect:(id)arg2 withPresetID:(id)arg3;
- (double)defaultPhaseInDurationForEffectID:(id)arg1;
- (double)defaultPhaseOutDurationForEffectID:(id)arg1;
- (double)defaultMainDurationForEffectID:(id)arg1;
- (double)defaultPosterFrameTimeForEffectID:(id)arg1 andPresetID:(id)arg2;
- (double)defaultPosterFrameTimeForEffect:(id)arg1;

@end

