/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPEffectContainerInternal : NSObject
{
    double startTime;
    double duration;
    struct CGColor *backgroundColor;
}

- (void)finalize;
- (void)dealloc;
@property(nonatomic) struct CGColor *backgroundColor; // @synthesize backgroundColor;
@property(nonatomic) double duration; // @synthesize duration;
@property(nonatomic) double startTime; // @synthesize startTime;

@end

