/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPEffectManager.h>

@interface MPEffectManager (Internal)
- (id)showTimeScriptForEffectID:(id)arg1 atSlideIndex:(int)arg2;
- (double)minimumEffectDurationForEffectID:(id)arg1;
- (id)sizeScriptForEffectID:(id)arg1 atIndex:(int)arg2;
- (id)effectPresetsMatchingCriteria:(id)arg1;
- (double)defaultFullDurationForEffectID:(id)arg1;
- (unsigned int)numOfImagesForEffectPresetID:(id)arg1;
- (unsigned int)maxNumOfImagesPerEffectInList:(id)arg1;
- (unsigned int)minNumOfImagesPerEffectInList:(id)arg1;
@end

