/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPEffect.h>

@interface MPEffect (Internal)
- (void)copyStruct:(id)arg1;
- (void)copySlides:(id)arg1;
- (void)copyTexts:(id)arg1;
- (void)copyFilters:(id)arg1;
- (void)copyAnimationPaths:(id)arg1;
- (void)copyAudioPlaylist:(id)arg1;
- (void)cleanup;
- (void)setPlug:(id)arg1;
- (void)setContainer:(id)arg1;
- (void)setParentContainer:(id)arg1;
- (BOOL)needsParallelizer;
- (void)scaleMainDuration;
- (void)recreateWithContainer:(id)arg1 andPlug:(id)arg2;
@end

