/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAnimationSupport-Protocol.h"
#import "MPAudioSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCContainerEffect, MCPlugParallel, MPAudioPlaylist, MPEffectContainer, MPEffectInternal, NSMutableArray, NSMutableDictionary;

@interface MPEffect : NSObject <NSCoding, NSCopying, MPFilterSupport, MPAnimationSupport, MPAudioSupport>
{
    NSMutableArray *_slides;
    NSMutableArray *_texts;
    NSMutableArray *_filters;
    NSMutableDictionary *_attributes;
    NSMutableDictionary *_animationPaths;
    MCContainerEffect *_container;
    MCPlugParallel *_plug;
    MPAudioPlaylist *_audioPlaylist;
    MPEffectContainer *_parentContainer;
    BOOL _replaceSlides;
    MPEffectInternal *_internal;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)effectWithEffectID:(id)arg1;
+ (id)effectWithEffectID:(id)arg1 andPaths:(id)arg2;
+ (id)effectWithEffectID:(id)arg1 andStrings:(id)arg2;
+ (id)effectWithEffectID:(id)arg1 strings:(id)arg2 paths:(id)arg3;
- (id)initWithEffectID:(id)arg1;
- (id)initWithEffectID:(id)arg1 andPaths:(id)arg2;
- (id)initWithEffectID:(id)arg1 andStrings:(id)arg2;
- (id)initWithEffectID:(id)arg1 strings:(id)arg2 paths:(id)arg3;
- (id)init;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)finalize;
- (void)dealloc;
- (id)effectID;
- (void)setEffectID:(id)arg1;
- (id)presetID;
- (void)setPresetID:(id)arg1;
- (id)effectAttributes;
- (id)effectAttributeForKey:(id)arg1;
- (void)setEffectAttribute:(id)arg1 forKey:(id)arg2;
- (float)opacity;
- (void)setOpacity:(float)arg1;
- (struct CGPoint)position;
- (void)setPosition:(struct CGPoint)arg1;
- (float)zPosition;
- (void)setZPosition:(float)arg1;
- (float)rotationAngle;
- (void)setRotationAngle:(float)arg1;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)arg1;
- (float)xRotationAngle;
- (void)setXRotationAngle:(float)arg1;
- (float)yRotationAngle;
- (void)setYRotationAngle:(float)arg1;
- (double)phaseInDuration;
- (void)setPhaseInDuration:(double)arg1;
- (double)phaseOutDuration;
- (void)setPhaseOutDuration:(double)arg1;
- (double)mainDuration;
- (void)setMainDuration:(double)arg1;
- (int)zIndex;
- (id)slides;
- (void)addSlide:(id)arg1;
- (void)addSlides:(id)arg1;
- (void)insertSlides:(id)arg1 atIndex:(int)arg2;
- (void)removeSlidesAtIndices:(id)arg1;
- (void)removeAllSlides;
- (void)replaceSlideAtIndex:(int)arg1 withSlide:(id)arg2;
- (void)replaceSlide:(id)arg1 atIndex:(int)arg2;
- (void)moveSlidesFromIndices:(id)arg1 toIndex:(int)arg2;
- (BOOL)supportsUnlimitedSlides;
- (BOOL)replaceSlides;
- (void)setReplaceSlides:(BOOL)arg1;
- (id)texts;
- (void)addText:(id)arg1;
- (void)addTexts:(id)arg1;
- (void)insertTexts:(id)arg1 atIndex:(int)arg2;
- (void)removeTextsAtIndices:(id)arg1;
- (void)removeAllTexts;
- (void)moveTextsFromIndices:(id)arg1 toIndex:(int)arg2;
- (BOOL)isTextOnly;
- (id)filters;
- (void)addFilter:(id)arg1;
- (void)addFilters:(id)arg1;
- (void)insertFilters:(id)arg1 atIndex:(int)arg2;
- (void)removeFiltersAtIndices:(id)arg1;
- (void)removeAllFilters;
- (void)moveFiltersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)animationPaths;
- (id)animationPathForKey:(id)arg1;
- (void)setAnimationPath:(id)arg1 forKey:(id)arg2;
- (void)removeAnimationPathForKey:(id)arg1;
- (id)audioPlaylist;
- (void)setAudioPlaylist:(id)arg1;
- (int)audioPriority;
- (void)setAudioPriority:(int)arg1;
- (id)parentContainer;
- (int)randomSeed;
- (void)setRandomSeed:(int)arg1;

@end

