/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPEffect.h>

@interface MPEffect (AppleScript)
- (int)countOfSlides;
- (id)objectInSlidesAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inSlidesAtIndex:(int)arg2;
- (void)removeObjectFromSlidesAtIndex:(int)arg1;
- (void)replaceObjectInSlidesAtIndex:(int)arg1 withObject:(id)arg2;
- (int)countOfTexts;
- (id)objectInTextsAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inTextsAtIndex:(int)arg2;
- (void)removeObjectFromTextsAtIndex:(int)arg1;
- (void)replaceObjectInTextsAtIndex:(int)arg1 withObject:(id)arg2;
- (int)countOfFilters;
- (id)objectInFiltersAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inFiltersAtIndex:(int)arg2;
- (void)removeObjectFromFiltersAtIndex:(int)arg1;
- (void)replaceObjectInFiltersAtIndex:(int)arg1 withObject:(id)arg2;
- (float)xPosition;
- (void)setXPosition:(float)arg1;
- (float)yPosition;
- (void)setYPosition:(float)arg1;
- (float)height;
- (void)setHeight:(float)arg1;
- (float)width;
- (void)setWidth:(float)arg1;
- (id)scriptingAnimations;
- (void)setScriptingAnimations:(id)arg1;
@end

