/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPEffectContainer.h>

@interface MPEffectContainer (AppleScript)
- (int)countOfEffects;
- (id)objectInEffectsAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inEffectsAtIndex:(int)arg2;
- (void)removeObjectFromEffectsAtIndex:(int)arg1;
- (void)replaceObjectInEffectsAtIndex:(int)arg1 withObject:(id)arg2;
- (int)countOfFilters;
- (id)objectInFiltersAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inFiltersAtIndex:(int)arg2;
- (void)removeObjectFromFiltersAtIndex:(int)arg1;
- (void)replaceObjectInFiltersAtIndex:(int)arg1 withObject:(id)arg2;
- (id)scriptingTransition;
- (void)setScriptingTransition:(id)arg1;
@end

