/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAnimationSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCFilter, MPFilterInternal, NSMutableDictionary, NSObject<MPFilterSupport>;

@interface MPFilter : NSObject <NSCoding, NSCopying, MPAnimationSupport>
{
    NSMutableDictionary *_attributes;
    NSMutableDictionary *_animationPaths;
    MCFilter *_filter;
    NSObject<MPFilterSupport> *_parent;
    MPFilterInternal *_internal;
}

+ (id)filterWithFilterID:(id)arg1;
- (id)initWithFilterID:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)finalize;
- (void)dealloc;
- (id)filterID;
- (void)setFilterID:(id)arg1;
- (id)presetID;
- (void)setPresetID:(id)arg1;
- (id)filterAttributes;
- (id)filterAttributeForKey:(id)arg1;
- (void)setFilterAttribute:(id)arg1 forKey:(id)arg2;
- (id)animationPaths;
- (id)animationPathForKey:(id)arg1;
- (void)setAnimationPath:(id)arg1 forKey:(id)arg2;
- (void)removeAnimationPathForKey:(id)arg1;
- (int)index;
- (id)parent;

@end

