/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPFilter.h>

@interface MPFilter (Internal)
- (void)copyStruct:(id)arg1;
- (void)copyAnimationPaths:(id)arg1;
- (void)setFilter:(id)arg1;
- (void)setParent:(id)arg1;
- (id)parentDocument;
- (void)recreateWithFilter:(id)arg1;
@end

