/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MPFrameInternal, MPSlide, NSMutableDictionary;

@interface MPFrame : NSObject <NSCoding, NSCopying>
{
    NSMutableDictionary *_attributes;
    MPSlide *_parentSlide;
    MPFrameInternal *_internal;
}

+ (id)frameWithFrameID:(id)arg1;
- (id)initWithFrameID:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)frameID;
- (void)setFrameID:(id)arg1;
- (id)presetID;
- (void)setPresetID:(id)arg1;
- (id)frameAttributes;
- (id)frameAttributeForKey:(id)arg1;
- (void)setFrameAttribute:(id)arg1 forKey:(id)arg2;
- (id)parentSlide;

@end

