/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPKeyframeInternal : NSObject
{
    double time;
    unsigned int offset;
    double preControl;
    double postControl;
}

@property(nonatomic) double postControl; // @synthesize postControl;
@property(nonatomic) double preControl; // @synthesize preControl;
@property(nonatomic) unsigned int offset; // @synthesize offset;
@property(nonatomic) double time; // @synthesize time;

@end

