/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAnimationSupport-Protocol.h"
#import "MPAudioSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCMontage, MCPlugParallel, MPAudioPlaylist, MPDocument, MPLayerInternal, NSMutableArray, NSMutableDictionary;

@interface MPLayer : NSObject <NSCoding, NSCopying, MPFilterSupport, MPAnimationSupport, MPAudioSupport>
{
    MCPlugParallel *_layerPlug;
    NSMutableDictionary *_attributes;
    NSMutableArray *_effectContainers;
    NSMutableArray *_filters;
    NSMutableDictionary *_animationPaths;
    MPAudioPlaylist *_audioPlaylist;
    MCMontage *_montage;
    MPDocument *_parentDocument;
    MPLayerInternal *_internal;
    BOOL _skipTimeCalculations;
}

+ (BOOL)automaticallyNotifiesObserversForKey:(id)arg1;
+ (id)layer;
+ (id)sequentialLayer;
- (id)init;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)finalize;
- (void)dealloc;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)effectContainers;
- (void)addEffectContainer:(id)arg1;
- (void)addEffectContainers:(id)arg1;
- (void)insertEffectContainers:(id)arg1 atIndex:(int)arg2;
- (void)removeEffectContainersAtIndices:(id)arg1;
- (void)removeAllEffectContainers;
- (void)moveEffectContainersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)filters;
- (void)addFilter:(id)arg1;
- (void)addFilters:(id)arg1;
- (void)insertFilters:(id)arg1 atIndex:(int)arg2;
- (void)removeFiltersAtIndices:(id)arg1;
- (void)removeAllFilters;
- (void)moveFiltersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)animationPaths;
- (id)animationPathForKey:(id)arg1;
- (void)setAnimationPath:(id)arg1 forKey:(id)arg2;
- (void)removeAnimationPathForKey:(id)arg1;
- (float)opacity;
- (void)setOpacity:(float)arg1;
- (struct CGPoint)position;
- (void)setPosition:(struct CGPoint)arg1;
- (float)zPosition;
- (void)setZPosition:(float)arg1;
- (float)rotationAngle;
- (void)setRotationAngle:(float)arg1;
- (struct CGSize)size;
- (void)setSize:(struct CGSize)arg1;
- (float)xRotationAngle;
- (void)setXRotationAngle:(float)arg1;
- (float)yRotationAngle;
- (void)setYRotationAngle:(float)arg1;
- (int)zIndex;
- (id)parentDocument;
- (double)timeIn;
- (void)setTimeIn:(double)arg1;
- (double)duration;
- (id)audioPlaylist;
- (void)setAudioPlaylist:(id)arg1;
- (int)audioPriority;
- (void)setAudioPriority:(int)arg1;
- (double)numberOfLoops;
- (void)setNumberOfLoops:(double)arg1;
- (BOOL)isAudioLayer;
- (void)setIsAudioLayer:(BOOL)arg1;

@end

