/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MPLayerInternal : NSObject
{
    int numberOfLoops;
    float opacity;
    struct CGPoint position;
    float zPosition;
    struct CGSize size;
    float rotationAngle;
    float xRotationAngle;
    float yRotationAngle;
    double timeIn;
    double duration;
    NSString *title;
    BOOL isAudioLayer;
    int audioPriority;
    double durationPadding;
    NSString *layerID;
}

- (void)dealloc;
@property(retain, nonatomic) NSString *layerID; // @synthesize layerID;
@property(nonatomic) double durationPadding; // @synthesize durationPadding;
@property(nonatomic) int audioPriority; // @synthesize audioPriority;
@property(nonatomic) BOOL isAudioLayer; // @synthesize isAudioLayer;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) double duration; // @synthesize duration;
@property(nonatomic) double timeIn; // @synthesize timeIn;
@property(nonatomic) float yRotationAngle; // @synthesize yRotationAngle;
@property(nonatomic) float xRotationAngle; // @synthesize xRotationAngle;
@property(nonatomic) float rotationAngle; // @synthesize rotationAngle;
@property(nonatomic) struct CGSize size; // @synthesize size;
@property(nonatomic) float zPosition; // @synthesize zPosition;
@property(nonatomic) struct CGPoint position; // @synthesize position;
@property(nonatomic) float opacity; // @synthesize opacity;
@property(nonatomic) int numberOfLoops; // @synthesize numberOfLoops;

@end

