/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPLayer.h>

@class MCContainerSerializer;

@interface MPLayerSerializer : MPLayer
{
    MCContainerSerializer *_layerSerializer;
}

- (id)description;
- (void)finalize;
- (void)dealloc;
- (void)insertEffectContainers:(id)arg1 atIndex:(int)arg2;
- (void)removeEffectContainersAtIndices:(id)arg1;
- (void)moveEffectContainersFromIndices:(id)arg1 toIndex:(int)arg2;
- (void)setAudioPlaylist:(id)arg1;

@end

