/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPLayer.h>

@interface MPLayer (Internal)
- (void)copyStruct:(id)arg1;
- (void)copyEffectContainers:(id)arg1;
- (void)copyFilters:(id)arg1;
- (void)copyAnimationPaths:(id)arg1;
- (void)copyAudioPlaylist:(id)arg1;
- (void)cleanup;
- (void)setLayerPlug:(id)arg1;
- (void)setParentDocument:(id)arg1;
- (void)setMontage:(id)arg1;
- (void)recreateWithPlug:(id)arg1;
- (BOOL)skipTimeCalculations;
- (void)setSkipTimeCalculations:(BOOL)arg1;
- (void)updateDurationPadding:(double)arg1;
- (void)reconnectTransitionForEffectContainerAtIndex:(int)arg1;
- (void)reconnectAllTransitions;
- (void)resetStartTimes;
- (void)setLayerID:(id)arg1;
- (id)layerID;
@end

