/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MPSlideInternal : NSObject
{
    double startTime;
    double duration;
    double audioFadeInDuration;
    double audioFadeOutDuration;
    double audioDuckInDuration;
    double audioDuckOutDuration;
    double audioDuckLevel;
    float scale;
    float rotation;
    struct CGPoint center;
    float audioVolume;
    NSString *sizingMode;
}

- (void)dealloc;
@property(nonatomic) struct CGPoint center; // @synthesize center;
@property(nonatomic) float rotation; // @synthesize rotation;
@property(nonatomic) float scale; // @synthesize scale;
@property(retain, nonatomic) NSString *sizingMode; // @synthesize sizingMode;
@property(nonatomic) float audioVolume; // @synthesize audioVolume;
@property(nonatomic) double audioDuckLevel; // @synthesize audioDuckLevel;
@property(nonatomic) double audioDuckOutDuration; // @synthesize audioDuckOutDuration;
@property(nonatomic) double audioDuckInDuration; // @synthesize audioDuckInDuration;
@property(nonatomic) double audioFadeOutDuration; // @synthesize audioFadeOutDuration;
@property(nonatomic) double audioFadeInDuration; // @synthesize audioFadeInDuration;
@property(nonatomic) double duration; // @synthesize duration;
@property(nonatomic) double startTime; // @synthesize startTime;

@end

