/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPSlide.h>

@interface MPSlide (Internal)
- (void)copyStruct:(id)arg1;
- (void)copyPath:(id)arg1;
- (void)copyFilters:(id)arg1;
- (void)copyAnimationPaths:(id)arg1;
- (void)cleanup;
- (id)parentDocument;
- (BOOL)determineShowTime:(double *)arg1 showDuration:(double *)arg2;
- (void)setSlide:(id)arg1;
- (void)setParentEffect:(id)arg1;
- (void)recreateWithSlide:(id)arg1;
@end

