/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPSlide.h>

@interface MPSlide (AppleScript)
- (int)countOfFilter;
- (id)objectInFilterAtIndex:(int)arg1;
- (void)insertObject:(id)arg1 inFilterAtIndex:(int)arg2;
- (void)removeObjectFromFilterAtIndex:(int)arg1;
- (void)replaceObjectInFilterAtIndex:(int)arg1 withObject:(id)arg2;
- (id)scriptingAnimations;
- (void)setScriptingAnimations:(id)arg1;
- (id)scriptingFrame;
- (void)setScriptingFrame:(id)arg1;
@end

