/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAnimationSupport-Protocol.h"
#import "MPFilterSupport-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCSlide, MPEffect, MPFrame, MPSlideInternal, NSMutableArray, NSMutableDictionary, NSString;

@interface MPSlide : NSObject <NSCoding, NSCopying, MPFilterSupport, MPAnimationSupport>
{
    MPFrame *_frame;
    NSMutableDictionary *_attributes;
    NSString *_path;
    NSString *_cachedAbsolutePath;
    NSMutableArray *_filters;
    NSMutableDictionary *_animationPaths;
    MCSlide *_slide;
    MPEffect *_parentEffect;
    MPSlideInternal *_internal;
}

+ (id)slide;
+ (id)slideWithPath:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)finalize;
- (void)dealloc;
- (id)frame;
- (void)setFrame:(id)arg1;
- (id)path;
- (void)setPath:(id)arg1;
- (id)absolutePath;
- (void)setAbsolutePath:(id)arg1;
- (id)filters;
- (void)addFilter:(id)arg1;
- (void)addFilters:(id)arg1;
- (void)insertFilters:(id)arg1 atIndex:(int)arg2;
- (void)removeFiltersAtIndices:(id)arg1;
- (void)removeAllFilters;
- (void)moveFiltersFromIndices:(id)arg1 toIndex:(int)arg2;
- (id)animationPaths;
- (id)animationPathForKey:(id)arg1;
- (void)setAnimationPath:(id)arg1 forKey:(id)arg2;
- (void)removeAnimationPathForKey:(id)arg1;
- (double)showTime;
- (double)showDuration;
- (double)showDisplayTime;
- (double)startTime;
- (void)setStartTime:(double)arg1;
- (double)duration;
- (void)setDuration:(double)arg1;
- (float)audioVolume;
- (void)setAudioVolume:(float)arg1;
- (double)audioFadeInDuration;
- (void)setAudioFadeInDuration:(double)arg1;
- (double)audioFadeOutDuration;
- (void)setAudioFadeOutDuration:(double)arg1;
- (double)audioDuckInDuration;
- (void)setAudioDuckInDuration:(double)arg1;
- (double)audioDuckOutDuration;
- (void)setAudioDuckOutDuration:(double)arg1;
- (float)audioDuckLevel;
- (void)setAudioDuckLevel:(float)arg1;
- (id)sizingMode;
- (void)setSizingMode:(id)arg1;
- (struct CGPoint)center;
- (void)setCenter:(struct CGPoint)arg1;
- (float)scale;
- (void)setScale:(float)arg1;
- (float)rotation;
- (void)setRotation:(float)arg1;
- (int)index;
- (float)aspectRatio;
- (id)parentEffect;

@end

