/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCSong, MPAudioPlaylist, MPSongInternal, NSString;

@interface MPSong : NSObject <NSCoding, NSCopying>
{
    NSString *_path;
    MCSong *_song;
    MPAudioPlaylist *_parentPlaylist;
    MPSongInternal *_internal;
}

+ (id)song;
+ (id)songWithURL:(id)arg1;
+ (id)songWithPath:(id)arg1;
- (id)init;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPath:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (id)path;
- (void)setPath:(id)arg1;
- (id)URL;
- (void)setURL:(id)arg1;
- (double)startTime;
- (void)setStartTime:(double)arg1;
- (double)duration;
- (void)setDuration:(double)arg1;
- (double)fadeInDuration;
- (void)setFadeInDuration:(double)arg1;
- (double)fadeOutDuration;
- (void)setFadeOutDuration:(double)arg1;
- (float)audioVolume;
- (void)setAudioVolume:(float)arg1;
- (int)index;
- (id)parentPlaylist;

@end

