/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSRecursiveLock, NSString;

@interface MPSongManager : NSObject
{
    NSMutableDictionary *mSongDescriptions;
    NSMutableDictionary *mSongBeats;
    NSString *mSongCacheFilePath;
    NSRecursiveLock *mSongLock;
    void *mDaFunc;
}

+ (id)sharedManager;
+ (void)releaseSharedManager;
- (id)init;
- (void)dealloc;
- (id)beatsForSongAtPath:(id)arg1 progressCallback:(void *)arg2 context:(void *)arg3;

@end

