/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPStyleManager.h>

@interface MPStyleManager (Internal)
- (BOOL)easeKenBurnsForStyleID:(id)arg1;
- (struct CGSize)defaultSizeForZIndex:(int)arg1 ofStyle:(id)arg2;
- (id)defaultPositionForZIndex:(int)arg1 ofStyle:(id)arg2;
- (float)defaultFilterLikelihoodForZIndex:(int)arg1 ofStyle:(id)arg2;
- (float)defaultAutoKenBurnsLikelihoodForZIndex:(int)arg1 ofStyle:(id)arg2;
- (int)defaultAutoKenBurnsLevelForZIndex:(int)arg1 ofStyle:(id)arg2;
- (float)defaultAutoKenBurnsLikelihoodForEffect:(id)arg1 withPreset:(id)arg2 ofStyle:(id)arg3;
- (int)defaultAutoKenBurnsLevelForEffect:(id)arg1 withPreset:(id)arg2 ofStyle:(id)arg3;
- (BOOL)supportPerSlideCustomizationForZIndex:(int)arg1 ofStyle:(id)arg2;
- (id)effectPresetIDsForStyleID:(id)arg1;
- (id)effectSettingOverwritesForZIndex:(int)arg1 ofStyle:(id)arg2;
- (double)gapLikelihoodForZIndex:(int)arg1 ofStyle:(id)arg2;
- (double)defaultEffectDurationForLayer:(int)arg1 ofStyle:(id)arg2;
- (double)defaultTransitionDurationForLayer:(int)arg1 ofStyle:(id)arg2;
- (double)basePeriodForLayerIndex:(int)arg1 ofStyle:(id)arg2;
- (id)layerIDForLayerIndex:(int)arg1 ofStyle:(id)arg2;
- (id)backgroundColorLayerForStyleID:(id)arg1;
- (struct CGColor *)backgroundCGColorForStyleID:(id)arg1;
@end

