/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPStyleManager.h>

@interface MPStyleManager (Private)
+ (void)loadStyleManagerWithPaths:(id)arg1;
- (int)mediaPresentationOrderForStyleID:(id)arg1;
- (int)automaticKenBurnsModeForStyleID:(id)arg1;
- (id)demoDocumentWithImages:(id)arg1 properties:(id)arg2 count:(int)arg3 options:(id)arg4;
- (double)posterTimeForStyleID:(id)arg1;
@end

