/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MCText, MPEffect, MPTextInternal, NSMutableDictionary;

@interface MPText : NSObject <NSCoding, NSCopying>
{
    NSMutableDictionary *_attributes;
    MCText *_text;
    MPTextInternal *_internal;
    MPEffect *_parentEffect;
}

+ (id)textWithAttributedString:(id)arg1;
- (id)initWithAttributedString:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)attributedString;
- (void)setAttributedString:(id)arg1;
- (id)parentEffect;
- (int)index;

@end

