/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPText.h>

@interface MPText (Internal)
- (void)copyStruct:(id)arg1;
- (void)setText:(id)arg1;
- (void)setParentEffect:(id)arg1;
- (void)recreateWithText:(id)arg1;
- (void)checkForMaxFontSize;
@end

