/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MPTransitionInternal : NSObject
{
    NSString *transitionID;
    NSString *presetID;
    double duration;
    BOOL isRandom;
}

- (void)dealloc;
@property(nonatomic) BOOL isRandom; // @synthesize isRandom;
@property(nonatomic) double duration; // @synthesize duration;
@property(retain, nonatomic) NSString *presetID; // @synthesize presetID;
@property(retain, nonatomic) NSString *transitionID; // @synthesize transitionID;

@end

