/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPTransitionManager.h>

@interface MPTransitionManager (Internal)
- (id)constraintsForTransitionPresetsMatchingList:(id)arg1 andCriteria:(id)arg2;
- (id)randomTransitionPresetFromList:(id)arg1 abidingWithConstraints:(id)arg2;
- (id)transitionPresetsMatchingCriteria:(id)arg1;
- (float)beatStrengthForTransitionID:(id)arg1;
- (double)bestBeatTimeForTransitionID:(id)arg1;
@end

