/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class MPEffectContainer, MPTransitionInternal, NSMutableDictionary;

@interface MPTransition : NSObject <NSCoding, NSCopying>
{
    NSMutableDictionary *_attributes;
    MPEffectContainer *_parentContainer;
    MPTransitionInternal *_internal;
}

+ (id)transitionWithTransitionID:(id)arg1;
- (id)initWithTransitionID:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)transitionID;
- (void)setTransitionID:(id)arg1;
- (id)presetID;
- (void)setPresetID:(id)arg1;
- (double)duration;
- (void)setDuration:(double)arg1;
- (id)transitionAttributes;
- (void)setTransitionAttributes:(id)arg1;
- (id)transitionAttributeForKey:(id)arg1;
- (void)setTransitionAttribute:(id)arg1 forKey:(id)arg2;
- (id)parentContainer;

@end

