/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface MPTransitionManager : NSObject
{
    NSMutableDictionary *mTransitions;
    NSMutableDictionary *mTransitionCategories;
    NSMutableDictionary *mTransitionPresets;
}

+ (id)sharedManager;
+ (void)releaseSharedManager;
- (void)dealloc;
- (id)allTransitionIDs;
- (id)allCategoryIDs;
- (id)versionOfTransitionID:(id)arg1;
- (id)categoryIDsForTransitionID:(id)arg1;
- (id)transitionsForCategoryID:(id)arg1;
- (id)localizedTransitionNameForTransitionID:(id)arg1;
- (id)localizedTransitionNameForTransitionID:(id)arg1 andPresetID:(id)arg2;
- (id)localizedCategoryNameFromCategoryID:(id)arg1;
- (id)attributesForTransitionID:(id)arg1 andPresetID:(id)arg2;
- (id)localizedSettingsUITitleForTitleKey:(id)arg1 inTransition:(id)arg2;
- (id)imageResourceForTransitionID:(id)arg1 withFileName:(id)arg2;
- (id)settingsUIControlDescriptionsForTransition:(id)arg1;
- (id)controlForAttribute:(id)arg1 forTransitionID:(id)arg2;
- (double)defaultDurationForTransitionID:(id)arg1;
- (id)presetsForTransitionID:(id)arg1;

@end

