/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPTransition.h>

@interface MPTransition (Internal)
- (void)copyStruct:(id)arg1;
- (void)copyAttribures:(id)arg1;
- (void)setParentContainer:(id)arg1;
- (void)recreateWithPlug:(id)arg1;
- (BOOL)isRandom;
- (void)setIsRandom:(BOOL)arg1;
- (id)_transitionAttributes;
@end

