/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MPUtilities.h>

@interface MPUtilities (Internal)
+ (id)executeScript:(id)arg1 withHeader:(id)arg2 andAttributes:(id)arg3;
+ (id)stringWithNewUUID;
+ (id)colorFromString:(id)arg1;
+ (id)colorFromCGColor:(struct CGColor *)arg1;
+ (struct CGColor *)CGColorFromColor:(id)arg1;
+ (struct CGColor *)CGColorFromString:(id)arg1;
+ (struct CGColor *)CGColorWithRed:(float)arg1 green:(float)arg2 blue:(float)arg3 alpha:(float)arg4;
+ (struct CGColorSpace *)newColorSpaceForDevice;
+ (void)registerUndoForDocument:(id)arg1 toReceiver:(id)arg2 withSelector:(SEL)arg3 object:(id)arg4;
@end

