/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPUtilities : NSObject
{
}

+ (int)timeOffSetFromString:(id)arg1;
+ (double)transformTime:(double)arg1 forAnimationPath:(id)arg2;
+ (float)computeScalarValueForAnimationPath:(id)arg1 atTime:(double)arg2 defaultsTo:(float)arg3;
+ (struct CGPoint)computePointValueForAnimationPath:(id)arg1 atTime:(double)arg2 defaultsTo:(struct CGPoint)arg3;
+ (id)computeVectorValueForAnimationPath:(id)arg1 atTime:(double)arg2 defaultsTo:(id)arg3;
+ (float)scaledFilterPresetScalarValue:(float)arg1 withKey:(id)arg2 forFilterID:(id)arg3 andPresetID:(id)arg4;
+ (struct CGPoint)scaledFilterPresetPointValue:(struct CGPoint)arg1 withKey:(id)arg2 forFilterID:(id)arg3 andPresetID:(id)arg4;
+ (CDStruct_d27e73f0)scaledFilterPresetVectorValue:(CDStruct_d27e73f0)arg1 withKey:(id)arg2 forFilterID:(id)arg3 andPresetID:(id)arg4;
+ (id)defaultAttributesForMPFilter:(id)arg1;
+ (id)defaultAttributesForMPTransition:(id)arg1;
+ (id)attributesFormMPFilter:(id)arg1 atTime:(double)arg2;
+ (id)attributesFromAnimationPathsInFilter:(id)arg1 atTime:(double)arg2;
+ (id)animationsPathsFromFilterID:(id)arg1 andPresetID:(id)arg2;
+ (void)syncAnimationPaths:(id)arg1;
+ (id)effectContainersForTime:(double)arg1 inDocument:(id)arg2;
+ (id)effectForMCContainerEffect:(id)arg1 inDocument:(id)arg2;
+ (id)slideForPath:(id)arg1 inDocument:(id)arg2;
+ (id)effectContainerContainingPath:(id)arg1 inDocument:(id)arg2;
+ (id)textForElementID:(id)arg1 withMCContainerEffect:(id)arg2 inDocument:(id)arg3;
+ (id)slideForElementID:(id)arg1 withMCContainerEffect:(id)arg2 inDocument:(id)arg3;
+ (id)idOfCombinedID:(id)arg1;
+ (id)presetIDOfCombinedID:(id)arg1;

@end

