/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MPVector : NSObject
{
    CDStruct_d27e73f0 _vector;
}

+ (id)vectorFromString:(id)arg1;
+ (id)vectorWithValues:(id)arg1;
+ (id)vectorFromColor:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (float)valueAtIndex:(int)arg1;
- (int)count;
- (id)string;
- (id)CIColorString;
- (id)color;
- (id)values;
- (void)setValues:(id)arg1;
- (BOOL)isEqualTo:(id)arg1;

@end

