/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableIndexSet;

@interface MPWeighter : NSObject
{
    int _totalWeight;
    NSMutableArray *_weights;
    NSMutableArray *_items;
    NSMutableArray *_constraints;
    NSMutableArray *_usageCount;
    NSMutableIndexSet *_ignoreIndices;
    BOOL _evenlyPickByID;
}

- (id)init;
- (void)dealloc;
- (void)addItem:(id)arg1 withWeight:(int)arg2 andContraints:(id)arg3;
- (int)getRandomIndexMeetingContraints:(id)arg1;
- (id)getRandomItemMeetingNumberOfFaceLandscapes:(int)arg1 facePortraits:(int)arg2 imageLandscapes:(int)arg3 imagePortraits:(int)arg4 movies:(int)arg5 fitsInExtraWide:(int)arg6;
- (int)getRandomIndexInSubset:(id)arg1;
- (int)getRandomIndex;
- (BOOL)itemAtIndex:(int)arg1 meetsContraints:(id)arg2;
- (void)increaseUsageCountOfObjectAtIndex:(int)arg1;
- (void)setEvenlyPickByID:(BOOL)arg1;
- (id)indicesEqualingConstraints:(id)arg1;
- (id)leastUsedItemMeetingContraints:(id)arg1;
- (id)imageCounts;
- (id)ignoredIndices;
- (void)ignoreIndices:(id)arg1;
- (id)allItems;
- (id)allConstraints;
- (id)allUsageCounts;
- (int)count;
- (void)clearAllItems;

@end

