/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MRCroppingSprite : NSObject
{
}

+ (void)renderDumbImage:(const CDStruct_911c9307 *)arg1 atPosition:(struct CGPoint)arg2 andSize:(struct CGSize)arg3;
+ (void)renderImage:(const CDStruct_911c9307 *)arg1 atPosition:(struct CGPoint)arg2 andSize:(struct CGSize)arg3;
+ (void)renderImage:(const CDStruct_911c9307 *)arg1 withMask:(const CDStruct_911c9307 *)arg2 atPosition:(struct CGPoint)arg3 andSize:(struct CGSize)arg4;
+ (void)renderImage:(const CDStruct_911c9307 *)arg1 atPosition:(struct CGPoint)arg2 andSize:(struct CGSize)arg3 withReferenceAspectRatio:(float)arg4 andJustifications:(struct CGPoint)arg5;

@end

