/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MCSlide, NSOperation, NSRecursiveLock, NSString;

@interface MRImageProvider : NSObject
{
    MCSlide *mSlide;
    NSString *mPath;
    CDStruct_911c9307 mImage;
    BOOL mPerformKenBurns;
    BOOL mNeedsBorder;
    unsigned int mBorderColor;
    struct CGSize mTargetSize;
    NSRecursiveLock *mLock;
    NSOperation *mPreloadOperation;
}

+ (void)initialize;
+ (void)waitUntilPreloadingIsFinished;
+ (void)abortPreloading:(BOOL)arg1;
+ (void)suspendPreloading;
+ (void)resumePreloading;
+ (void)insertCallback:(SEL)arg1 forTarget:(id)arg2 withObject:(id)arg3;
- (id)init;
- (id)initWithSlide:(id)arg1;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (void)loadToRAM;
- (void)loadToVRAM;
- (void)loadToVRAMThreaded:(id)arg1;
- (const CDStruct_911c9307 *)imageAtTime:(double)arg1 inDuration:(double)arg2;
@property(readonly) float aspectRatio;
@property(readonly) unsigned int imageWidth;
@property(readonly) unsigned int imageHeight;
- (void)preloadInContext:(id)arg1;
- (void)unload;
@property unsigned int borderColor; // @synthesize borderColor=mBorderColor;
@property BOOL needsBorder; // @synthesize needsBorder=mNeedsBorder;
@property struct CGSize targetSize; // @synthesize targetSize=mTargetSize;

@end

