/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MRImageProvider.h>

@interface MRImageProvider (KenBurns)
+ (void)applyKenBurnsFromSlide:(id)arg1 forSize:(struct CGSize)arg2 atTime:(double)arg3 withTargetSize:(struct CGSize)arg4 translation:(struct CGPoint *)arg5 scale:(float *)arg6 rotation:(float *)arg7;
+ (struct CGRect)sourceRectForSlide:(id)arg1 slideSize:(struct CGSize)arg2 targetSize:(struct CGSize)arg3;
@end

