/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MRLayer.h>

@class MCContainerEffect, NSMutableArray;

@interface MRLayerEffect : MRLayer
{
    MCContainerEffect *mContainer;
    NSMutableArray *mImageProviders;
    BOOL mNeedsToPreloadImageProviders;
    BOOL mIsPreloaded;
    BOOL mNeedsToResumeRenderer;
    BOOL mIsPartOfWarmingUp;
}

+ (id)effectLayerWithPlug:(id)arg1 andParameters:(id)arg2 inSuperlayer:(id)arg3;
- (id)initWithPlug:(id)arg1 andParameters:(id)arg2 inSuperlayer:(id)arg3;
- (void)cleanup;
- (void)updateSize;
- (void)renderAtTime:(double)arg1;
- (const CDStruct_911c9307 *)renderedImageAtTime:(double)arg1;
- (id)patchworkAtBeginning;
- (id)patchworkAtEnd;
- (void)preactivate;
- (void)activate;
- (void)depreactivate;
- (void)contextChanged;
- (double)stillDurationFromTime:(double)arg1;
- (BOOL)changedBetweenTime:(double)arg1 andTime:(double)arg2 remainingStillDuration:(double)arg3;
- (void)_fillInTiming:(CDStruct_afa449f9 *)arg1 forTime:(double)arg2;
- (void)_setTargetSizeOfImageProviders;
- (void)_preloadCompleted;
@property BOOL isPartOfWarmingUp; // @synthesize isPartOfWarmingUp=mIsPartOfWarmingUp;
@property BOOL needsToResumeRenderer; // @synthesize needsToResumeRenderer=mNeedsToResumeRenderer;
@property(readonly) BOOL isPreloaded; // @synthesize isPreloaded=mIsPreloaded;

@end

