/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MRLayer.h>

@class MCContainerSerializer, NSArray, NSMutableArray;

@interface MRLayerSerializer : MRLayer
{
    MCContainerSerializer *mContainer;
    NSMutableArray *mSublayers;
    id <NSObject><MRTransition> mCurrentTransition;
    MRLayer *mCurrentTransitionSourceSublayer;
    double mLastCleanUpTime;
    BOOL mSerializerIsComplete;
}

- (id)initWithPlug:(id)arg1 andParameters:(id)arg2 inSuperlayer:(id)arg3;
- (void)cleanup;
- (void)updateSize;
- (void)renderAtTime:(double)arg1;
- (void)_cleanupAndCheckIfNeedsAdditionalEffectsAtTime:(double)arg1 forInterval:(double)arg2;
- (void)contextChanged;
- (double)stillDurationFromTime:(double)arg1;
- (BOOL)changedBetweenTime:(double)arg1 andTime:(double)arg2 remainingStillDuration:(double)arg3;
- (void)hackCheckIfNeedsAdditionalEffectsAtTime:(double)arg1;
- (void)_buildSublayers;
- (BOOL)_applyGLTransformationForTransitionID:(id)arg1 transitionAttributes:(id)arg2 atTime:(double)arg3 isTargetSublayer:(BOOL)arg4 currentColor:(float [4])arg5;
- (BOOL)isSimpleTransitionWithTransitionID:(id)arg1;
- (int)subtypeForSimpleTransitionWithTransitionID:(id)arg1;
@property(readonly) NSArray *sublayers; // @synthesize sublayers=mSublayers;

@end

