/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MCPlug, MCPlugParallel, MCPlugSerial, MRRenderer, NSDictionary;

@interface MRLayer : NSObject
{
    MRLayer *mSuperlayer;
    MCPlug *mPlug;
    MCPlugSerial *mPlugAsSerial;
    MCPlugParallel *mPlugAsParallel;
    BOOL mIsPreactivated;
    BOOL mIsActivated;
    double mTimeIn;
    struct CGSize mSize;
    MRRenderer *mRenderer;
    NSDictionary *mParameters;
}

- (id)initWithPlug:(id)arg1 andParameters:(id)arg2 inSuperlayer:(id)arg3;
- (void)dealloc;
- (void)cleanup;
- (void)updateSize;
- (id)sublayerWithPlug:(id)arg1;
- (void)renderAtTime:(double)arg1;
- (const CDStruct_911c9307 *)renderedImageAtTime:(double)arg1;
- (id)patchworkAtBeginning;
- (id)patchworkAtEnd;
- (void)preactivate;
- (void)activate;
- (void)deactivate;
- (void)depreactivate;
- (void)contextChanged;
- (double)stillDurationFromTime:(double)arg1;
- (BOOL)changedBetweenTime:(double)arg1 andTime:(double)arg2 remainingStillDuration:(double)arg3;
@property(readonly) struct CGSize size; // @synthesize size=mSize;
@property double timeIn; // @synthesize timeIn=mTimeIn;
@property(readonly) BOOL isActivated; // @synthesize isActivated=mIsActivated;
@property(readonly) BOOL isPreactivated; // @synthesize isPreactivated=mIsPreactivated;
@property(readonly) MCPlugSerial *plugAsSerial; // @synthesize plugAsSerial=mPlugAsSerial;
@property(readonly) MCPlugParallel *plugAsParallel; // @synthesize plugAsParallel=mPlugAsParallel;
@property(readonly) MCPlug *plug; // @synthesize plug=mPlug;
@property(readonly) MRLayer *superlayer; // @synthesize superlayer=mSuperlayer;

@end

