/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MRLayer.h>

@class MCContainerParallelizer, NSArray, NSMutableArray;

@interface MRLayerParallelizer : MRLayer
{
    MCContainerParallelizer *mContainer;
    NSMutableArray *mSublayers;
}

- (id)initWithPlug:(id)arg1 andParameters:(id)arg2 inSuperlayer:(id)arg3;
- (void)cleanup;
- (void)updateSize;
- (void)renderAtTime:(double)arg1;
- (void)contextChanged;
- (double)stillDurationFromTime:(double)arg1;
- (BOOL)changedBetweenTime:(double)arg1 andTime:(double)arg2 remainingStillDuration:(double)arg3;
- (void)hackCheckIfNeedsAdditionalEffectsAtTime:(double)arg1;
- (void)_buildSublayers;
@property(readonly) NSArray *sublayers; // @synthesize sublayers=mSublayers;

@end

