/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class EAGLContext, MPDocument, MRRenderer, NSLock;

@interface MRMarimbaViewLight : UIView
{
    EAGLContext *mContext;
    int mWidth;
    int mHeight;
    unsigned int mViewRenderbuffer;
    unsigned int mViewFramebuffer;
    MRRenderer *mRenderer;
    id mDelegate;
    MPDocument *mDocument;
    BOOL mWasPlayingBeforeRotation;
    NSLock *mUpdateDocumentLock;
    double mOldDuration;
    int mNextOrientation;
    NSLock *mRotationLock;
    NSLock *mIsUpdatingDocumentForRotationLock;
    unsigned int mRotationLevel;
    BOOL mIsUpdatingDocumentForRotation;
}

+ (Class)layerClass;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)warmup;
- (void)warmupAndWhenDoneCallSelector:(SEL)arg1 withTarget:(id)arg2 andObject:(id)arg3;
- (void)play;
- (void)pause;
- (void)pauseWhenStill;
- (void)cleanup;
@property(retain, nonatomic) MPDocument *document; // @synthesize document=mDocument;
@property double time;
- (void)layoutSubviews;
- (BOOL)updateFramebuffer;
- (void)destroyFramebuffer;
- (void)dealloc;
- (void)setOrientation:(int)arg1;
- (void)_fadeToBlack:(double)arg1;
- (void)_fadeFromBlack:(double)arg1;
- (void)willRotateToOrientation:(int)arg1 withFade:(BOOL)arg2;
- (void)updateDocumentForRotation:(id)arg1;
- (void)didRotateToOrientation:(int)arg1 withFade:(BOOL)arg2;
- (void)reset;
@property(retain) id delegate; // @synthesize delegate=mDelegate;
@property(readonly) MRRenderer *renderer; // @synthesize renderer=mRenderer;
@property(retain, nonatomic) EAGLContext *context; // @synthesize context=mContext;

@end

