/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iLifeSlideshow/MRLayerEffect.h>

@class NSArray;

@interface MROrigami : MRLayerEffect
{
    NSArray *mPatchworkAtBeginning;
    NSArray *mPatchworkAtEnd;
    float mPixelUnit;
}

+ (void)initialize;
- (void)cleanup;
- (void)_setTargetSizeOfImageProviders;
- (void)renderAtTime:(double)arg1;
- (void)renderFallAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderStillAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderFlipLeftAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderFlipDownAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderFoldLeftAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderFoldDownAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)render1To3DownAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)render1To3LeftAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderFold4LeftAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderOrigami3AtTime:(CDStruct_afa449f9)arg1;
- (void)renderFlipVerticalAtTime:(double)arg1 fromRect:(struct CGRect)arg2 toRect:(struct CGRect)arg3 withLayout:(id)arg4;
- (void)renderFlipDiagonalAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (void)renderUnfoldingFlowerAtTiming:(CDStruct_afa449f9)arg1 inRect:(struct CGRect)arg2 withAttributes:(id)arg3;
- (id)patchworkAtBeginning;
- (id)patchworkAtEnd;
- (void)sendSlidesToGART:(id)arg1;
- (void)unloadSlides:(id)arg1;
- (double)stillDurationFromTime:(double)arg1;
- (BOOL)changedBetweenTime:(double)arg1 andTime:(double)arg2 remainingStillDuration:(double)arg3;

@end

