/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class EAGLContext, MCMontage, MRLayerParallelizer, NSConditionLock, NSDictionary, NSLock, NSThread;

@interface MRRenderer : NSObject
{
    MCMontage *mMontage;
    MRLayerParallelizer *mTopMRLayer;
    NSLock *mRenderLock;
    NSConditionLock *mWarmUpLock;
    struct CGSize mSize;
    int mOrientation;
    BOOL mNeedsToUpdateSize;
    BOOL mIsPlaying;
    id mDisplayLink;
    NSDictionary *mParameters;
    EAGLContext *mContext;
    EAGLContext *mPreloadContext;
    unsigned int mFramebuffer;
    unsigned int mRenderbuffer;
    BOOL mFramebufferIsSetup;
    NSThread *mRenderThread;
    double mTimeOffset;
    double mLastRenderedTime;
    float mFadeAlpha;
    BOOL mShowFPS;
    BOOL mPauseWhenStill;
    BOOL mIsWarmingUp;
    BOOL mWasForcedPaused;
    id <MRLiveSlideshowDelegate> mLiveSlideshowDelegate;
}

- (id)init;
- (void)dealloc;
- (void)cleanup;
- (void)setContext:(id)arg1 frameBuffer:(unsigned int)arg2 renderBuffer:(unsigned int)arg3;
@property(retain, nonatomic) MCMontage *montage; // @synthesize montage=mMontage;
@property(nonatomic) struct CGSize size; // @synthesize size=mSize;
@property(nonatomic) int orientation; // @synthesize orientation=mOrientation;
- (void)render;
- (void)warmup;
- (void)warmupAndWhenDoneCallSelector:(SEL)arg1 withTarget:(id)arg2 andObject:(id)arg3;
- (void)_warmupWithCallback:(id)arg1;
- (void)pause;
- (void)pauseWhenStill;
- (void)resume;
- (void)stepForward;
- (void)stepBackward;
@property double time;
- (void)setForcedPaused;
- (void)_startRenderThread;
- (void)_exitRenderThread;
- (void)_startRenderTimer;
- (void)_stopRenderTimer;
- (void)_render;
- (void)_render:(id)arg1;
- (void)_postPlaybackOverNotification;
- (void)_displayFPS;
- (void)_warmup;
- (void)_armWarmingUp;
- (void)_warmingUpCompleted;
- (void)_pause:(BOOL)arg1;
- (void)_resume;
- (void)hackCheckIfNeedsAdditionalEffectsAtTime:(double)arg1;
@property id <MRLiveSlideshowDelegate> liveSlideshowDelegate; // @synthesize liveSlideshowDelegate=mLiveSlideshowDelegate;
@property float fadeAlpha; // @synthesize fadeAlpha=mFadeAlpha;
@property BOOL showFPS; // @synthesize showFPS=mShowFPS;
@property(readonly) BOOL isWarmingUp; // @synthesize isWarmingUp=mIsWarmingUp;
@property(readonly) BOOL isPlaying; // @synthesize isPlaying=mIsPlaying;
@property(readonly) EAGLContext *preloadContext; // @synthesize preloadContext=mPreloadContext;
@property(readonly) EAGLContext *context; // @synthesize context=mContext;

@end

