/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (MRMarimbaViewPlayback)
- (double)relativeTime;
- (double)relativeTimeForBackgroundAudio;
- (double)relativeTimeForLayer:(id)arg1;
- (id)displayedEffectContainers;
- (void)moveToEffectContainer:(id)arg1 withStartOffset:(double)arg2 toStopOffset:(double)arg3 blocking:(BOOL)arg4;
- (void)moveToNextEffectContainer;
- (void)moveToPreviousEffectContainer;
- (void)moveToTitleSlide;
- (id)_currentEffectContainer;
- (id)_firstEffectContainer;
- (id)_effectContainerForTime:(double)arg1;
- (int)_mainLayerIndex;
- (void)watcherThread:(id)arg1;
@end

