/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class AXNotificationHandler, AXTimer, NSArray, NSDictionary;

@interface AXVisualAlertManager : NSObject
{
    unsigned int _alertTypes;
    id <AXCameraTorchManager> _cameraTorchManager;
    AXTimer *_timer;
    AXTimer *_torchForceShutdownTimer;
    NSDictionary *_patterns;
    NSDictionary *_activePattern;
    unsigned int _activePatternCursor;
    BOOL _shouldRepeatPattern;
    NSDictionary *_patternToUseForVisualAlertAfterCaptureSessionStopsRunning;
    NSArray *_notificationHandlers;
    AXNotificationHandler *_deviceLockStateChangedNotificationHandler;
    BOOL _torchDeviceOpen;
    BOOL _torchDeviceOn;
    BOOL _isDeviceLocked;
    BOOL _captureSessionRunning;
    BOOL _conferenceCallRinging;
    BOOL _skipAutomaticStopOnUserInteraction;
}

+ (id)sharedVisualAlertManager;
+ (void)initialize;
@property(nonatomic, getter=_isTorchDeviceOn, setter=_setTorchDeviceOn:) BOOL _torchDeviceOn; // @synthesize _torchDeviceOn;
@property(nonatomic, getter=_isTorchDeviceOpen, setter=_setTorchDeviceOpen:) BOOL _torchDeviceOpen; // @synthesize _torchDeviceOpen;
@property(retain, nonatomic, setter=_setPatternToUseForVisualAlertAfterCaptureSessionStopsRunning:) NSDictionary *_patternToUseForVisualAlertAfterCaptureSessionStopsRunning; // @synthesize _patternToUseForVisualAlertAfterCaptureSessionStopsRunning;
@property(retain, nonatomic, setter=_setActivePattern:) NSDictionary *_activePattern; // @synthesize _activePattern;
- (BOOL)_axShouldHandleVisualAlertsForConferenceCallsInConferenceFramework;
- (BOOL)_axHasConferenceCameraTorchManager;
- (id)_normalizedStrobePatternForOriginalPattern:(id)arg1;
- (void)_insertCustomLogicForSystemWideServer;
- (void)_handleCaptureSessionDidStopRunning;
- (void)_handleCaptureSessionDidStartRunning;
- (void)_handleDeviceWasUnlocked;
- (void)_handleDeviceWasLocked;
- (void)_handleVolumeChanged;
- (void)_handleLockButtonPressed;
- (void)_handleFaceTimeCallRinging;
- (void)_handleSecondaryVisualAlertManagerDidStart;
- (void)_handleVisualAlertForIncomingMessage;
- (void)_handleVisualAlertForExternalApplication;
- (void)_handleVisualAlertForRegularNotification;
- (void)_handleEndVisualAlertForAlarm;
- (void)_handleBeginVisualAlertForAlarmWithSound:(BOOL)arg1;
- (void)_handleEndVisualAlertForIncomingConferenceCall;
- (void)_handleBeginVisualAlertForIncomingConferenceCall;
- (void)_handleEndVisualAlertForIncomingCall;
- (void)_handleBeginVisualAlertForIncomingCall;
- (void)_processNextVisualAlertComponent;
- (void)_endVisualAlert;
- (void)_beginVisualAlertWithPattern:(id)arg1 repeat:(BOOL)arg2 skipAutomaticStopOnUserInteraction:(BOOL)arg3;
- (void)_beginVisualAlertWithPattern:(id)arg1 repeat:(BOOL)arg2;
- (void)stop;
- (void)startForAlertTypes:(unsigned int)arg1 cameraTorchManager:(id)arg2;
- (void)_stop;
- (void)_startForAlertTypes:(unsigned int)arg1 cameraTorchManager:(id)arg2;
- (id)description;
@property(readonly, nonatomic) NSDictionary *_patterns;
- (void)dealloc;
- (id)init;

@end

