/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ChartLabelInfo : NSObject
{
    NSString *_string;
    struct CGSize _size;
    float _position;
    BOOL _immutable;
}

+ (id)ChartLabelFont;
+ (id)labelInfoWithString:(id)arg1;
+ (id)labelInfoForYAxis;
+ (id)labelInfoWithUnsignedInteger:(unsigned int)arg1;
+ (BOOL)use24hrTime;
+ (struct __CFString *)_CFDateFormatterPropertyForMonthLabelLength:(int)arg1;
+ (id)monthLabelInfoArrayForLabelLength:(int)arg1;
+ (void)resetLocale;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
@property(nonatomic) float position; // @synthesize position=_position;
- (void)setImmutable:(BOOL)arg1;
- (void)setStringToMonthAndDayWithAbsoluteTime:(double)arg1 timeZone:(struct __CFTimeZone *)arg2;
- (void)setStringToYearWithAbsoluteTime:(double)arg1 timeZone:(struct __CFTimeZone *)arg2;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
- (void)retainStringAndSizeFromLabelInfo:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)dealloc;
@property(readonly, nonatomic) BOOL immutable; // @synthesize immutable=_immutable;

@end

