/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSOperationQueue, NSThread;

@interface GraphRenderer : NSObject
{
    NSThread *_thread;
    NSOperationQueue *_queue;
}

+ (id)sharedInstance;
- (void)dealloc;
- (void)threadMain;
- (void)cancelAllOperations;
- (void)performRenderOperation:(id)arg1;

@end

