/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class NSMutableData, NSString, NSURL, NSURLConnection;

@interface NetPreferences : NSObject <NSURLConnectionDelegate>
{
    NSString *_buildVersion;
    NSString *_productVersion;
    NSString *_UUID;
    NSURL *_serviceURL;
    NSURL *_serviceURLGT;
    NSURLConnection *_gtButtonLogoConnection;
    NSMutableData *_gtButtonLogoData;
    NSURLConnection *_gtBacksideLogoConnection;
    NSMutableData *_gtBacksideLogoData;
    BOOL _serviceDebugging;
    BOOL _isNetworkReachable;
}

+ (id)sharedPreferences;
- (id)init;
- (void)setupLogging;
@property(nonatomic, getter=isNetworkReachable) BOOL networkReachable;
- (id)_stocksUserAgent;
- (id)_stocksCountryCode;
- (id)_stocksAcceptLanguage;
- (void)addStocksHeadersToPostRequest:(id)arg1;
- (id)financeRequestAttributes;
- (id)UUID;
- (BOOL)multipleDataSourcesAllowedForGT;
- (id)_urlStringWithHost:(id)arg1;
- (id)serviceURL;
- (id)serviceURLGT;
- (id)newsServiceURLForStock:(id)arg1;
- (id)fullQuoteURLOverrideForStock:(id)arg1;
- (id)backsideLogoURL;
- (id)_cacheDirectoryPath;
- (id)logoButtonImage;
- (id)logoBacksideImage;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (BOOL)serviceDebugging;
- (id)serviceDebuggingPath;

@end

