/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Stocks/XMLHTTPRequest.h>

@class Stock, StockNewsItemCollection;

@interface NewsUpdater : XMLHTTPRequest
{
    id <NewsUpdaterDelegate> _delegate;
    BOOL _firstLoad;
    double _lastResponseTimestamp;
    StockNewsItemCollection *_lastNewsItemCollection;
    Stock *_stock;
}

+ (id)sharedNewsUpdater;
+ (id)_newsItemCollectionCache;
- (id)init;
- (BOOL)shouldReloadOnResume;
- (void)clearNewsCacheOnDisk;
- (void)loadNewsCacheFromDiskForSymbol:(id)arg1;
- (BOOL)fetchNewsForStock:(id)arg1;
- (void)saveLastResponse;
- (int)parseData:(id)arg1;
- (void)failWithError:(id)arg1;
- (void)didParseData;
- (void)resetLocale;
@property(nonatomic) id <NewsUpdaterDelegate> delegate; // @synthesize delegate=_delegate;

@end

