/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Stocks/XMLHTTPRequest.h>

@class NSArray, NSError;

@interface StockUpdater : XMLHTTPRequest
{
    NSArray *_requestStocks;
    int _responseListCount;
    NSError *_lastError;
    BOOL _ignoreNewRequests;
    BOOL _isComprehensive;
    BOOL _useAlternateDataSource;
}

+ (void)resetUpdaters;
+ (void)_createUpdatersIfNeeded;
+ (id)_listUpdaterAlternate:(BOOL)arg1;
+ (id)_comprehensiveUpdaterAlternate:(BOOL)arg1;
+ (BOOL)isLoading;
+ (BOOL)hadError;
+ (void)failWithError:(id)arg1;
+ (void)cancel;
+ (void)updateAllStocksComprehensive;
+ (void)updateStockComprehensive:(id)arg1;
+ (void)updateAllStocksBasic;
- (void)_setLastError:(id)arg1;
- (id)init;
- (void)dealloc;
- (void)_updateWithPostBody:(id)arg1;
- (id)_symbolTagsForRequestStocks;
- (void)_updateWithPartsTag:(id)arg1 forStocks:(id)arg2;
- (int)parseData:(id)arg1;
- (BOOL)hadError;
- (void)didParseData;
- (void)failWithError:(id)arg1;
@property(nonatomic) BOOL useAlternateDataSource; // @synthesize useAlternateDataSource=_useAlternateDataSource;
@property(nonatomic) BOOL isComprehensive; // @synthesize isComprehensive=_isComprehensive;
@property(retain, nonatomic) NSArray *requestStocks; // @synthesize requestStocks=_requestStocks;

@end

