/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "GraphRenderOperationDelegate-Protocol.h"

@class GraphRenderOperation, LineGraphView, NSArray, NSMutableArray, StockChartData, UIView<StockGraphViewContainer>;

@interface StockGraphView : UIView <GraphRenderOperationDelegate>
{
    UIView<StockGraphViewContainer> *_chartView;
    StockChartData *_chartData;
    int _valueIndex;
    int _valueCount;
    struct CGPoint *_points;
    struct CGPoint *_values;
    NSMutableArray *_linePointCounts;
    NSArray *_dottedLinePositions;
    unsigned int _dataSize;
    unsigned int _dataCount;
    CDStruct_cf61fa5f *_volumeBars;
    unsigned int _volumeSize;
    unsigned int _volumeCount;
    float _volumeBarWidth;
    unsigned long long _maxVolume;
    float _lineWidth;
    LineGraphView *_lineView;
    UIView *_volumeView;
    GraphRenderOperation *_renderOperation;
    BOOL _isRendered;
    BOOL _detailedMode;
    BOOL _showingVolume;
    BOOL _volumeCollapsed;
}

+ (id)SelectedLineColor;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)_lineViewFrameForBoundsSize:(struct CGSize)arg1;
- (struct CGRect)_volumeViewFrameForBoundsSize:(struct CGSize)arg1;
- (void)_layoutSubviews;
- (void)setFrame:(struct CGRect)arg1;
- (void)setDetailedMode:(BOOL)arg1;
- (void)setShowingSelectedLine:(BOOL)arg1;
- (void)setDottedLinePositionsWithLabelInfo:(id)arg1;
- (void)prepareToAnimateSetShowingVolume:(BOOL)arg1;
- (void)animateSetShowingVolume:(BOOL)arg1;
- (void)setVolumeCollapsed:(BOOL)arg1;
- (BOOL)showingVolume;
- (void)volumeDidAnimate;
- (float)_priceAtTime:(double)arg1 dataPosition:(double *)arg2;
- (double)_timeAtPosition:(double)arg1;
- (struct CGRect)_trueGraphPointsRegion;
- (void)clearPaths;
- (void)_finishCurrentLine;
- (unsigned long long)_normalizedAccumulatedVolumeInDataRange:(struct CGPoint)arg1;
- (void)_processGraphDataForWidth:(float)arg1;
- (void)readyForDisplayFromChartData;
- (void)cancelRenderOperation;
- (void)recomputePathsAndRenderWithPriorityIfNeeded:(int)arg1;
- (void)graphRenderOperationDidFinish:(id)arg1;
- (void)resizeSelectedLineClipViewWithLeftX:(float)arg1 rightX:(float)arg2;
- (void)clearData;
- (void)loadStockChartData:(id)arg1;
- (struct CGPoint)rightmostPlottedPoint;
- (CDStruct_8cc9ba3e)plottedPointNearestToPoint:(struct CGPoint *)arg1;
- (struct CGRect)volumeBarRectNearestToPoint:(struct CGPoint)arg1;
- (void)dealloc;
@property(nonatomic) UIView<StockGraphViewContainer> *chartViewDelegate; // @synthesize chartViewDelegate=_chartView;
@property(readonly, nonatomic) NSArray *dottedLinePositions; // @synthesize dottedLinePositions=_dottedLinePositions;
@property(readonly, nonatomic) BOOL isRendered; // @synthesize isRendered=_isRendered;

@end

