/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface StocksPreferences : NSObject
{
    BOOL _changeColorSwapped;
}

+ (id)sharedPreferences;
- (id)init;
- (void)dealloc;
- (void)resetLocale;
@property(readonly, nonatomic, getter=isChangeColorSwapped) BOOL changeColorSwapped; // @synthesize changeColorSwapped=_changeColorSwapped;

@end

