/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Stocks/XMLHTTPRequest.h>

@class NSMutableArray;

@interface SymbolValidator : XMLHTTPRequest
{
    id _delegate;
    NSMutableArray *_validatedSymbols;
    BOOL _useGTServer;
}

- (id)initWithDelegate:(id)arg1;
- (void)setUsesGTServer:(BOOL)arg1;
- (void)validateSymbol:(id)arg1 withMaxResults:(int)arg2;
- (void)cancel;
- (int)parseData:(id)arg1;
- (void)didParseData;
- (void)failWithError:(id)arg1;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;

@end

