/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class UIColor, UIImage;

@interface TintedView : UIView
{
    UIColor *_tintColor;
    UIImage *_image;
}

- (id)init;
- (void)drawRect:(struct CGRect)arg1;
- (void)setImage:(id)arg1;
- (void)setTintColor:(id)arg1;
- (void)dealloc;

@end

