/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class ATXPCConnection, NSObject<ATConnectionDelegate>;

@interface ATConnection : NSObject
{
    ATXPCConnection *_connection;
    NSObject<ATConnectionDelegate> *_delegate;
    BOOL _registerForStatus;
    int _atcRunningToken;
    BOOL _atcRunning;
}

@property(retain, nonatomic) NSObject<ATConnectionDelegate> *delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (id)init;
- (BOOL)isSyncing:(char *)arg1 automatically:(char *)arg2 wirelessly:(char *)arg3;
- (void)lowBatteryNotification;
- (void)dataMigrationFinished;
- (void)clearSyncData;
- (void)cancelSync;
- (void)requestSyncForLibrary:(id)arg1;
- (void)unregisterForStatus;
- (void)registerForStatus;
- (void)_setRegisterForStatus:(BOOL)arg1;
- (void)_sendMessage:(id)arg1 info:(id)arg2 reply:(id)arg3;
- (id)_connection;
- (void)_resetConnection;
- (void)_handleMessage:(id)arg1;

@end

