/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "MPAssetKeyDelegate-Protocol.h"

@class CALayer, MPDocument, MRMarimbaLayer, MediaControlServer, NSData, NSDictionary, NSLock, NSMutableDictionary;

@interface AirPlayLocalSlideshow : NSObject <MPAssetKeyDelegate>
{
    NSLock *_lock;
    MediaControlServer *_server;
    unsigned int _serverSessionID;
    CALayer *_presentationLayer;
    MPDocument *_marimbaDocument;
    MRMarimbaLayer *_marimbaLayer;
    unsigned char _sessionUUID[16];
    NSDictionary *_settings;
    int _state;
    NSMutableDictionary *_assets;
    unsigned int _nextAssetIndex;
    BOOL _hasMoreAssets;
    BOOL _endPending;
    int _outstandingCount;
    double _startTime;
    double _lastRequestTime;
    double _lastRemoveTime;
    NSData *_firstImageData;
}

+ (id)slideshowFeatures;
- (id)initWithServer:(id)arg1;
- (void)dealloc;
- (void)setPresentationLayer:(id)arg1;
- (void)setServerSessionID:(unsigned int)arg1;
- (id)slideshowInfo;
- (id)startSlideshowWithInfo:(id)arg1 error:(id *)arg2;
- (id)stopSlideshowWithInfo:(id)arg1 error:(id *)arg2;
- (id)absolutePathForAssetKey:(id)arg1;
- (id)absolutePathForAssetKey:(id)arg1 andSize:(struct CGSize)arg2;
- (id)absolutePathForStillAssetAtPath:(id)arg1 andSize:(struct CGSize)arg2;
- (id)imageDataForAssetKey:(id)arg1 andSize:(struct CGSize)arg2;
- (struct CGSize)resolutionForAssetKey:(id)arg1;
- (void)_playbackStart;
- (void)_playbackStop;
- (void)_playbackRunStateMachine;
- (void)_playbackPrefetch;
- (void)_playbackPrefetchDone;
- (void)_playbackProducedAssetData:(id)arg1 withAssetInfo:(id)arg2;
- (void)_playbackConsumedAssetKey:(id)arg1;
- (void)_playbackEnded:(id)arg1;
- (id)_assetForAssetKey:(id)arg1;
- (id)_copyImageForAssetKey:(id)arg1 decode:(BOOL)arg2;
- (unsigned int)_bufferedAssetCount;
- (id)_oldestAsset;
- (void)_pruneAssets;
- (void)_postProgressEvent:(id)arg1;
- (void)_setSlideDuration;
- (void)_setTransition;
- (void)_playbackUserPlayPause:(id)arg1;
- (void)_playbackUserStop:(id)arg1;
- (void)_playbackUserNext:(id)arg1;
- (void)_playbackUserPrevious:(id)arg1;

@end

