/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class FTCConnectionHandler, IMTimer;

@interface CKDowngradeServer : NSObject
{
    IMTimer *_nextDowngradeCheckTimer;
    BOOL _ignoreConversationChangeNotifications;
    FTCConnectionHandler *_connectionHandler;
}

+ (id)sharedDowngradeServer;
- (id)init;
- (void)dealloc;
- (void)_setActive:(BOOL)arg1;
- (void)_setActiveIfNecessary;
- (void)start;
- (void)stop;
- (void)_handleSendAsSMSSettingChanged:(id)arg1;
- (void)_handleMessageSent:(id)arg1;
- (BOOL)__messageHasDowngradeMarkers:(id)arg1;
- (double)_lowerDowngradeIntervalForMessage:(id)arg1;
- (double)_upperDowngradeInterval;
- (id)_copyUndeliveredMessages;
- (void)_scheduleTimerCheck;
- (void)_timerFired;
- (void)_setupTimerIfNecessary;
- (BOOL)_shouldSendMessageAsSMS:(id)arg1;
- (BOOL)_shouldIgnoreMessageDueToAge:(id)arg1;
- (BOOL)_shouldIgnoreMessageDueToContent:(id)arg1;
- (void)_sendMessageAsSMS:(id)arg1;
- (void)_resendMessagesAsSMSIfNecessary:(id)arg1;
- (void)_resendMessagesAsSMSIfNecessary;
- (void)_handleDaemonConnected:(id)arg1;

@end

