/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface GKBluetoothSupport : NSObject
{
}

+ (int)bluetoothStatus;
+ (void)cleanup;
+ (void)turnBluetoothOn;
+ (void)initialize;
+ (Class)_bluetoothManagerClass;
+ (int)_determineBluetoothStatus;
+ (void)_btPowerStateChanged:(id)arg1;
+ (int)_directBTStatus;

@end

