/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface SCROBrailleKey : NSObject <NSCoding>
{
    NSMutableArray *_maskArray;
    NSString *_identifier;
    int _routerIndex;
    int _routerToken;
    int _routerLocation;
    BOOL _hasRouterInfo;
    id _appToken;
    int _displayToken;
}

- (id)init;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setDisplayToken:(long)arg1;
- (long)displayToken;
- (id)description;
- (void)addKeyMask:(unsigned long)arg1;
- (id)keyMasks;
- (id)identifier;
- (void)setRouterIndex:(long)arg1 token:(int)arg2 location:(long)arg3 appToken:(id)arg4;
- (BOOL)getRouterIndex:(int *)arg1 token:(int *)arg2 location:(int *)arg3 appToken:(id *)arg4;

@end

