/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSBundle, NSMutableDictionary, NSSet;

@interface SCROMobileBrailleDisplayInputManager : NSObject
{
    NSMutableDictionary *_displayInfoDict;
    NSSet *_brailleKeys;
    NSBundle *_bundle;
    NSArray *_sixDotCommands;
    NSArray *_eightDotCommands;
}

+ (id)sharedManager;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (id)_bundle;
- (id)init;
- (void)dealloc;
- (void)configureWithDriverConfiguration:(id)arg1;
- (id)driverIdentifierForDisplayWithToken:(long)arg1;
- (id)modelIdentifierForDisplayWithToken:(long)arg1;
- (id)commandForBrailleKey:(id)arg1;
- (id)buttonNamesForInputIdentifier:(id)arg1 forDisplayWithToken:(long)arg2;
- (id)_sixDotCommands;
- (id)_eightDotCommands;
- (id)_commandsFromBrailleInputMode:(int)arg1;
- (unsigned int)countForDisplayWithToken:(long)arg1;
- (id)inputIdentifierAtIndex:(unsigned int)arg1 forDisplayWithToken:(long)arg2;
- (id)commandAtIndex:(unsigned int)arg1 forDisplayWithToken:(long)arg2;
- (id)buttonNamesAtIndex:(unsigned int)arg1 forDisplayWithToken:(long)arg2;

@end

