/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SCROConnection : NSObject
{
    BOOL _isConnectionStarted;
    unsigned int _pingPort;
    struct __CFRunLoopSource *_pingSource;
    struct __CFRunLoopSource *_invalidationSource;
    unsigned int _identifier;
    int _handlerType;
    id _delegate;
}

+ (void)initialize;
+ (void)_createConnectionRunLoop;
+ (void)_configServer;
+ (void)_unconfigServerAndRetry:(BOOL)arg1;
+ (void)_addConnectionToRunLoop:(id)arg1;
- (id)initWithHandlerType:(int)arg1 delegate:(id)arg2;
- (void)dealloc;
- (void)invalidate;
- (void)_startConnection;
- (void)_stopConnection;
- (int)sendEvent:(id)arg1;
- (int)registerHandlerCallbackForKey:(int)arg1;
- (int)setHandlerValue:(id)arg1 forKey:(int)arg2;
- (id)handlerValueForKey:(int)arg1;
- (id)handlerValueForKey:(int)arg1 withObject:(id)arg2;
- (int)performHandlerActionForKey:(int)arg1;
- (void)_ping;

@end

