/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SCRCThreadedWeakLinkedObject.h"

@class NSAttributedString, NSData, NSLock, NSMutableAttributedString, SCRCTargetSelectorTimer, SCROConnection;

@interface SCROBrailleClient : SCRCThreadedWeakLinkedObject
{
    SCROConnection *_connection;
    NSLock *_lock;
    id _delegate;
    NSMutableAttributedString *_mainStringPending;
    NSAttributedString *_mainStringCache;
    NSData *_aggregatedStatusPending;
    NSData *_aggregatedStatusCache;
    SCRCTargetSelectorTimer *_deathTimer;
    BOOL _isReady;
    BOOL _needsDisplay;
    BOOL _keepConnectionAlive;
    BOOL _delegateWantsKeypresses;
    BOOL _wantsDisconnectMessage;
    BOOL _wantsReconnectMessage;
    BOOL _wantsDisplayConfigurationChanged;
    BOOL _displayDescriptorCallbackEnabled;
}

- (id)init;
- (id)initWithDelegate:(id)arg1;
- (void)invalidateThreadsWithWeakLinks;
- (void)dealloc;
- (void)_setupDeviceDetection;
- (void)_deviceConnected:(id)arg1;
- (void)setKeepConnectionAlive:(BOOL)arg1;
- (BOOL)keepConnectionAlive;
- (void)_deathTimerHandler;
- (id)_lazyConnection;
- (void)_registerDelegate;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)loadDisplayWithBluetoothDeviceAddress:(id)arg1;
- (void)removeDisplayWithBluetoothDeviceAddress:(id)arg1;
- (void)setTableIdentifier:(id)arg1;
- (id)tableIdentifier;
- (BOOL)isConfigured;
- (id)driverConfiguration;
- (void)setMainAttributedString:(id)arg1;
- (id)pendingMainAttributedString;
- (id)mainAttributedString;
- (void)setAnnouncementString:(id)arg1;
- (void)setAlertString:(id)arg1 timeout:(double)arg2 priority:(int)arg3;
- (void)setAggregatedStatus:(id)arg1;
- (id)pendingAggregatedStatus;
- (id)aggregatedStatus;
- (void)setVirtualStatusAlignment:(int)arg1;
- (int)virtualStatusAlignment;
- (void)setMasterStatusCellIndex:(long)arg1;
- (long)masterStatusCellIndex;
- (void)setShowDotsSevenAndEight:(BOOL)arg1;
- (BOOL)showDotsSevenAndEight;
- (void)setContractionMode:(int)arg1;
- (int)contractionMode;
- (void)setShowEightDotBraille:(BOOL)arg1;
- (BOOL)showEightDotBraille;
- (int)displayMode;
- (void)setExpandedStatusDisplayModeWithStatus:(id)arg1;
- (void)setAnnouncementsDisplayMode;
- (void)exitCurrentDisplayMode;
- (void)setDisplayDescriptorCallbackEnabled:(BOOL)arg1;
- (BOOL)displayDescriptorCallbackEnabled;
- (int)tokenForRouterIndex:(int)arg1 location:(int *)arg2 appToken:(id *)arg3 forDisplayWithToken:(long)arg4;
- (id)_getWorkingString;
- (id)tokenArray;
- (void)setSelection:(struct _NSRange)arg1 forToken:(int)arg2;
- (void)selectAllForToken:(int)arg1;
- (void)unselectAllForToken:(int)arg1;
- (void)setFocused:(BOOL)arg1 forToken:(int)arg2;
- (BOOL)needsDisplay;
- (void)displayIfNeeded;
- (void)display;
- (void)simulateKeypress:(id)arg1;
- (void)panDisplayLeft:(long)arg1;
- (void)panDisplayRight:(long)arg1;
- (void)showPreviousAnnouncement;
- (void)showNextAnnouncement;
- (void)setPrepareToMemorizeNextKey:(BOOL)arg1 immediate:(BOOL)arg2 forDisplayWithToken:(long)arg3;
- (void)setPrimaryBrailleDisplay:(long)arg1;
- (void)handleCallback:(id)arg1;
- (void)_refreshAfterReconnect;
- (BOOL)isConnected;

@end

