/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, SCRCTargetSelectorTimer, SCROConnection;

@interface SCROScriptClient : NSObject
{
    NSLock *_lock;
    SCROConnection *_connection;
    SCRCTargetSelectorTimer *_timer;
    BOOL _isReady;
}

+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedScriptClient;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (id)init;
- (void)_killConnection;
- (id)_lazyConnection;
- (BOOL)_isReady;
- (void)handleCallback:(id)arg1;
- (BOOL)runScriptFile:(id)arg1;

@end

