/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"
#import "SCROIOElementProtocol-Protocol.h"

@interface SCROIOElement : NSObject <SCROIOElementProtocol, NSCopying>
{
    unsigned int _ioObject;
    int _identifier;
}

- (id)initWithIOObject:(unsigned int)arg1;
- (void)dealloc;
- (unsigned int)ioObject;
- (long)identifier;
- (unsigned int)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (int)transport;

@end

