/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIActionSheet.h"

@class UINavigationBar, UINavigationItem, UIPickerView;

@interface AnimatedPickerView : UIActionSheet
{
    UIPickerView *pickerView;
    UINavigationItem *navigationItem;
    UINavigationBar *navigationBar;
}

@property(retain, nonatomic) UINavigationItem *navigationItem; // @synthesize navigationItem;
@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

