/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/AssistantCallbackController.h>

@interface AssistantCallbackController (Private)
+ (id)keychainPasswordForBaseMACAddress:(id)arg1;
- (void)directedScanDone:(id)arg1;
- (void)scanForNetworksDone:(id)arg1;
- (long)startScanForNetworks;
- (long)startDirectedScan:(id)arg1 waitingForNetwork:(BOOL)arg2;
- (void)joinNetworkDone:(id)arg1;
- (long)startJoinNetwork:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (void)userResponseToWarning:(long)arg1;
- (void)userResponseToJoinNetwork:(long)arg1;
- (long)assistantCallback:(struct AssistantCallbackContext *)arg1 withSelector:(int)arg2;
@end

