/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/AssistantUIController.h>

@interface AssistantUIController (Private)
- (void)restoreNetworkDone:(id)arg1;
- (long)startRestoreNetwork:(id)arg1;
- (BOOL)restoreNetworkIfNeeded:(BOOL)arg1 disassociateIfNeeded:(BOOL)arg2 forceQuit:(BOOL)arg3;
- (id)setupPromptStringForBaseInfo:(id)arg1 andResult:(long)arg2;
- (void)handlePresentAutoGuessUIFromAutoGuessCompleteResult:(BOOL)arg1;
- (void)presentUIForConnectionVerification:(int)arg1 status:(long)arg2 paramDict:(id)arg3;
- (long)startSetupFromStepByStepResults:(id)arg1;
@end

