/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock, NSString;

@interface KeychainWrapper : NSObject
{
    NSString *_accountName;
    NSString *_serviceName;
    NSString *_serverName;
    NSString *_dnsName;
    NSLock *_lock;
}

+ (BOOL)supportsSavingAirDiskPasswords;
+ (id)keychainWrapperWithAccountName:(id)arg1 serverName:(id)arg2 dnsName:(id)arg3;
+ (id)keychainWrapperWithAccountName:(id)arg1 serviceName:(id)arg2;
- (id)serviceName;
- (void)setServiceName:(id)arg1;
- (id)accountName;
- (void)setAccountName:(id)arg1;
- (void)removeGenericPassword;
- (id)airDiskPassword;
- (void)removeAirDiskPasswords;
- (long)addInternetPassword:(id)arg1;
- (long)addGenericPasswordWithAttributes:(id)arg1 data:(id)arg2;
- (id)genericPassword;
- (id)genericPasswordForItemRef:(id *)arg1;
- (void)dealloc;
- (id)initWithAccountName:(id)arg1 serverName:(id)arg2 dnsName:(id)arg3;
- (id)initWithAccountName:(id)arg1 serviceName:(id)arg2;

@end

