/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/KeychainWrapper.h>

@interface KeychainWrapper (Private)
- (id)dnsName;
- (void)setDNSName:(id)arg1;
- (id)serverName;
- (void)setServerName:(id)arg1;
- (id)getAirDiskServerDescs;
@end

