/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSFileManager.h"

@interface NSFileManager (PathCompatHelpers)
- (BOOL)moveItemAtPathCompat:(id)arg1 toPath:(id)arg2;
- (id)contentsOfDirectoryAtPathCompat:(id)arg1;
- (BOOL)removeItemAtPathCompat:(id)arg1;
- (BOOL)createDirectoryAtPathCompat:(id)arg1;
@end

