/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIViewController.h"

@class UIPickerView;

@interface PoppablePickerViewController : UIViewController
{
    UIPickerView *pickerView;
}

@property(retain, nonatomic) UIPickerView *pickerView; // @synthesize pickerView;
- (void)dealloc;
- (void)viewDidLoad;

@end

