/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/ViewScroller.h>

@interface ViewScroller (private)
- (struct CGSize)viewScrollerContentSize;
- (struct CGRect)frameForViewAtIndex:(unsigned int)arg1;
- (void)configureView:(id)arg1 forIndex:(unsigned int)arg2;
- (BOOL)isDisplayingViewForIndex:(unsigned int)arg1;
- (id)dequeueRecycledView;
@end

