/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <AirPortAssistant/WiFiUtils.h>

@interface WiFiUtils (private)
+ (BOOL)stringArray:(id)arg1 containsBSSID:(id)arg2;
- (void)setUnmergedScanInfoDict:(id)arg1;
- (id)unmergedScanInfoDict;
- (void)mergeScanResults:(id)arg1;
- (void)asyncWiFiScanThread:(id)arg1;
- (long)asyncWiFiScan:(BOOL)arg1;
- (long)joinNetworkWithScanInfo:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (void)joinNetworkWithNameThread:(id)arg1;
- (void)joinNetworkWithScanInfoThread:(id)arg1;
- (long)scanInfoViaDirectedScanSync:(id)arg1 scanInfo:(id *)arg2;
- (void)scanInfoViaDirectedScanThread:(id)arg1;
- (void)setJoinInProgress:(BOOL)arg1;
- (void)setScanInProgress:(BOOL)arg1;
- (void)triggerScan;
- (void)scanTimerCallback:(id)arg1;
- (long)closeWiFi;
- (long)openWiFi;
@end

