/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSTimer;

@interface WiFiUtils : NSObject
{
    NSDictionary *_unmergedScanInfoDict;
    NSMutableDictionary *_missingBSSIDCounts;
    struct WiFiShimContext *_wifiShim;
    struct dispatch_semaphore_s *_wifiBusy;
    BOOL _scanInProgress;
    BOOL _joinInProgress;
    BOOL _scanningActive;
    BOOL _scanOnlyWhenAppActive;
    NSTimer *_scanTimer;
}

+ (int)barsForRSSI:(int)arg1;
+ (BOOL)networkIsApple:(id)arg1 productID:(unsigned int *)arg2;
+ (BOOL)networkIsSecure:(id)arg1 secMode:(int *)arg2;
+ (id)getNetworkPassword:(id)arg1;
+ (BOOL)scanInfoIs5GHz:(id)arg1;
+ (void)sharedInstanceRelease;
+ (id)sharedInstanceRef;
+ (id)sharedInstance;
@property(retain) NSTimer *_scanTimer; // @synthesize _scanTimer;
- (id)getPreferredNetworks:(BOOL)arg1;
- (BOOL)isCurrentlyAssociatedToAnInfrastructureNetwork:(char *)arg1;
- (BOOL)getAutoJoinState;
- (long)setAutoJoinState:(BOOL)arg1;
- (id)getLinkStatus;
- (id)getIfList;
- (id)getCurrentAssociationScanInfo;
- (id)getCurrentAssociationInfoOrNil;
- (id)getCurrentAssociationInfo;
- (long)scanInfoViaDirectedScanAsync:(id)arg1 waitingForNetwork:(BOOL)arg2;
- (long)clearScanCacheSync;
- (long)dissassociateSync;
- (long)joinNetworkWithNameAsync:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (long)joinNetworkWithScanInfoAsync:(id)arg1 password:(id)arg2 rememberChoice:(int)arg3;
- (id)scanInfoForName:(id)arg1 wifiType:(int)arg2;
- (id)scanInfoForMACAddress:(id)arg1;
- (id)unconfiguredScanInfosOfType:(int)arg1;
- (id)mergedScanInfoArray;
- (id)unmergedScanInfoArray;
- (void)cancelAsync;
- (BOOL)isJoinInProgress;
- (BOOL)isScanInProgress;
- (BOOL)isScanningActive;
- (void)activateScanning:(BOOL)arg1;
- (void)setScanOnlyWhenAppActive:(BOOL)arg1;
- (BOOL)airPortIsOn;
- (void)dealloc;
- (id)init;

@end

