/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSMutableDictionary, NSString, NSURL, UILocalNotification;

@interface Alarm : NSObject
{
    NSString *_id;
    NSURL *_idUrl;
    NSMutableDictionary *_settings;
    UILocalNotification *_notification;
    UILocalNotification *_weeklyNotifications[7];
    UILocalNotification *_snoozedNotification;
    unsigned int _hour;
    unsigned int _minute;
    unsigned int _daySetting;
    BOOL _allowsSnooze;
    NSString *_sound;
    NSString *_title;
    NSDate *_lastModified;
    unsigned int _revision;
    BOOL _hasSnapshot;
    unsigned int _snapshotHour;
    unsigned int _snapshotMinute;
    unsigned int _snapshotDaySetting;
    unsigned char _snapshotAllowsSnooze;
    NSString *_snapshotSound;
    NSString *_snapshotTitle;
    id <AlarmDelegate> _delegate;
}

+ (BOOL)verifyIdSetting:(id)arg1 withMessageList:(id)arg2;
+ (BOOL)verifyHourSetting:(id)arg1 withMessageList:(id)arg2;
+ (BOOL)verifyMinuteSetting:(id)arg1 withMessageList:(id)arg2;
+ (BOOL)verifyDaySetting:(id)arg1 withMessageList:(id)arg2;
+ (BOOL)verifySettings:(id)arg1;
+ (BOOL)_verifyNotificationSettings:(id)arg1 againstAlarmSettings:(id)arg2;
+ (BOOL)_verifyNotificationSettings:(id)arg1 againstUserInfo:(id)arg2;
+ (id)_newSettingsFromNotification:(id)arg1;
- (id)init;
- (id)initWithSettings:(id)arg1;
- (id)initWithNotification:(id)arg1;
- (id)initWithDefaultValues;
- (void)dealloc;
- (id)nowDateForOffsetCalculation;
- (id)timeZoneForOffsetCalculation;
- (unsigned int)_notificationsCount;
- (BOOL)tryAddNotification:(id)arg1;
- (id)_newBaseDateComponentsForDay:(int)arg1;
- (id)_newNotification:(int)arg1;
- (void)prepareNotifications;
- (void)scheduleNotifications;
- (void)cancelNotifications;
- (void)dropNotifications;
- (void)refreshActiveState;
- (void)handleAlarmFired:(id)arg1;
- (void)handleNotificationSnoozed:(id)arg1;
- (void)takeSnapshot;
- (void)revertToSnapshot;
- (void)markModified;
- (int)compareTime:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)alarmId;
- (id)alarmIdUrl;
- (id)settings;
- (unsigned int)hour;
- (void)setHour:(unsigned int)arg1;
- (unsigned int)minute;
- (void)setMinute:(unsigned int)arg1;
- (BOOL)isActive;
- (BOOL)repeats;
- (unsigned int)daySetting;
- (void)setDaySetting:(unsigned int)arg1;
- (BOOL)allowsSnooze;
- (void)setAllowsSnooze:(BOOL)arg1;
- (id)sound;
- (void)setSound:(id)arg1;
- (id)uiTitle;
- (id)rawTitle;
- (void)setTitle:(id)arg1;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (id)debugDescription;
- (id)description;

@end

