/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSDate, NSMutableArray, NSString;

@interface AlarmManager : NSObject
{
    BOOL _dirty;
    NSMutableArray *_alarms;
    NSMutableArray *logMessageList;
    BOOL invalidAlarmsDetected;
    NSDate *lastModified;
}

+ (id)sharedManager;
+ (BOOL)isAlarmNotification:(id)arg1;
+ (BOOL)upgrade;
+ (BOOL)discardOldVersion;
+ (void)writeAlarmsToPreferences:(id)arg1;
+ (id)readAlarmsFromPreferencesCopy;
- (id)init;
- (void)dealloc;
@property(retain, nonatomic) NSString *defaultSound;
- (void)loadAlarms;
- (void)unloadAlarms;
- (void)saveAlarms;
- (BOOL)checkIfAlarmsModified;
- (id)alarmWithIdUrl:(id)arg1;
- (void)addAlarm:(id)arg1 active:(BOOL)arg2;
- (void)updateAlarm:(id)arg1 active:(BOOL)arg2;
- (void)removeAlarm:(id)arg1;
- (void)setAlarm:(id)arg1 active:(BOOL)arg2;
- (void)loadScheduledNotifications;
- (void)loadScheduledNotificationsWithCancelUnused:(BOOL)arg1;
- (void)reloadScheduledNotifications;
- (void)reloadScheduledNotificationsWithRefreshActive:(BOOL)arg1 cancelUnused:(BOOL)arg2;
- (void)handleAnyNotificationChanges;
- (void)handleExpiredOrSnoozedNotificationsOnly;
- (void)handleNotificationSnoozed:(id)arg1;
- (void)handleNotificationFired:(id)arg1;
@property(retain, nonatomic) NSDate *lastModified; // @synthesize lastModified;
@property(readonly, retain, nonatomic) NSArray *alarms; // @synthesize alarms=_alarms;
@property(nonatomic) BOOL invalidAlarmsDetected; // @synthesize invalidAlarmsDetected;
@property(retain, nonatomic) NSMutableArray *logMessageList; // @synthesize logMessageList;

@end

