/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSBundle, NSString;

@interface HandView : UIView
{
    NSBundle *_resourcesBundle;
    NSString *_name;
    NSString *_pmname;
    struct CGPoint _offset;
    float _handAngle;
    BOOL _evening;
    struct CGSize _scale;
    struct CGPoint _center;
    struct CGPoint _imageCenter;
}

- (struct CGPDFPage *)_loadImage:(id)arg1;
- (struct CGDisplayList *)_displayList:(id)arg1;
- (id)initWithPDFFile:(id)arg1 scale:(struct CGSize)arg2 bundle:(id)arg3;
- (void)dealloc;
- (void)setOffset:(struct CGPoint)arg1;
- (void)setHandAngle:(float)arg1;
- (float)handAngle;
- (void)setEvening:(BOOL)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

