/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSCalendarDate, NSMutableArray, NSString;

@interface City : NSObject
{
    id _delegate;
    int _updateInterval;
    NSString *_name;
    NSString *_locationID;
    NSString *_state;
    NSString *_link;
    NSString *_temperature;
    unsigned int _bigIcon;
    NSMutableArray *_dayForecasts;
    NSMutableArray *_hourlyForecasts;
    unsigned int _observationTime;
    unsigned int _sunsetTime;
    unsigned int _sunriseTime;
    unsigned int _moonPhase;
    BOOL _dataCelsius;
    BOOL _autoUpdate;
    BOOL _isUpdating;
    NSString *_updateTimeString;
    NSCalendarDate *_updateTime;
    int _lastUpdateStatus;
    int _lastUpdateDetail;
    BOOL _fromSecondaryService;
    BOOL isLocalWeatherCity;
    BOOL _hourlyDataIsCelsius;
    NSString *_windChill;
    unsigned int _windDirection;
    unsigned int _windSpeed;
    unsigned int _humidity;
    float _visibility;
    float _pressure;
    int _pressureRising;
    float _dewPoint;
    float _feelsLike;
    float _heatIndex;
    NSString *_woeid;
    BOOL _isLocalWeatherCity;
}

- (id)init;
- (void)dealloc;
- (id)description;
- (void)associateWithDelegate:(id)arg1;
- (void)disassociateWithDelegate:(id)arg1;
- (void)setAutoUpdate:(BOOL)arg1;
- (void)setName:(id)arg1;
- (id)name;
- (id)locationID;
- (id)displayName;
- (void)setLocationID:(id)arg1;
- (void)setLink:(id)arg1;
- (id)link;
- (void)setTemperature:(id)arg1;
- (id)temperature;
- (unsigned int)bigIcon;
- (void)setBigIcon:(unsigned int)arg1;
- (void)setDayForecasts:(id)arg1;
- (id)dayForecasts;
- (void)setObservationTime:(unsigned int)arg1;
- (unsigned int)observationTime;
- (void)setSunsetTime:(unsigned int)arg1;
- (unsigned int)sunsetTime;
- (void)setSunriseTime:(unsigned int)arg1;
- (unsigned int)sunriseTime;
- (BOOL)isDay;
- (unsigned int)moonPhase;
- (void)setMoonPhase:(unsigned int)arg1;
- (BOOL)isDataCelsius;
- (void)setDataCelsius:(BOOL)arg1;
- (int)weatherDataAge;
- (void)updateLocalWeather;
- (void)update;
- (void)clearForecasts;
- (void)addDayForecast:(id)arg1;
- (void)setHourlyForecasts:(id)arg1;
- (id)hourlyForecasts;
- (void)addHourlyForecast:(id)arg1;
- (void)setUpdateTime:(id)arg1;
- (void)finishedUpdating:(int)arg1 statusDetail:(int)arg2;
- (BOOL)_isUpdating;
- (BOOL)isUpdatingOrNoData;
- (void)setLastUpdateStatus:(int)arg1;
- (int)lastUpdateStatus;
- (int)lastUpdateDetail;
- (id)updateTime;
- (id)updateTimeString;
- (BOOL)fromSecondaryService;
- (void)setFromSecondaryService:(BOOL)arg1;
- (void)setState:(id)arg1;
- (id)state;
- (id)cityAndState;
@property(copy, nonatomic) NSString *woeid; // @synthesize woeid=_woeid;
- (BOOL)populateWithDataFromCity:(id)arg1;
- (id)windDirectionAsString:(int)arg1;
@property(nonatomic) BOOL isLocalWeatherCity; // @synthesize isLocalWeatherCity=_isLocalWeatherCity;
@property(nonatomic) float heatIndex; // @synthesize heatIndex=_heatIndex;
@property(nonatomic) float feelsLike; // @synthesize feelsLike=_feelsLike;
@property(nonatomic) float dewPoint; // @synthesize dewPoint=_dewPoint;
@property(nonatomic) int pressureRising; // @synthesize pressureRising=_pressureRising;
@property(nonatomic) float pressure; // @synthesize pressure=_pressure;
@property(nonatomic) float visibility; // @synthesize visibility=_visibility;
@property(nonatomic) unsigned int humidity; // @synthesize humidity=_humidity;
@property(nonatomic) unsigned int windSpeed; // @synthesize windSpeed=_windSpeed;
@property(nonatomic) unsigned int windDirection; // @synthesize windDirection=_windDirection;
@property(copy, nonatomic) NSString *windChill; // @synthesize windChill=_windChill;
@property(nonatomic) BOOL isHourlyDataCelsius; // @synthesize isHourlyDataCelsius=_hourlyDataIsCelsius;

@end

