/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (WeatherStringAdditions)
- (void)draw:(id)arg1 atPoint:(struct CGPoint)arg2 forWidth:(float)arg3 withFont:(id)arg4 fontColor:(id)arg5;
- (void)draw:(id)arg1 inRect:(struct CGRect)arg2 withFont:(id)arg3 fontColor:(id)arg4 alignment:(int)arg5;
- (void)drawAtPoint:(struct CGPoint)arg1 forWidth:(float)arg2 withFont:(id)arg3 fontColor:(id)arg4 shadowColor:(id)arg5 centeredHorizontally:(BOOL)arg6 uncenteredSuffix:(id)arg7;
@end

