/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <Weather/WeatherUpdater.h>

@interface WeatherIdentifierUpdater : WeatherUpdater
{
}

+ (id)sharedWeatherIdentifierUpdater;
- (void)updateWeatherForCity:(id)arg1;
- (void)_failed:(int)arg1;

@end

