/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

#import "CityUpdaterDelegate-Protocol.h"

@class City, UIImage;

@interface WeatherView : UIView <CityUpdaterDelegate>
{
    City *_city;
    id _delegate;
    BOOL _showingDay;
    UIImage *_bigIcon;
    UIImage *_secondaryBigIcon;
    unsigned int _bigIconIndex;
    BOOL _showWind;
    UIView *_windView;
}

- (void)dealloc;
- (void)cityDidFinishWeatherUpdate:(id)arg1;
@property(retain, nonatomic, setter=showCity:) City *city; // @synthesize city=_city;
- (void)updateWeatherDisplayForCity:(id)arg1;
- (void)cityDidStartWeatherUpdate:(id)arg1;
- (void)refreshLocalization;
- (struct CGRect)windFrame;
- (void)setupBigIconOffset:(int)arg1;
- (void)setupSecondaryBigIconOffset:(int)arg1;
- (id)bundle;
- (void)_removeWindView;
- (id)bigImageBundle;
- (void)updateWind;
- (void)setBigIcon:(unsigned int)arg1 dayNightChanged:(BOOL)arg2;
- (id)_bigIcon;
- (id)_secondaryBigIcon;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;

@end

