/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class SUManager;

@interface SUBackgroundTaskAgent : NSObject
{
    SUManager *_manager;
}

+ (id)sharedInstance;
- (void)_handleBackgroundAgentAutoScan:(const char *)arg1 parameters:(void *)arg2;
- (void)_scheduleNewBackgroundAgentAutoScanForType:(int)arg1 jobName:(const char *)arg2 previousStartDate:(id)arg3 previousEndDate:(id)arg4;
- (void)_scheduleAutoScanForTypeIfNecessary:(int)arg1 jobName:(const char *)arg2;
- (void)_handleAutodownloadWifiPeriodEndTask:(void *)arg1;
- (void)cancelAutodownloadWifiPeriodEndTask;
- (void)scheduleAutodownloadWifiPeriodEndTaskIfNecessary;
- (void)scheduleAutodownloadWifiPeriodEndTask;
- (void)_handleAutodownloadRetryTask:(void *)arg1;
- (void)cancelAutodownloadRetryTask;
- (void)scheduleAutodownloadRetryTaskIfNecessary;
- (void)scheduleAutodownloadRetryTaskFromDate:(id)arg1 toDate:(id)arg2 policy:(id)arg3;
- (void)_addAutodownloadPowerRequirementsToRequest:(void *)arg1;
- (void)cancelEmergencyAutoScanTask;
- (void)scheduleEmergencyAutoScanTaskIfNecessary;
- (void)cancelDefaultAutoScanTask;
- (void)scheduleDefaultAutoScanTaskIfNecessary;
- (void)cancelAllAutodownloadTasks;
- (void)cancelAllAutoscanTasks;
- (void)cancelAllTasks;
- (void)scheduleAnyTasksIfNecessary;
- (void)_printDetailsForJob:(const char *)arg1;
- (void)_initBackgroundTaskAgent;
- (void)dealloc;
- (id)init;

@end

