/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIButton.h"

@interface AlbumSongListAggregateShuffleButton : UIButton
{
    BOOL _highlightStateChangesDisallowedCount;
    BOOL _highlightStateChangeWasSkipped;
    BOOL _highlightStateSkipped;
}

- (void)setHighlighted:(BOOL)arg1;
- (void)_endDisallowingHighlightChangesForEventAfterDelay;
- (void)_delayedEndDisallowingHighlightChangesForEvent;
- (void)_endDisallowingHighlightChangesForEvent;
- (void)_beginDisallowingHighlightChangesForEvent;
- (void)endDisallowingHighlightChanges;
- (void)beginDisallowingHighlightChanges;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGRect)sloppyHitRect;
- (int)buttonType;
- (id)init;

@end

