/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class IULiveReflectionView;

@interface IUDoorSwingTransitionView : UIView
{
    id <IUDoorSwingTransitionViewDelegate> _delegate;
    UIView *_doorsView;
    IULiveReflectionView *_zoomView;
    int _currentTransition;
    BOOL _transitioning;
}

+ (double)defaultDurationForTransition:(int)arg1;
@property(retain, nonatomic) UIView *zoomView; // @synthesize zoomView=_zoomView;
@property(readonly, nonatomic, getter=isTransitioning) BOOL transitioning; // @synthesize transitioning=_transitioning;
@property(retain, nonatomic) UIView *doorsView; // @synthesize doorsView=_doorsView;
@property(nonatomic) id <IUDoorSwingTransitionViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int currentTransition; // @synthesize currentTransition=_currentTransition;
- (void)_informDelegateOfCompletion;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)dealloc;
- (BOOL)transition:(int)arg1 fromView:(id)arg2 toView:(id)arg3 usingOrientation:(int)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

