/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUMediaDataSource.h>

@class NSMutableArray;

@interface IUGeniusMixDataSource : IUMediaDataSource
{
    NSMutableArray *_mixes;
    unsigned int _countOfMixes;
}

+ (id)moreListTitleKey;
+ (id)tabBarItemTitleKey;
+ (id)tabBarItemIconName;
+ (id)defaultTitle;
- (id)_geniusMixAtIndex:(unsigned int)arg1;
- (id)viewControllerContextForIndex:(unsigned int)arg1;
- (struct CGImage *)representativeImageAtIndex:(unsigned int)arg1 withSize:(struct CGSize)arg2 count:(unsigned int)arg3;
- (unsigned int)countOfRepresentativeImagesAtIndex:(unsigned int)arg1 maxCount:(unsigned int)arg2;
- (id)representativeArtistsAtIndex:(unsigned int)arg1;
- (id)mixNameAtIndex:(unsigned int)arg1;
- (unsigned int)indexOfMix:(id)arg1;
- (id)mixAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int countOfMixes;
- (void)unloadReloadableData;
- (void)_cacheMixArtworkInBackground:(id)arg1;
- (void)_invalidateForArtworkCacheChange;
- (void)reloadData;
- (SEL)libraryHasDisplayableEntitiesSelector;
- (void)dealloc;
- (id)init;

@end

