/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUiPodViewController.h>

#import "IUGeniusGridViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class IUGeniusGridView, MPGeniusMix, NSMutableArray, NSMutableSet, UIImageView, UIPageControl, UIScrollView;

@interface IUGeniusMixViewController : IUiPodViewController <IUGeniusGridViewDelegate, UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    NSMutableArray *_gridViews;
    UIPageControl *_pageControl;
    IUGeniusGridView *_flippedGridView;
    NSMutableSet *_unusedGridViewPool;
    UIImageView *_artworkImageView;
    unsigned int _didPushMix:1;
    unsigned int _isZooming:1;
}

- (void)_zoomOutDidStop;
- (void)_zoomArtworkOut;
- (void)_zoomArtworkInForDataSource:(id)arg1;
- (BOOL)_currentPageIsPlayingGeniusMix;
- (int)_playingGeniusMixPage;
- (void)_nowPlayingItemDidChange:(id)arg1;
- (void)_pushViewControllerContext:(id)arg1;
- (id)_viewControllerContextForCurrentPage;
- (void)_flipGridViewForAnimatedPop;
- (void)_flipGridView:(id)arg1 toOrientation:(int)arg2 animated:(BOOL)arg3;
- (struct CGPoint)_contentOffsetForPage:(int)arg1;
- (struct CGPoint)_contentOffsetForCurrentPage;
- (int)_pageForContentOffset;
- (void)_pageControlValueDidChange:(id)arg1;
- (void)_enqueueGridViewForReuse:(id)arg1;
- (id)_dequeueExistingGridView;
- (BOOL)_hasGridViewForPage:(int)arg1;
- (void)_pruneGridViewPages;
- (void)_createGridViewIfNecessaryForPage:(int)arg1;
- (id)_geniusMixDataSource;
@property(readonly, nonatomic) MPGeniusMix *selectedMix;
- (void)geniusGridViewWasTapped:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (int)navigationTransition;
- (id)_moreListTitle;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)reloadData;
- (void)reloadDataWithSelectedMix:(id)arg1;
- (void)loadView;
- (void)_unloadGridViews;
- (void)dealloc;
- (id)init;

@end

