/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUMediaListViewController.h>

@interface IUGroupedVideosViewController : IUMediaListViewController
{
}

- (void)_showSharedLibrariesController;
- (void)_defaultMediaLibraryDidChangeNotification:(id)arg1;
- (void)_availableMediaLibrariesDidChangeNotification:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)performActionForActionRow:(id)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (id)init;

@end

