/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UINavigationController.h"

@class IUModalContext, NSString, UINavigationItem;

@interface IUiPodNavigationController : UINavigationController
{
    IUModalContext *_modalContext;
    UINavigationItem *_navigationItemTemplate;
}

@property(retain, nonatomic) IUModalContext *modalContext; // @synthesize modalContext=_modalContext;
- (void)_updateViewControllersModalContext;
- (BOOL)_shouldNavigationBarInsetViewController:(id)arg1;
- (id)popToViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (id)description;
- (void)loadView;
@property(readonly, nonatomic) NSString *rootIdentifier;
- (void)dealloc;

@end

