/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUiPadVideoPartTableViewCellContentView.h>

@class MPButton, NSArray, NSString, UIImageView, UIView;

@interface IUiPadVideoEpisodeTableViewCellContentView : IUiPadVideoPartTableViewCellContentView
{
    NSString *_expirationText;
    struct CGSize _expirationTextSize;
    BOOL _expiresSoon;
    NSString *_title;
    NSString *_summary;
    NSArray *_supertitles;
    MPButton *_moreButton;
    id _moreButtonTarget;
    SEL _moreButtonAction;
    BOOL _expanded;
    int _unplayedState;
    UIImageView *_unplayedIndicator;
    UIView *_disabledView;
}

@property(nonatomic) int unplayedState; // @synthesize unplayedState=_unplayedState;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *supertitles; // @synthesize supertitles=_supertitles;
@property(retain, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(nonatomic) id moreButtonTarget; // @synthesize moreButtonTarget=_moreButtonTarget;
@property(nonatomic) SEL moreButtonAction; // @synthesize moreButtonAction=_moreButtonAction;
@property(retain, nonatomic) NSString *expirationText; // @synthesize expirationText=_expirationText;
@property(nonatomic) BOOL expiresSoon; // @synthesize expiresSoon=_expiresSoon;
@property(nonatomic) BOOL expanded; // @synthesize expanded=_expanded;
- (struct __CFAttributedString *)_newSummaryAttributedString:(id)arg1 withLineBreakMode:(unsigned char)arg2;
- (void)_moreButtonSelected:(id)arg1;
- (void)_drawText;
- (void)setHighlightedOrSelected:(BOOL)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1 expanded:(BOOL)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;

@end

