/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUMediaListDataSource.h>

@class IUMediaDataSource, MPMediaLibrary, MPMediaQuery, NSArray, NSMutableArray;

@interface IUMediaQueriesDataSource : IUMediaListDataSource
{
    NSArray *_queries;
    MPMediaLibrary *_mediaLibrary;
    NSMutableArray *_queriesEntities;
    NSArray *_queriesBeforeFiltering;
    IUMediaDataSource *_dataSourceForFiltering;
    BOOL _hasQueriesAreEmpty;
    BOOL _queriesAreEmpty;
    unsigned long long _nowPlayingItemPersistentID;
    int _invalidationBehavior;
    unsigned int _reloading:1;
    unsigned int _queriesEntitiesChanged:1;
    unsigned int _hasPendingDynamicChanges:1;
    unsigned int _hasPendingDefaultLibraryChanges:1;
    unsigned int _hasPendingLibraryChanges:1;
}

+ (id)_imageCache;
+ (BOOL)usesNowPlayingIndicator;
+ (int)mediaEntityType;
+ (id)selectionConfirmationAlertForEntity:(id)arg1;
+ (Class)cellConfigurationClassForSongs;
+ (id)queryCollectionPropertiesToFetch;
+ (id)queryItemPropertiesToFetch;
+ (id)newDataSourceWithQuery:(id)arg1;
+ (id)newDataSourceWithSpecifier:(id)arg1;
@property(retain, nonatomic) NSArray *queries; // @synthesize queries=_queries;
@property(readonly, nonatomic) unsigned long long nowPlayingItemPersistentID; // @synthesize nowPlayingItemPersistentID=_nowPlayingItemPersistentID;
@property(retain, nonatomic) MPMediaLibrary *mediaLibrary; // @synthesize mediaLibrary=_mediaLibrary;
@property(nonatomic) int invalidationBehavior; // @synthesize invalidationBehavior=_invalidationBehavior;
- (void)_setQueriesEntities:(id)arg1;
- (void)_reloadFilteredQueries;
- (id)_newContextForShuffle;
- (id)_newContextForCopyWithIdentifier:(id)arg1;
- (id)_newContextForAllSongs;
- (id)_newContextForAllAlbums;
- (id)_copyReloadedQueriesEntitiesForQueries:(id)arg1 library:(id)arg2;
- (void)_addDefaultOnTheGoActionRows;
- (void)_addDefaultNormalActionRows;
- (void)_addPrefixActionRow:(id)arg1;
- (void)setArtAStillFrame:(BOOL)arg1 atIndex:(unsigned int)arg2;
@property(readonly, nonatomic) BOOL alwaysGroupedInGridView;
@property(readonly, nonatomic) BOOL showShuffleButtonWhenApplicable;
@property(readonly, nonatomic) unsigned int requiredEntityCountForSections;
- (id)entitiesForQuery:(id)arg1;
- (id)_newGetMoreActionRowForMediaType:(int)arg1;
- (id)_getMoreURLForMediaType:(int)arg1;
- (void)_getMoreAction:(id)arg1;
- (id)copyGetMoreFromITunesStoreActionRow;
- (id)bestStoreURL;
@property(readonly, nonatomic) BOOL shouldLoadLocalImagesSynchronously; // @dynamic shouldLoadLocalImagesSynchronously;
@property(readonly, nonatomic) BOOL matchesNowPlayingQuery;
- (void)invalidateDynamicTrackCaches;
- (void)reloadNowPlayingItemPersistentID;
- (void)appDefaultsChanged;
- (id)queryForDrillingIntoRowAtIndex:(unsigned int)arg1;
- (unsigned int)indexOfPersistentID:(unsigned long long)arg1;
- (unsigned int)indexOfEntity:(id)arg1;
- (id)queryForIndex:(unsigned int)arg1 localEntityIndex:(unsigned int *)arg2;
- (id)entityAtIndex:(unsigned int)arg1;
- (id)entityAtIndex:(unsigned int)arg1 localEntityIndex:(unsigned int *)arg2 localEntityCount:(unsigned int *)arg3 query:(id *)arg4;
@property(copy, nonatomic) MPMediaQuery *query;
- (void)_mediaLibraryDidChangeNotification:(id)arg1;
- (void)_mediaLibraryDynamicPropertiesDidChangeNotification:(id)arg1;
- (void)_handleTrackDynamicPropertiesChanged;
- (void)_handleMediaLibraryDidChange;
- (void)_handleDefaultMediaLibraryDidChange;
- (void)_defaultMediaLibraryDidChangeNotification:(id)arg1;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_appDefaultsDidChangeNotification:(id)arg1;
- (BOOL)shouldDrawAsDisabledForIndex:(unsigned int)arg1;
- (BOOL)selectionPossibleForIndex:(unsigned int)arg1;
- (BOOL)selectionPossibleForActionRow:(id)arg1;
- (id)viewControllerContextForActionRow:(id)arg1;
- (id)selectionConfirmationAlertForIndex:(unsigned int)arg1;
- (int)mediaDisclosureStyleForIndex:(unsigned int)arg1;
- (BOOL)deleteIndexesInRange:(struct _NSRange)arg1;
- (void)reloadSectionInfo;
- (void)reloadIsEmpty;
- (void)reloadActionRows;
- (BOOL)skipSingleItemLists;
- (float)rowHeight;
- (id)playbackContextForIndex:(unsigned int)arg1;
- (id)playbackContextForQuery:(id)arg1 entityIndex:(unsigned int)arg2;
- (BOOL)hasPlayableItems;
- (id)deleteConfirmationSheetForIndex:(unsigned int)arg1;
- (id)deleteConfirmationAlertViewForIndex:(unsigned int)arg1;
- (id)cellConfigurationForIndex:(unsigned int)arg1 artworkLoadingCompletionHandler:(id)arg2;
- (Class)cellConfigurationClassForEntity:(id)arg1;
- (id)countStringFormat;
- (BOOL)canDeleteIndex:(unsigned int)arg1;
- (unsigned int)count;
- (BOOL)isEmpty;
- (BOOL)filterUsingDataSource:(id)arg1;
- (BOOL)isFiltered;
- (BOOL)isEmptyAfterFiltering;
- (id)viewControllerContextForSearchCompletion;
- (BOOL)isRestorableNavigationPathNode;
- (void)reloadData;
- (void)invalidate;
- (void)reloadDataWithCompletionHandler:(id)arg1;
- (void)reloadQueriesEntities;
- (void)dealloc;
- (id)init;

@end

