/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IUMediaTableCell, IUTableCellConfiguration, UIView;

@interface IUMediaActionRow : NSObject
{
    SEL _action;
    IUMediaTableCell *_cell;
    IUTableCellConfiguration *_configuration;
    BOOL _includeInDisplayedRowCount;
    BOOL _selectable;
    BOOL _showCheckmark;
    BOOL _showDisclosure;
    BOOL _showPlusButton;
    int _tag;
}

+ (id)hyperlinkActionRowWithTitle:(id)arg1;
+ (id)actionRowWithPreset:(int)arg1 action:(SEL)arg2;
@property(nonatomic) int tag; // @synthesize tag=_tag;
@property(nonatomic) BOOL showPlusButton; // @synthesize showPlusButton=_showPlusButton;
@property(nonatomic) BOOL showDisclosure; // @synthesize showDisclosure=_showDisclosure;
@property(nonatomic) BOOL showCheckmark; // @synthesize showCheckmark=_showCheckmark;
@property(nonatomic) BOOL selectable; // @synthesize selectable=_selectable;
@property(nonatomic) BOOL includeInDisplayedRowCount; // @synthesize includeInDisplayedRowCount=_includeInDisplayedRowCount;
@property(retain, nonatomic) IUTableCellConfiguration *configuration; // @synthesize configuration=_configuration;
@property(retain, nonatomic) IUMediaTableCell *cell; // @synthesize cell=_cell;
@property(nonatomic) SEL action; // @synthesize action=_action;
- (void)setSimpleConfigurationWithTitle:(id)arg1;
- (void)setSimpleConfigurationPreset:(int)arg1;
@property(readonly, nonatomic) int mediaDisclosureStyle;
@property(readonly, nonatomic) UIView *accessoryView;
- (void)dealloc;
- (id)description;
- (id)initWithTag:(int)arg1 action:(SEL)arg2;

@end

