/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUMediaTableCell.h>

@class NSMutableArray, UIColor;

@interface IUMediaActionButtonsCell : IUMediaTableCell
{
    id _delegate;
    NSMutableArray *_buttons;
    UIColor *_bottomSeparatorColor;
}

@property(retain, nonatomic) UIColor *bottomSeparatorColor; // @synthesize bottomSeparatorColor=_bottomSeparatorColor;
@property(nonatomic) id delegate; // @synthesize delegate=_delegate;
- (id)_buttonImageForControlState:(unsigned int)arg1 stretchable:(BOOL)arg2;
- (void)_buttonAction:(id)arg1;
- (BOOL)supportsSpinning;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)_didCreateContentView;
- (id)createButtonWithTitle:(id)arg1 action:(SEL)arg2;
- (void)_buttonFadeDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)reconfigureWithButtonTitles:(id)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (id)initWithTitles:(id)arg1;

@end

