/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "MPViewController.h"

#import "IUCoverFlowTransitionViewController-Protocol.h"
#import "MPVideoTransferViewController-Protocol.h"

@class IUFlipperButton, MPImageCache, MPImageCacheRequest, MPPortraitTransportControls, UINavigationButton, UITransitionView, UIView;

@interface IUNowPlayingPortraitViewController : MPViewController <IUCoverFlowTransitionViewController, MPVideoTransferViewController>
{
    MPPortraitTransportControls *_transportControls;
    UIView *_flipContainerView;
    UINavigationButton *_backButton;
    UINavigationButton *_scaleModeButton;
    IUFlipperButton *_flipperButton;
    MPImageCache *_flipperImageCache;
    MPImageCacheRequest *_flipperImageRequest;
    MPViewController *_preFlipController;
    MPViewController *_preSlideController;
    MPViewController *_mainController;
    UITransitionView *_transitionView;
    UIView *_transitionOverlayView;
    BOOL _showFlipperHint;
    BOOL _didZoom;
    unsigned int _tvOutEnabled:1;
}

@property(nonatomic) BOOL showFlipperHint; // @synthesize showFlipperHint=_showFlipperHint;
- (BOOL)isStatusBarHidden;
- (int)statusBarStyle;
- (id)_viewControllerForChangeFromItem:(id)arg1 toItem:(id)arg2 withAvailableController:(id)arg3;
- (Class)_viewControllerClassForItem:(id)arg1;
- (void)_updateViewControllerForChangeFromItem:(id)arg1 toItem:(id)arg2 animate:(BOOL)arg3;
- (void)_updateNavigationBarForItem:(id)arg1 animate:(BOOL)arg2;
- (void)_slideToController:(id)arg1 transition:(int)arg2;
- (void)_setFlipperButtonImageWithItem:(id)arg1 time:(double)arg2;
- (void)_reloadForChangeFromItem:(id)arg1 toItem:(id)arg2;
- (id)_navigationBar;
- (id)_flipTransition;
- (id)_flipperButton;
- (void)_flipFromViewController:(id)arg1 toViewController:(id)arg2 withType:(id)arg3;
- (void)_exitNowPlaying;
- (void)_configureViewController:(id)arg1;
- (BOOL)transportControls:(id)arg1 tappedButtonPart:(unsigned int)arg2;
- (BOOL)transportControls:(id)arg1 releasedHeldButtonPart:(unsigned int)arg2;
- (BOOL)transportControls:(id)arg1 heldButtonPart:(unsigned int)arg2;
- (void)_scaleModeButton:(id)arg1;
- (void)_flipperButton:(id)arg1;
- (void)_back:(id)arg1;
- (void)_crossedTimeMarkerNotification:(id)arg1;
- (void)videoController:(id)arg1 willShowChaptersWithTransition:(id)arg2;
- (void)videoController:(id)arg1 scaleModeDidChange:(unsigned int)arg2;
- (void)viewController:(id)arg1 viewWasDoubleTapped:(id)arg2;
- (void)viewController:(id)arg1 endIgnoringChangeType:(unsigned int)arg2;
- (void)viewController:(id)arg1 beginIgnoringChangeTypes:(unsigned int)arg2;
- (void)viewControllerRequestsExit:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)videoView;
- (void)displayVideoView;
- (void)coverFlowWillTransitionOut:(BOOL)arg1;
- (void)coverFlowWillTransitionIn:(BOOL)arg1;
- (void)coverFlowIsTransitioningOut:(BOOL)arg1;
- (void)coverFlowIsTransitioningIn:(BOOL)arg1;
- (void)coverFlowDidTransitionOut:(BOOL)arg1;
- (void)coverFlowDidTransitionIn:(BOOL)arg1;
- (id)coverViewFlipView;
@property(nonatomic, getter=isTVOutEnabled) BOOL TVOutEnabled;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)setOrientation:(int)arg1 animate:(BOOL)arg2;
- (void)_setExistingNavigationItem:(id)arg1;
- (void)setItem:(id)arg1;
- (void)noteIgnoredChangeTypes:(unsigned int)arg1;
- (id)navigationController;
- (void)loadView;
- (int)displayableInterfaceOrientationForInterfaceOrientation:(int)arg1;
- (BOOL)canDisplayItem:(id)arg1 withInterfaceOrientation:(int)arg2;
- (void)flip:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(nonatomic) BOOL inhibitOverlay;

@end

