/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class MPAVController, MPSystemNowPlayingController;

@interface IUNowPlayingObserver : NSObject
{
    MPSystemNowPlayingController *_nowPlayingController;
    MPAVController *_player;
}

- (id)_currentItem;
- (void)_rateDidChangeNotification:(id)arg1;
- (void)_timeDidJumpNotification:(id)arg1;
- (void)_repeatTypeChanged:(id)arg1;
- (void)_playbackStateChanged:(id)arg1;
- (void)_itemChanged:(id)arg1;
- (void)_contentsChanged:(id)arg1;
- (void)dealloc;
- (id)initWithPlayer:(id)arg1;
- (id)init;

@end

