/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUPlaylistDataSource.h>

@interface IUPlaylistsDataSource : IUPlaylistDataSource
{
}

+ (id)queryCollectionPropertiesToFetch;
+ (id)tabBarItemTitleKey;
+ (id)tabBarItemIconName;
- (id)_otgActionRow;
- (id)_geniusActionRow;
- (id)_newOnTheGoViewControllerContext;
- (id)_newGeniusNotEnabledViewControllerContext;
- (id)_newActiveGeniusViewControllerContext;
- (id)_addPlaylistActionRow;
- (id)entitiesForQuery:(id)arg1;
- (id)viewControllerContextForActionRow:(id)arg1;
- (id)prefixActionRows;
- (void)invalidate;
- (void)reloadActionRows;
- (BOOL)hasActionRowsEvenWhenNoOtherRowsExist;
- (int)initialVisibleIndex;
- (int)initialSelectedIndex;
- (int)mediaDisclosureStyleForIndex:(unsigned int)arg1;
- (id)cellConfigurationForIndex:(unsigned int)arg1 artworkLoadingCompletionHandler:(id)arg2;
- (Class)cellConfigurationClassForEntity:(id)arg1;
- (SEL)libraryHasDisplayableEntitiesSelector;

@end

