/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUSongCellConfigurationAbstract.h>

@class NSString;

@interface IUSongCellConfiguration : IUSongCellConfigurationAbstract
{
    NSString *_title;
    NSString *_album;
    NSString *_artist;
    int _mediaType;
}

+ (float)rowHeightForGlobalContext:(id)arg1;
+ (void)getRequiredStringProperties:(id)arg1 optionalStringProperties:(id)arg2 forDataSource:(id)arg3;
@property(nonatomic) int mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) NSString *artist; // @synthesize artist=_artist;
@property(retain, nonatomic) NSString *album; // @synthesize album=_album;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void)reloadStrings;
- (void)reloadImages;
- (void)reloadLayoutInformation;
- (id)fontForLabelAtIndex:(unsigned int)arg1;
- (struct CGRect)downloadProgressIndicatorFrame;
- (struct CGRect)downloadButtonFrame;
- (id)colorForLabelAtIndex:(unsigned int)arg1 withModifiers:(unsigned int)arg2;
- (void)dealloc;
- (id)init;
- (id)description;

@end

