/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ISOperation.h"

@class NSDictionary, NSHTTPURLResponse, NSString;

@interface IUStoreSocialActionOperation : ISOperation
{
    NSString *_actionType;
    unsigned long long _itemIdentifier;
    NSDictionary *_responseDictionary;
    NSHTTPURLResponse *_urlResponse;
}

- (void)_setURLResponse:(id)arg1;
- (void)_setResponseDictionary:(id)arg1;
- (BOOL)_runWithActionURL:(id)arg1 error:(id *)arg2;
- (void)run;
@property(readonly) NSHTTPURLResponse *URLResponse;
@property(readonly) NSString *socialActionType;
@property(readonly) NSDictionary *responseDictionary;
@property(readonly) unsigned long long itemIdentifier;
- (void)dealloc;
- (id)initWithSocialActionType:(id)arg1 itemIdentifier:(unsigned long long)arg2;
- (id)init;

@end

