/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SUViewController.h"

@class IUStoreSocialURLResolutionOperation, NSString, SUStorePageViewController;

@interface IUStoreSocialPageViewController : SUViewController
{
    NSString *_actionType;
    unsigned long long _itemIdentifier;
    IUStoreSocialURLResolutionOperation *_resolutionOperation;
    SUStorePageViewController *_storePageViewController;
    NSString *_socialActionType;
}

@property(readonly, nonatomic) NSString *socialActionType; // @synthesize socialActionType=_socialActionType;
@property(readonly, nonatomic) unsigned long long itemIdentifier; // @synthesize itemIdentifier=_itemIdentifier;
- (void)storePage:(id)arg1 finishedWithSuccess:(BOOL)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)viewControllerFactory;
- (void)loadView;
- (void)dealloc;
- (id)initWithSocialActionType:(id)arg1 itemIdentifier:(unsigned long long)arg2;
- (id)init;

@end

