/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SUClientController.h"

#import "MCProfileConnectionObserver-Protocol.h"
#import "SSDownloadManagerObserver-Protocol.h"

@class IUStoreSocialHistory;

@interface IUStoreClientController : SUClientController <SSDownloadManagerObserver, MCProfileConnectionObserver>
{
    BOOL _isUsingNetwork;
    BOOL _shouldIgnoreSocial;
    BOOL _socialEnabled;
    IUStoreSocialHistory *_socialHistory;
}

+ (id)sharedController;
+ (id)musicStoreURLWithAction:(id)arg1;
@property(readonly, nonatomic) IUStoreSocialHistory *socialHistory; // @synthesize socialHistory=_socialHistory;
- (void)_reloadSocialEnabled;
- (void)_networkTypeChangedNotification:(id)arg1;
- (void)bagDidLoadNotification:(id)arg1;
- (void)_accountStoreChangedNotification:(id)arg1;
- (void)downloadManagerNetworkUsageDidChange:(id)arg1;
- (void)profileConnectionDidReceiveRestrictionChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)profileConnectionDidReceiveEffectiveSettingsChangedNotification:(id)arg1 userInfo:(id)arg2;
- (void)becomeActive;
@property(readonly, nonatomic, getter=isSocialEnabled) BOOL socialEnabled;
@property(nonatomic) BOOL shouldIgnoreSocial;
- (void)dealloc;
- (id)initWithClientIdentifier:(id)arg1;
- (id)init;

@end

