/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class IUStoreSocialActionOperation, NSMutableDictionary, NSNumber;

@interface IUStoreSocialHistory : NSObject
{
    NSNumber *_accountIdentifier;
    struct dispatch_queue_s *_dispatchQueue;
    struct dispatch_source_s *_expirationTimer;
    NSMutableDictionary *_performedActions;
    IUStoreSocialActionOperation *_reloadOperation;
}

- (void)_setHistoryFromResponseDictionary:(id)arg1;
- (void)_setAccountIdentifier:(id)arg1;
- (void)_scheduleExpirationTimerForURLResponse:(id)arg1;
- (void)_removePerformedActionType:(id)arg1 forItemIdentifier:(unsigned long long)arg2;
- (void)_removeOperationFromLocalChanges:(id)arg1;
- (void)_reloadFromServerIfExpired;
- (void)_postSocialHistoryChanged;
- (void)_performAutomaticReloadFromServer;
- (void)_cancelExpirationTimer;
- (void)_addPerformedActionType:(id)arg1 forItemIdentifier:(unsigned long long)arg2;
- (void)_addOperationToLocalChanges:(id)arg1;
- (void)_urlBagDidLoadNotification:(id)arg1;
- (void)_networkTypeDidChangeNotification:(id)arg1;
- (void)_applicationDidBecomeActiveNotification:(id)arg1;
- (void)_accountStoreChangedNotification:(id)arg1;
- (void)reloadFromServer;
- (BOOL)hasPerformedActionWithActionType:(id)arg1 itemIdentifier:(unsigned long long)arg2;
- (void)addChangeOperation:(id)arg1;
- (void)dealloc;
- (id)init;

@end

