/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "ISOperation.h"

@class NSString, NSURL;

@interface IUStoreSocialURLResolutionOperation : ISOperation
{
    NSString *_actionType;
    NSURL *_url;
}

- (void)_setOutputURL:(id)arg1;
- (void)run;
@property(readonly) NSString *socialActionType;
@property(readonly) NSURL *outputURL;
- (void)dealloc;
- (id)initWithSocialActionType:(id)arg1;
- (id)init;

@end

