/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIApplication.h"

@class IUiPodTabBarController, IUiPodViewController, UINavigationController, UIViewController;

@interface UIApplication (IUAdditions)
@property(readonly, nonatomic) UIViewController *IUTopViewController;
@property(readonly, nonatomic) UINavigationController *IUTopNavigationController;
@property(readonly, nonatomic) IUiPodTabBarController *IUTabBarController;
@property(readonly, nonatomic) IUiPodViewController *IUFullScreenViewController;
@property(readonly, nonatomic) UIViewController *IURootViewController;
@property(readonly, nonatomic) int IUInterfaceType;
@end

