/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <iPodUI/IUiPodSegmentedViewController.h>

@class UIView;

@interface WildcatSegmentedViewController : IUiPodSegmentedViewController
{
    UIView *_noContentView;
}

@property(retain, nonatomic) UIView *noContentView; // @synthesize noContentView=_noContentView;
- (void)_goToMovieStore:(id)arg1;
- (id)noContentViewContextForContexts:(id)arg1;
- (void)reloadSegmentedControl;
- (void)dealloc;

@end

