/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSData, NSMutableDictionary, NSString;

@interface MBSDevice : NSObject
{
    NSMutableDictionary *_deviceInfoDictionary;
    NSData *_logData;
    NSString *_logFileName;
}

- (void)dealloc;
- (BOOL)collectAllDeviceInformation;
- (id)collectBasicDeviceData;
- (id)collectGasGaugeData;
- (id)collectAggdData;
- (id)collectUbiquityData;
- (BOOL)collectLogs;
- (BOOL)createTempDirectory;
- (BOOL)copyLogsToTempDirectory;
@property(retain) NSString *logFileName; // @synthesize logFileName=_logFileName;
@property(retain) NSData *logData; // @synthesize logData=_logData;
@property(retain) NSMutableDictionary *deviceInfoDictionary; // @synthesize deviceInfoDictionary=_deviceInfoDictionary;

@end

