/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCROBrailleDisplayAutoDetector : NSObject
{
    BOOL _isDetectingDisplays;
    struct IONotificationPort *_notificationPort;
    NSMutableDictionary *_iteratorDict;
}

+ (id)sharedDetector;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (BOOL)isAutoDetectEnabled;
- (void)detectDisplays;
- (void)stopDetectingDisplays;

@end

