/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying-Protocol.h"

@class NSMutableAttributedString, NSString;

@interface SCROBrailleChunk : NSObject <NSCopying>
{
    NSString *_text;
    NSString *_language;
    int _contractionMode;
    BOOL _showEightDot;
    BOOL _isFocused;
    BOOL _hasTextSelection;
    struct _NSRange _textSelection;
    int _token;
    BOOL _showDotsSevenAndEight;
    NSMutableAttributedString *_brailleString;
    struct _NSRange _brailleSelection;
}

+ (void)initialize;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithText:(id)arg1 language:(id)arg2 selection:(struct _NSRange *)arg3 token:(int)arg4 focused:(BOOL)arg5 contractionMode:(int)arg6 showEightDot:(BOOL)arg7 showDotsSevenAndEight:(BOOL)arg8;
- (void)dealloc;
- (id)_tableIdentifierForLanguage:(id)arg1;
- (void)translate;
- (BOOL)focused;
- (BOOL)hasSelection;
- (BOOL)isFocusedOrSelected;
- (int)token;
- (int)locationForIndex:(int)arg1;
- (id)brailleWithIBeamLocation:(int *)arg1 selection:(struct _NSRange *)arg2;
@property(readonly, nonatomic) NSString *language; // @synthesize language=_language;

@end

