/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SCROBrailleDriverProtocol <NSObject>
- (unsigned int)interfaceVersion;
- (int)loadDriverWithIOElement:(id)arg1;
- (BOOL)unloadDriver;
- (BOOL)isDriverLoaded;
- (BOOL)isSleeping;
- (id)modelIdentifier;
- (BOOL)supportsBlinkingCursor;
- (BOOL)isInputEnabled;
- (BOOL)postsKeyboardEvents;
- (int)brailleInputMode;
- (id)getInputEvents;
- (int)mainSize;
- (int)statusSize;
- (BOOL)setMainCells:(const char *)arg1 length:(int)arg2;
- (BOOL)setStatusCells:(const char *)arg1 length:(int)arg2;
@end

