/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface SCROBrailleDisplayHistory : NSObject
{
    struct __CFArray *_announcements;
    struct __CFArray *_unreadSnapshot;
    int _currentIndex;
    int _unreadCount;
}

+ (void)initialize;
- (id)init;
- (void)dealloc;
- (void)addString:(id)arg1;
- (void)snapshotUnread;
- (void)markSnapshotAsRead;
- (BOOL)hasUnread;
- (id)currentString;
- (BOOL)moveToNext;
- (BOOL)moveToPrevious;
- (BOOL)_moveIndexBy:(long)arg1;
- (BOOL)isOnMostRecent;
- (void)moveToMostRecent;

@end

