/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock;

@interface SCROClient : NSObject
{
    NSLock *_lock;
    unsigned int _identifier;
    unsigned int _port;
    struct __CFArray *_queue;
    struct __CFSet *_callbackSet;
}

+ (void)initialize;
+ (id)addClientGetIdentifier:(unsigned int *)arg1 getPort:(unsigned int *)arg2;
+ (long)removeClientWithPort:(unsigned int)arg1;
+ (void)sendCallback:(id)arg1;
+ (id)callbacksForClientIdentifier:(unsigned int)arg1;
+ (void)registerCallbackWithKey:(int)arg1 forClientIdentifier:(unsigned int)arg2;
- (id)init;
- (void)dealloc;
- (void)_lock;
- (void)_unlock;
- (void)_invalidate;
- (void)_registerCallbackWithKey:(int)arg1;
- (id)_dequeueCallbacks;
- (BOOL)_wantsCallback:(id)arg1;
- (void)_sendCallback:(id)arg1;

@end

