/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@interface SCROCallback : NSObject <NSCoding>
{
    int _key;
    id _object;
    BOOL _isAtomic;
}

- (id)initWithKey:(int)arg1 object:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (int)key;
- (id)object;
- (void)setIsAtomic:(BOOL)arg1;
- (BOOL)isAtomic;
- (void)postToHandler:(id)arg1;

@end

