/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <ScreenReaderOutputServer/SCROIOElement.h>

#import "SCROIOHIDElementProtocol-Protocol.h"

@interface SCROIOHIDElement : SCROIOElement <SCROIOHIDElementProtocol>
{
    struct __IOHIDDevice *_hidDevice;
}

- (id)initWithIOObject:(unsigned int)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (struct __IOHIDDevice *)hidDevice;
- (int)transport;

@end

