/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class SCRCIndexMap;

@interface SCROBrailleDisplayManagedQueue : NSObject
{
    SCRCIndexMap *_stateQueueMap;
    struct __CFDictionary *_queueStateDict;
    struct __CFDictionary *_displayQueueDict;
    SCRCIndexMap *_tokenDisplayMap;
    unsigned int _maxActiveQueueSize;
}

- (id)init;
- (void)dealloc;
- (id)_queueForState:(int)arg1 createQueue:(BOOL)arg2;
- (void)addDisplay:(id)arg1 withState:(int)arg2;
- (void)removeDisplay:(id)arg1;
- (void)_fillActiveBrailleDisplayQueue;
- (void)setState:(int)arg1 forDisplay:(id)arg2;
- (int)stateForDisplay:(id)arg1;
- (id)displayForToken:(long)arg1;
- (unsigned int)displayCountIncludingDisconnectedDisplays:(BOOL)arg1;
- (id)primaryDisplay;
- (void)setPrimaryDisplay:(id)arg1;
- (unsigned int)activeQueueMaximumSize;
- (void)setActiveQueueMaximumSize:(unsigned int)arg1;
- (id)activeDisplays;
- (id)activePendingDisplays;
- (id)sleepingDisplays;
- (id)disconnectedDisplays;
- (id)loadingDisplays;

@end

