/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSBundle, NSLock;

@interface SCROBrailleTranslationManager : NSObject
{
    NSLock *_contentLock;
    id <SCROBrailleTranslatorProtocol> _translator;
    NSBundle *_translatorBundle;
    BOOL _tableSupportsContractedBraille;
    BOOL _tableSupportsEightDotBraille;
    id <SCROBrailleTranslatorProtocol> _auxTranslator;
    NSBundle *_auxTranslatorBundle;
    BOOL _auxTableSupportsContractedBraille;
    BOOL _auxTableSupportsEightDotBraille;
}

+ (id)sharedManager;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (void)dealloc;
- (void)setPrimaryTranslationTableWithTableIdentifier:(id)arg1;
- (id)primaryTableIdentifier;
- (void)setAuxiliaryTranslationTableWithTableIdentifier:(id)arg1;
- (id)auxiliaryTableIdentifier;
- (id)printBrailleForText:(id)arg1 contracted:(BOOL)arg2 eightDot:(BOOL)arg3 locations:(id *)arg4;
- (id)printBrailleForText:(id)arg1 primaryTable:(BOOL)arg2 contracted:(BOOL)arg3 eightDot:(BOOL)arg4 locations:(id *)arg5;
- (id)textForPrintBraille:(id)arg1 contracted:(BOOL)arg2 eightDot:(BOOL)arg3 locations:(id *)arg4;
- (id)textForPrintBraille:(id)arg1 primaryTable:(BOOL)arg2 contracted:(BOOL)arg3 eightDot:(BOOL)arg4 locations:(id *)arg5;
@property(readonly, nonatomic) BOOL auxiliaryTableSupportsEightDotBraille; // @synthesize auxiliaryTableSupportsEightDotBraille=_auxTableSupportsEightDotBraille;
@property(readonly, nonatomic) BOOL auxiliaryTableSupportsContractedBraille; // @synthesize auxiliaryTableSupportsContractedBraille=_auxTableSupportsContractedBraille;
@property(readonly, nonatomic) BOOL primaryTableSupportsEightDotBraille; // @synthesize primaryTableSupportsEightDotBraille=_tableSupportsEightDotBraille;
@property(readonly, nonatomic) BOOL primaryTableSupportsContractedBraille; // @synthesize primaryTableSupportsContractedBraille=_tableSupportsContractedBraille;

@end

