/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSLock;

@interface SCROServer : NSObject
{
    NSLock *_contentLock;
    id <SCROServerDelegate> _delegate;
    struct __CFRunLoopSource *_serverSource;
    struct __CFRunLoopSource *_deathSource;
    struct __CFRunLoopTimer *_deathTimer;
    unsigned int _serverPort;
    unsigned int _deathPort;
    int _clientCount;
    BOOL _isRegisteredWithMach;
}

+ (id)sharedServer;
+ (void)initialize;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)retain;
- (unsigned int)retainCount;
- (void)release;
- (id)autorelease;
- (long)_clientCount;
- (long)_incrementClientCount;
- (void)_setClientCount:(long)arg1;
- (struct __CFRunLoopTimer *)_deathTimer;
- (int)_registerForNotificationOnDeathPort:(unsigned int)arg1;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (BOOL)isRegisteredWithMach;
- (BOOL)registerWithMach;
- (void)unregisterWithMach;
- (struct __CFRunLoopSource *)serverSource;

@end

