/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class AVCaptureConnection, AVCaptureMovieFileOutput, AVCaptureSession, AVRemaker, MPAudioDeviceController, NSDate, NSMutableArray, NSString, RCSavedRecording;

@interface RCAudioInputDevice : NSObject
{
    AVCaptureSession *_captureController;
    AVCaptureMovieFileOutput *_movieFileOutput;
    AVCaptureConnection *_captureConnection;
    MPAudioDeviceController *_audioDeviceController;
    NSString *_pickedRouteName;
    RCSavedRecording *_activeRecording;
    NSDate *_recordingStartDate;
    NSDate *_pauseStartDate;
    double _totalPausedTime;
    double _duration;
    unsigned int _backgroundTaskIdentifier;
    unsigned int _recording:1;
    unsigned int _audioInputAvailable:1;
    unsigned int _active:1;
    unsigned int _interrupted:1;
    unsigned int _writingToDisk:1;
    unsigned int _recordAfterFinishedWritingToDisk:1;
    unsigned int _lastRecordingDidStop:1;
    unsigned int _preparingToRecord:1;
    unsigned int _stopRecordingImmediately:1;
    unsigned int _previewStarted:1;
    AVRemaker *_remaker;
    NSString *_originalRecordingPath;
    NSString *_remadeRecordingPath;
    NSMutableArray *_recordingsToRemake;
    RCSavedRecording *_recordingBeingRemade;
    unsigned int _remaking:1;
}

+ (id)savedRecordingsDirectory;
+ (id)sharedInputDevice;
- (id)init;
- (id)_init;
- (void)dealloc;
- (void)audioDeviceControllerAudioRoutesChanged:(id)arg1;
- (void)becomeActive;
- (void)resignActive;
@property(readonly, nonatomic) BOOL audioInputAvailable;
- (void)getAverageAudioLevel:(float *)arg1 peakAudioLevel:(float *)arg2;
@property(readonly, nonatomic) BOOL isRecording;
@property(readonly, nonatomic) BOOL isPaused;
- (BOOL)beginRecording;
- (void)pauseRecording;
- (void)resumeRecording;
- (void)endRecording;
@property(readonly, nonatomic) double elapsedRecordingTime;
@property(readonly, nonatomic) BOOL shouldSuspend;
- (void)remakeRecording:(id)arg1;
- (BOOL)_attachCaptureDevice;
- (void)_createCaptureController;
- (void)captureOutput:(id)arg1 didStartRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3;
- (void)captureOutput:(id)arg1 didFinishRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3 error:(id)arg4;
- (void)_beginRecording;
- (void)_adjustDurationForPauseIfNecessary;
- (void)_availableModesDidChange:(id)arg1;
- (void)_interruptionDidBegin:(id)arg1;
- (void)_interruptionDidEnd:(id)arg1;
- (void)_sessionDidStartRunning:(id)arg1;
- (void)captureOutput:(id)arg1 didPauseRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3;
- (void)captureOutput:(id)arg1 didResumeRecordingToOutputFileAtURL:(id)arg2 fromConnections:(id)arg3;
- (void)_recordingStopped;
- (void)_audioInputAvailabilityDidChange:(BOOL)arg1;
- (BOOL)_setupAudioInputQueue;
- (void)_teardownAudioInputQueue;
- (void)_captureCompleted;
- (void)_sessionErrored:(id)arg1;
- (void)_remakeRecording:(id)arg1;
- (void)_remakingCompleted:(id)arg1;
- (void)_applicationWillTerminate:(id)arg1;
- (void)_removeCaptureObservers;
- (void)_setDisableSBMediaHUD:(BOOL)arg1;
@property(retain, nonatomic) NSDate *recordingStartDate; // @synthesize recordingStartDate=_recordingStartDate;
@property(readonly, nonatomic) RCSavedRecording *recordingBeingRemade; // @synthesize recordingBeingRemade=_recordingBeingRemade;

@end

