/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSFetchRequest, NSFetchedResultsController, NSManagedObjectContext, NSManagedObjectModel;

@interface RCSavedRecordingsModel : NSObject
{
    NSManagedObjectModel *_model;
    NSManagedObjectContext *_context;
    NSFetchRequest *_fetchRequest;
    NSFetchedResultsController *_fetchController;
}

+ (id)sharedModel;
- (id)init;
- (id)_init;
- (void)dealloc;
- (void)controller:(id)arg1 didChangeObject:(id)arg2 atIndexPath:(id)arg3 forChangeType:(unsigned int)arg4 newIndexPath:(id)arg5;
- (void)controllerDidChangeContent:(id)arg1;
@property(readonly, nonatomic) unsigned int count;
@property(readonly, nonatomic) NSArray *recordings;
- (id)recordingAtIndex:(unsigned int)arg1;
- (id)indexPathForRecording:(id)arg1;
- (id)recordingWithID:(id)arg1;
- (id)recordingWithURIRepresentation:(id)arg1;
- (id)recordingWithITunesPersistentID:(long long)arg1;
- (id)insertRecordingWithAudioFile:(id)arg1 duration:(double)arg2 date:(id)arg3;
- (void)deleteRecording:(id)arg1;
- (BOOL)hasExistingRecordingForAudioFile:(id)arg1;
- (id)_labelPresetsForQuery:(id)arg1;
- (id)recordingsForSpotlightSearch:(id)arg1;
- (void)saveIfNecessary;
- (void)_generateAssetManifestPlist;

@end

