/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSManagedObject.h"

@class AVItem, NSDate, NSString;

@interface RCSavedRecording : NSManagedObject
{
    AVItem *_avItem;
    unsigned int _beingRemade:1;
    NSString *_pathForRemaking;
}

+ (id)localizedStringForRecordingLabel:(unsigned int)arg1;
- (void)dealloc;
- (void)awakeFromInsert;
- (void)awakeFromFetch;
- (void)willSave;
@property(nonatomic) double duration;
@property(nonatomic) unsigned int labelPreset;
@property(nonatomic) long long iTunesPersistentID;
@property(nonatomic, getter=isSynced) BOOL synced;
@property(readonly, nonatomic) NSString *label;
@property(readonly, nonatomic) NSString *detailLabel;
@property(readonly, nonatomic) AVItem *avItem;
@property(nonatomic, getter=isBeingRemade) BOOL beingRemade;
@property(copy, nonatomic) NSString *pathForRemaking; // @synthesize pathForRemaking=_pathForRemaking;

// Remaining properties
@property(copy, nonatomic) NSString *customLabel; // @dynamic customLabel;
@property(copy, nonatomic) NSDate *date; // @dynamic date;
@property(copy, nonatomic) NSString *path; // @dynamic path;

@end

