/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class CMMotionManager;

@interface FigCoreMotionDelegate : NSObject
{
    struct _opaque_pthread_mutex_t ringMutex;
    CMMotionManager *motionManager;
    BOOL manageFusedMotion;
    BOOL manageAccel;
    BOOL manageGravity;
    int accelRingIndex;
    float accelRingX[128];
    float accelRingY[128];
    float accelRingZ[128];
    double accelRingTime[128];
    int fusedRingIndex;
    double fusedRingTime[128];
    char fusedRingSync[128];
    CDStruct_03942939 fusedRingAccel[128];
    CDStruct_bf7dff04 fusedRingQuaternion[128];
    CDStruct_03942939 fusedRingPosition[128];
    BOOL copyingAllData;
    double dLatestFusedMotionCopied;
    double dLatestTimestamp;
    double dGyroUpdateInterval;
    double timestampLatency;
    BOOL gettingAttitudeChange;
    CDStruct_bf7dff04 previousQuaternion;
    CDStruct_bf7dff04 currentQuaternion;
    BOOL computingPosition;
    CDStruct_f31118bd position;
    CDStruct_f31118bd velocity;
}

- (id)initWithAccelerometer:(BOOL)arg1 gravityZ:(BOOL)arg2 fusedMotion:(BOOL)arg3 accelUpdateInterval:(float)arg4 fusedMotionUpdateInterval:(float)arg5;
- (void)updateDeviceCallback:(BOOL)arg1 fusedMotionUpdateInterval:(float)arg2;
- (void)updateGyroInterval:(float)arg1;
- (id)init;
- (void)dealloc;
- (void)didUpdateAcceleration:(CDStruct_03942939)arg1 time:(double)arg2;
- (void)didUpdateGravity:(CDStruct_03942939)arg1 time:(double)arg2;
- (void)getVector:(float *)arg1:(float *)arg2:(float *)arg3 forTimeStamp:(double)arg4;
- (void)getGravityZ:(float *)arg1 forTimeStamp:(double)arg2;
- (void)getFusedVector:(float *)arg1:(float *)arg2:(float *)arg3 forTimeStamp:(double)arg4;
- (void)didUpdateFusedMotionWithDeviceMotion:(CDStruct_2e6f786d)arg1 time:(double)arg2 ifsync:(BOOL)arg3;
- (void)didUpdatePositionWithAcceleration:(CDStruct_03942939 *)arg1 forTimeStamp:(double)arg2;
- (void)didUpdateVelocityWithAcceleration:(CDStruct_03942939 *)arg1 forTimeStamp:(double)arg2;
- (void)didUpdatePositionWithTimeStamp:(double)arg1;
- (id)copyAllFusedMotionData;
- (id)copyNewFusedMotionData;
- (void)updateCurrentQuaternionForTimeStamp:(double)arg1;
- (void)updateCurrentQuaternionForTimeStamps:(double)arg1 withEnd:(double)arg2;
- (void)updateCurrentQuaternionForTimeStamps:(double)arg1 withSynced:(double)arg2;
- (void)getCurrentQuaternion:(CDStruct_bf7dff04 *)arg1;
- (void)getCurrentDeltaQuaternion:(CDStruct_bf7dff04 *)arg1;
- (void)getCurrentAttitude:(double *)arg1:(double *)arg2:(double *)arg3;
- (void)getCurrentDeltaAttitude:(double *)arg1:(double *)arg2:(double *)arg3;
- (void)getPosition:(float *)arg1:(float *)arg2:(float *)arg3 forTimeStamp:(double)arg4;
- (BOOL)managingFusedMotion;
- (BOOL)managingAccel;
- (BOOL)managingGravity;
- (BOOL)isCopyingAllData;

@end

