/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSOperation.h"

@class NSDictionary;

@interface CKSendSMSOperation : NSOperation
{
    NSDictionary *_messageFields;
    unsigned int _recordID;
}

- (id)initWithMessageFields:(id)arg1 recordID:(unsigned int)arg2;
- (void)main;
- (void)dealloc;

@end

