/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSThread;

@interface SMSCTServer : NSObject
{
    NSMutableDictionary *_associationSets;
    NSMutableDictionary *_associationForRecord;
    NSThread *_messageThread;
}

+ (id)sharedServer;
- (void)dealloc;
- (int)_associationIDForRecord:(int)arg1;
- (void)_removeAssociationSetForRecord:(int)arg1;
- (BOOL)_removeRecordFromAssociations:(int)arg1;
- (void)_addRecord:(int)arg1 forAssociationID:(int)arg2;
- (void)start;
- (void)stop;
- (void)updateMMSCapability;
- (void)_registerForCTNotifications;
- (BOOL)_checkMMSEnablement;
- (unsigned char)_readMMSUserOverride;
- (void)playMessageSent;
- (void)_acknowledgeMessageWithKey:(int)arg1;
- (void)_clearPendingIncomingMessageQueue;
- (void)_processReceivedMessageWithInfo:(struct __CFDictionary *)arg1;
- (void)_processReceivedMessageReceiptWithInfo:(struct __CFDictionary *)arg1;
- (void)_ingestIncomingCTMessage:(id)arg1;
- (void)_reallySendSMSRequest:(struct __CFDictionary *)arg1 withProcessedParts:(struct __CFArray *)arg2 recordID:(unsigned int)arg3;
- (void)_sendCompleted:(unsigned char)arg1 forRecord:(unsigned int)arg2;
- (void)_checkAddressBook:(void *)arg1;
- (void)_checkAddressBookAfterQuiescence;
- (void)_significantTimeChanged;
- (void)_mobileSMSDidResume;

@end

