/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSFileHandle, NSThread;

@interface SCRDFileReader : NSObject
{
    id <SCRDFileReaderDelegate> _delegate;
    NSThread *_readerThread;
    NSFileHandle *_fileHandle;
    int _threadStartCount;
}

- (id)initWithDelegate:(id)arg1 fileHandle:(id)arg2;
- (void)dealloc;
- (void)start;
- (BOOL)hasStarted;
- (void)invalidate;
- (BOOL)isValid;
- (void)_readHandler:(id)arg1;

@end

