/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

@protocol MBConnectionHandler
- (void)connection:(id)arg1 didReceiveMessage:(id)arg2;
- (void)connectionDidDisconnect:(id)arg1;
@end

