/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, NSMutableDictionary;

@interface MBDebugContext : NSObject
{
    NSMutableDictionary *_dictionary;
}

+ (id)defaultDebugContext;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) int time;
@property(retain, nonatomic) NSDate *simulatedDate;
- (BOOL)isFlagSet:(id)arg1;
- (void)setFlag:(id)arg1;
- (void)setValue:(id)arg1 forName:(id)arg2;
- (void)removeValueForName:(id)arg1;
- (id)valueForName:(id)arg1;
- (void)setBool:(BOOL)arg1 forName:(id)arg2;
- (BOOL)boolForName:(id)arg1;
- (void)setInt:(int)arg1 forName:(id)arg2;
- (int)intForName:(id)arg1;
- (void)setDelegate:(id)arg1 andSelector:(SEL)arg2 forName:(id)arg3;
- (id)performSelectorForName:(id)arg1;
- (id)performSelectorForName:(id)arg1 withObject:(id)arg2;
- (BOOL)eval:(id)arg1;
- (id)description;

@end

