/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface MBDomainInfo : NSObject <NSCopying, NSCoding>
{
    NSString *_domainName;
    unsigned long long _remoteSize;
    unsigned long long _localSize;
    BOOL _enabled;
    BOOL _restricted;
}

+ (id)domainNameForBundleID:(id)arg1;
+ (id)domainInfoWithName:(id)arg1 remoteSize:(unsigned long long)arg2 localSize:(unsigned long long)arg3 enabled:(BOOL)arg4 restricted:(BOOL)arg5;
- (id)initWithDomainName:(id)arg1 remoteSize:(unsigned long long)arg2 localSize:(unsigned long long)arg3 enabled:(BOOL)arg4 restricted:(BOOL)arg5;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly, nonatomic, getter=isAppDomain) BOOL appDomain;
@property(readonly, nonatomic, getter=isCameraRollDomain) BOOL cameraRollDomain;
@property(readonly, nonatomic) NSString *bundleID;
@property(readonly, nonatomic) unsigned long long size;
@property(nonatomic, getter=isRestricted) BOOL restricted; // @synthesize restricted=_restricted;
@property(nonatomic, getter=isEnabled) BOOL enabled; // @synthesize enabled=_enabled;
@property(nonatomic) unsigned long long localSize; // @synthesize localSize=_localSize;
@property(nonatomic) unsigned long long remoteSize; // @synthesize remoteSize=_remoteSize;
@property(retain, nonatomic) NSString *domainName; // @synthesize domainName=_domainName;

@end

