/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MBFileManager : NSObject
{
}

+ (id)defaultManager;
- (BOOL)fileExistsAtPath:(id)arg1;
- (BOOL)removeFileAtPath:(id)arg1;
- (BOOL)copyPath:(id)arg1 toPath:(id)arg2;
- (BOOL)movePath:(id)arg1 toPath:(id)arg2;
- (id)directoryContentsAtPath:(id)arg1;
- (id)fileAttributesAtPath:(id)arg1 traverseLink:(BOOL)arg2;
- (BOOL)createDirectoryAtPath:(id)arg1 attributes:(id)arg2;

@end

