/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface MBFileInfo : NSObject <NSCopying, NSCoding>
{
    NSString *_path;
    NSDictionary *_extendedAttributes;
}

+ (id)fileInfoWithPath:(id)arg1 extendedAttributes:(id)arg2;
- (id)initWithPath:(id)arg1 extendedAttributes:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDictionary *extendedAttributes; // @synthesize extendedAttributes=_extendedAttributes;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;

@end

