/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDictionary;

@interface MBMessage : NSObject
{
    void *_xpcObject;
    NSDictionary *_messageInfo;
    NSDictionary *_replyInfo;
}

+ (id)messageWithInfo:(id)arg1;
- (id)_initWithXPCObject:(void *)arg1;
- (id)initWithMessageInfo:(id)arg1;
- (void)dealloc;
- (void)sendReply;
- (void *)_xpcObject;
- (id)description;
@property(readonly, nonatomic) NSDictionary *messageInfo; // @synthesize messageInfo=_messageInfo;
@property(copy, nonatomic) NSDictionary *replyInfo; // @synthesize replyInfo=_replyInfo;

@end

