/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface MBMobileInstallation : NSObject
{
    NSString *_safeHarborDir;
    NSString *_errorString;
}

- (id)initWithSafeHarborDir:(id)arg1;
- (void)dealloc;
- (id)userAppsWithError:(id *)arg1;
- (BOOL)processRestoredContainerAtPath:(id)arg1 error:(id *)arg2;
- (BOOL)installPlaceholderAppAtPath:(id)arg1 error:(id *)arg2;
- (BOOL)uninstallAppWithBundleID:(id)arg1 error:(id *)arg2;
- (id)safeHarborsWithError:(id *)arg1;
- (BOOL)registerSafeHarborWithIdentifier:(id)arg1 path:(id)arg2 error:(id *)arg3;
- (BOOL)removeSafeHarbordWithIdentifier:(id)arg1 error:(id *)arg2;
- (void)_mobileInstallationCallback:(id)arg1;
@property(readonly, nonatomic) NSString *safeHarborDir; // @synthesize safeHarborDir=_safeHarborDir;

@end

