/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <FTServices/FTPushHandler.h>

#import "APSConnectionDelegate-Protocol.h"

@class APSConnection, NSData;

@interface FTEmbeddedPushHandler : FTPushHandler <APSConnectionDelegate>
{
    APSConnection *_apsConnection;
    NSData *_cachedPushToken;
    Class _APSConnectionClass;
    BOOL _fastUserSwitched;
    int _cachedStatus;
}

- (void)connection:(id)arg1 didChangeConnectedStatus:(BOOL)arg2;
- (void)connectionDidReconnect:(id)arg1;
- (void)connection:(id)arg1 didFailToSendOutgoingMessage:(id)arg2 error:(id)arg3;
- (void)connection:(id)arg1 didSendOutgoingMessage:(id)arg2;
- (void)connection:(id)arg1 didReceiveMessageForTopic:(id)arg2 userInfo:(id)arg3;
- (void)connection:(id)arg1 didReceivePublicToken:(id)arg2;
- (void)_handlePendingMessagePush:(id)arg1;
- (void)_handleGenericDataPush:(id)arg1;
- (void)_handleGenericCommandPush:(id)arg1;
- (void)_handleEmailConfirmedPush:(id)arg1;
- (void)_handleIncomingReadReceipt:(id)arg1;
- (void)_handleIncomingMessageError:(id)arg1;
- (void)_handleIncomingDeliveryReceipt:(id)arg1;
- (void)_handleIncomingAttachmentMessage:(id)arg1;
- (void)_handleIncomingTextMessage:(id)arg1;
- (void)_handleRelayCancelPush:(id)arg1;
- (void)_handleRelayUpdatePush:(id)arg1;
- (void)_handleRelayInitatePush:(id)arg1;
- (void)_handleSendPush:(id)arg1;
- (void)_handleCancelPush:(id)arg1;
- (void)_handleRejectPush:(id)arg1;
- (void)_handleAcceptPush:(id)arg1;
- (void)_handleReregisterPush:(id)arg1;
- (void)_handleInitatePush:(id)arg1;
- (void)requestKeepAlive;
- (int)connectionStatus;
- (id)pushToken;
- (void)systemDidFastUserSwitchIn;
- (void)systemDidFastUserSwitchOut;
- (void)setRegistered:(BOOL)arg1;
- (void)_ignoreIncomingPushes;
- (void)_acceptIncomingPushes;
- (void)updateTopics;
- (void)_updateTopics;
- (void)dealloc;
- (id)initWithTopics:(id)arg1;

@end

