/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface YTAuthenticator : NSObject
{
    id <YTAuthenticatorDelegate> _delegate;
    NSMutableArray *_deferredRequests;
    int _accountAuthState;
    int _deviceAuthState;
}

+ (id)authenticationDialogWithTarget:(id)arg1 action:(SEL)arg2;
+ (id)sharedAuthenticator;
- (id)init;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)_addDeferredRequest:(id)arg1 accountAuthRequired:(BOOL)arg2;
- (void)_addDeviceAuthenticationObserers;
- (void)_removeDeviceAuthenticationObservers;
- (void)_didAuthenticateDevice:(id)arg1;
- (void)_failedToAuthenticateDevice:(id)arg1;
- (void)_addAccountAuthenticationObserers;
- (void)_removeAccountAuthenticationObservers;
- (void)_didAuthenticateAccount:(id)arg1;
- (void)_failedToAuthenticateAccount:(id)arg1;
- (void)setAccount:(id)arg1 password:(id)arg2;
- (void)userCancelledAccountAuthentication;
- (void)_completeAuthenticationForDeferredRequests;
- (void)_removeDefferredRequests;
- (void)addAuthenticationHeadersToRequest:(id)arg1 accountAuthRequired:(BOOL)arg2;
- (void)invalidateToken;
- (void)clearAccountInfo;
- (BOOL)cachedCredentialsValid;
- (BOOL)isWaitingForAuthentication;
- (BOOL)isAccountAuthenticated;
- (BOOL)loadStoredCredentials;

@end

