/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableURLRequest;

@interface YTAuthenticatorDeferredRequest : NSObject
{
    NSMutableURLRequest *_request;
    BOOL _accountAuthRequired;
}

- (void)dealloc;
- (void)setRequest:(id)arg1;
- (id)request;
- (void)setAccountAuthRequired:(BOOL)arg1;
- (BOOL)accountAuthRequired;

@end

