/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableArray, NSMutableURLRequest, YTVideo;

@interface YTCaptionsRequest : XMLSAXHTTPRequest
{
    id <YTCaptionsRequestDelegate> _delegate;
    BOOL _isLoading;
    NSMutableArray *_captions;
    NSMutableURLRequest *_deferredRequest;
    YTVideo *_video;
}

- (void)_requestCaptionsFromURL:(id)arg1;
- (id)initRequestingCaptionsForVideo:(id)arg1 withDelegate:(id)arg2;
- (void)_listenForAuthenticationNotifications:(BOOL)arg1;
- (void)dealloc;
- (id)video;
- (int)parseData:(id)arg1;
- (void)didParseData;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (BOOL)isLoading;
- (void)loadRequest:(id)arg1;
- (void)failWithError:(id)arg1;

@end

