/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableURLRequest, YTCaptionTrack;

@interface YTCaptionTrackRequest : XMLSAXHTTPRequest
{
    id <YTCaptionTrackRequestDelegate> _delegate;
    YTCaptionTrack *_captionTrack;
    NSMutableURLRequest *_deferredRequest;
    BOOL _isLoading;
}

- (id)initCaptionTrackDataRequest:(id)arg1 withDelegate:(id)arg2;
- (void)dealloc;
- (id)captionTrack;
- (void)_listenForAuthenticationNotifications:(BOOL)arg1;
- (void)loadRequest:(id)arg1;
- (void)_requestCaptionTrackDataWithURL:(id)arg1;
- (int)parseData:(id)arg1;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (void)failWithError:(id)arg1;

@end

