/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableArray, NSMutableString, NSMutableURLRequest, YTVideo;

@interface YTCommentsRequest : XMLSAXHTTPRequest
{
    id _delegate;
    BOOL _isLoading;
    NSMutableArray *_comments;
    unsigned int _startIndex;
    unsigned int _totalResults;
    NSMutableURLRequest *_deferredRequest;
    NSMutableString *_moreCommentsURLString;
    YTVideo *_video;
}

+ (unsigned int)commentsPerRequest;
- (void)_requestCommentsFromURL:(id)arg1;
- (void)requestMoreComments;
- (id)initRequestingCommentsForVideo:(id)arg1 withDelegate:(id)arg2;
- (void)_listenForAuthenticationNotifications:(BOOL)arg1;
- (void)dealloc;
- (int)parseData:(id)arg1;
- (void)didParseData;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (BOOL)isLoading;
- (void)loadRequest:(id)arg1;
- (void)failWithError:(id)arg1;

@end

