/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableArray, NSMutableURLRequest, NSURL;

@interface YTFeedRequest : XMLSAXHTTPRequest
{
    id _delegate;
    NSMutableArray *_videos;
    NSURL *_batchURL;
    unsigned int _startIndex;
    unsigned int _videosPerPage;
    unsigned int _totalResults;
    BOOL _invalidatedToken;
    BOOL _isLoading;
    BOOL _accountAuthRequired;
    NSMutableURLRequest *_deferredRequest;
}

+ (int)partialFeedType;
- (void)didParseData;
- (int)parseData:(id)arg1;
- (void)failWithError:(id)arg1;
- (void)listenForAuthenticationNotifications:(BOOL)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)isLoading;
- (void)loadRequest:(id)arg1;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (void)loadRequest:(id)arg1 withDelegate:(id)arg2 accountAuthRequired:(BOOL)arg3;
- (void)setDelegate:(id)arg1;

@end

