/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/YTVideoDataSource.h>

@class NSMutableArray;

@interface YTHistoryVideoDataSource : YTVideoDataSource
{
    NSMutableArray *_history;
}

- (id)_history;
- (void)reloadData;
- (void)loadFromDefaults;
- (void)addVideo:(id)arg1;
- (void)clearHistory;
- (unsigned int)maxVideosToSave;
- (void)_saveToDefaults;

@end

