/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, NSURL, UIImageView, UILabel, UIMoviePlayerController, YTSearchRequest, YTVideo;

@interface YTMovieView : UIView
{
    id _delegate;
    YTVideo *_video;
    NSArray *_videoList;
    NSURL *_youTubeURL;
    YTSearchRequest *_videoInfoRequest;
    UIMoviePlayerController *_moviePlayer;
    UIImageView *_bugView;
    UIImageView *_gradientView;
    BOOL _canAutoPlay;
    BOOL _shownFromExternalURL;
    BOOL _switchingVideos;
    BOOL _controlsShown;
    BOOL _useSmallLogo;
    BOOL _showControlsAfterFullscreenExit;
    BOOL _isShown;
    double _seekTime;
    UILabel *_logLabel;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setDelegate:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setSeekTime:(double)arg1;
- (void)_destroyMoviePlayer;
- (BOOL)_canShare;
- (BOOL)_canBookmark;
- (void)_updateCaptionsForMovie;
- (void)_setupBackground;
- (BOOL)_loggingEnabled;
- (void)_switchToVideo:(id)arg1;
- (void)_loadVideoFromURL:(BOOL)arg1;
- (void)_loadVideoInfoWithID:(id)arg1;
- (void)_cancelVideoInfoRequest;
- (void)willShowForVideo:(id)arg1 inList:(id)arg2 orVideoID:(id)arg3;
- (void)didShow;
- (void)willHide;
- (void)didHide;
- (void)play;
- (void)pause;
- (BOOL)isPlaying;
- (BOOL)canContinuePlayingWhenLocked;
- (int)orientation;
- (void)setCanAutoPlay:(BOOL)arg1;
- (void)willShowAlert;
- (void)setFullscreen:(BOOL)arg1;
- (id)fullscreenView;
- (id)moviePlayer;
- (void)useSmallLogo:(BOOL)arg1;
- (id)video;
- (BOOL)moviePlayerExitRequest:(id)arg1 exitReason:(int)arg2;
- (void)_hideOverlay;
- (void)_hideBug;
- (void)moviePlayerPlaybackStateDidChange:(id)arg1 fromPlaybackState:(unsigned int)arg2;
- (void)moviePlayerBufferingStateDidChange:(id)arg1;
- (BOOL)moviePlayerAddBookmarkButtonPressed:(id)arg1;
- (BOOL)moviePlayerEmailButtonPressed:(id)arg1;
- (void)shareSheetWillShow;
- (void)shareSheetDidHide;
- (BOOL)moviePlayerForwardButtonPressed:(id)arg1;
- (BOOL)moviePlayerBackwardButtonPressed:(id)arg1;
- (BOOL)moviePlayerHeadsetNextTrackPressed:(id)arg1;
- (BOOL)moviePlayerHeadsetPreviousTrackPressed:(id)arg1;
- (BOOL)moviePlayer:(id)arg1 validateAction:(SEL)arg2;
- (void)moviePlayerWillEnterFullscreen:(id)arg1;
- (void)moviePlayerWillExitFullscreen:(id)arg1;
- (void)moviePlayerDidExitFullscreen:(id)arg1;
- (void)moviePlayerWillShowOverlay:(id)arg1;
- (void)moviePlayerDidShowOverlay:(id)arg1;
- (void)moviePlayerWillHideOverlay:(id)arg1;
- (void)moviePlayerDidHideOverlay:(id)arg1;
- (struct CGRect)moviePlayerFrameAfterFullscreenExit:(id)arg1;
- (void)moviePlayerPlaybackDidEnd:(id)arg1;
- (void)_presentAlertForError:(id)arg1 reasonCode:(id)arg2;
- (void)searchRequest:(id)arg1 receivedVideos:(id)arg2 startIndex:(unsigned int)arg3 videosRemaining:(unsigned int)arg4;
- (void)searchRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)forceControlsVisible:(BOOL)arg1;

@end

