/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface YTProtectedDefaults : NSObject
{
    NSMutableDictionary *_internalDictionary;
    BOOL _shouldSynchronize;
    NSString *_plistPath;
}

+ (id)sharedInstance;
- (id)init;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)removeObjectForKey:(id)arg1;
- (BOOL)synchronize;
- (void)_protectedDataAvailable;
- (void)_protectedDataUnvailable;

@end

