/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableArray, NSMutableURLRequest, NSString;

@interface YTSearchSuggestionsRequest : XMLSAXHTTPRequest
{
    id _delegate;
    NSMutableArray *_suggestions;
    NSMutableURLRequest *_deferredRequest;
    NSString *_query;
}

- (void)_listenForAuthenticationNotifications:(BOOL)arg1;
- (void)dealloc;
- (int)parseData:(id)arg1;
- (void)didParseData;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (void)loadRequest:(id)arg1;
- (id)_suggestionsURLForQuery:(id)arg1;
- (void)requestSuggestionsWithDelegate:(id)arg1 query:(id)arg2;
- (void)failWithError:(id)arg1;
- (void)clearDelegate;

@end

