/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <YouTube/XMLSAXHTTPRequest.h>

@class NSMutableArray, NSMutableURLRequest;

@interface YTSubscriptionsRequest : XMLSAXHTTPRequest
{
    id _delegate;
    NSMutableArray *_subscriptions;
    int _mode;
    NSMutableURLRequest *_deferredRequest;
}

+ (id)displayStringForSubscription:(id)arg1;
+ (BOOL)isSubscription:(id)arg1 channelOfUser:(id)arg2;
+ (id)URLForSubscription:(id)arg1;
- (id)init;
- (void)_listenForAuthenticationNotifications:(BOOL)arg1;
- (void)dealloc;
- (int)parseData:(id)arg1;
- (void)didParseData;
- (void)_didAuthenticate:(id)arg1;
- (void)_failedToAuthenticate:(id)arg1;
- (void)loadRequest:(id)arg1;
- (void)_doRequestWithURL:(id)arg1;
- (void)requestSubscriptions;
- (void)requestPlaylists;
- (void)createPlaylistNamed:(id)arg1;
- (void)subscribeToUser:(id)arg1;
- (void)failWithError:(id)arg1;
- (void)setDelegate:(id)arg1;

@end

