/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSURL;

@interface YTVideoReference : NSObject
{
    NSURL *_contentURL;
    unsigned int _duration;
    int _profile;
}

- (id)initWithContentURL:(id)arg1 duration:(unsigned int)arg2 profile:(int)arg3;
- (id)initFromArchiveDictionary:(id)arg1;
- (void)dealloc;
- (id)archiveDictionary;
- (id)description;
- (id)contentURL;
- (unsigned int)duration;
- (int)profile;

@end

