/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSCalendarDate, NSMutableArray, NSString, NSURL;

@interface YTVideo : NSObject
{
    NSString *_id;
    NSString *_title;
    NSString *_author;
    NSCalendarDate *_dateUpdated;
    NSCalendarDate *_dateAdded;
    NSArray *_videoReferences;
    NSString *_notificationName;
    NSString *_videoDescription;
    NSString *_category;
    NSArray *_tags;
    unsigned int _numberOfViews;
    unsigned int _numLikes;
    unsigned int _numDislikes;
    int _batchStatus;
    NSURL *_infoURL;
    NSURL *_thumbnailURL;
    NSURL *_commentsURL;
    NSURL *_editURL;
    NSURL *_ratingsURL;
    NSURL *_captionsURL;
    NSString *_shortID;
    NSString *_unplayable;
    BOOL _isProcessing;
    NSMutableArray *_captions;
    int _privacy;
    id _thumbnailProxyBlock;
}

+ (void)disableNotifications;
+ (void)enableNotifications;
+ (id)unsupportedVideoError;
+ (id)videoNotFoundError;
+ (id)videoIsProcessingError;
+ (void)reset3GPlaybackStallCount;
+ (void)playbackDidStall;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)initFromArchiveDictionary:(id)arg1;
- (id)archiveDictionary;
- (void)_postVideoDidChange;
- (void)_thumbnailDidLoad;
- (id)initWithID:(id)arg1 title:(id)arg2 dateUpdated:(id)arg3 dateAdded:(id)arg4 videoReferences:(id)arg5 infoURL:(id)arg6 videoDescription:(id)arg7 category:(id)arg8 tags:(id)arg9 author:(id)arg10 thumbnailURL:(id)arg11 numLikes:(unsigned int)arg12 numDislikes:(unsigned int)arg13 numberOfViews:(unsigned int)arg14 batchStatus:(int)arg15 commentsURL:(id)arg16 editURL:(id)arg17 ratingsURL:(id)arg18 captionsURL:(id)arg19 shortID:(id)arg20 unplayable:(id)arg21 isProcessing:(BOOL)arg22 privacy:(int)arg23;
- (void)dealloc;
- (id)description;
- (id)ID;
- (id)shortID;
- (id)title;
- (id)author;
- (id)dateUpdated;
- (id)dateAdded;
- (id)dateAddedString;
- (id)commentsURL;
- (id)editURL;
- (id)ratingsURL;
- (id)captionsURL;
- (id)infoURL;
- (id)thumbnailURL;
- (id)videoDescription;
- (id)category;
- (id)tags;
- (id)tagsString;
- (id)unplayable;
- (double)age;
- (unsigned int)numLikes;
- (unsigned int)numDislikes;
- (BOOL)positiveRating;
- (id)ratingPercentageString;
- (unsigned int)numberOfViews;
- (int)batchStatus;
- (struct CGImage *)thumbnailLoadIfAbsent:(BOOL)arg1;
- (struct CGImage *)roundedThumbnailLoadIfAbsent:(BOOL)arg1;
- (struct CGImage *)largeThumbnailLoadIfAbsent:(BOOL)arg1;
- (struct CGImage *)pluginThumbnailLoadIfAbsent:(BOOL)arg1;
- (void)loadThumbnailWithCallback:(id)arg1;
- (id)videoReferenceForProfile:(int)arg1;
- (BOOL)allowsHighQuality3GPlayback;
- (void)carrierBundleDidChangeNotification:(id)arg1;
- (id)bestVideoReference;
- (id)anyVideoReference;
- (BOOL)isBookmarked;
- (BOOL)isPlayable;
- (BOOL)isProcessing;
- (id)captions;
- (id)privacyString;
- (BOOL)ownVideo;

@end

