/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PBCompiledFilter : NSObject
{
    unsigned int _program;
    unsigned int _vao;
    unsigned int _vbo;
    unsigned int *_uniforms;
    int _uniformCount;
}

- (id)initWithProgram:(unsigned int)arg1 uniforms:(unsigned int *)arg2 uniformCount:(int)arg3;
- (void)dealloc;
@property(readonly, nonatomic) int uniformCount; // @synthesize uniformCount=_uniformCount;
@property(readonly, nonatomic) unsigned int *uniforms; // @synthesize uniforms=_uniforms;
@property(readonly, nonatomic) unsigned int program; // @synthesize program=_program;

@end

