/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBNormalFilter.h>

@interface PBNormalFilter (OpenCL)
- (void)setupKernelArguments:(id)arg1 mirrored:(BOOL)arg2;
- (unsigned long)kernelArgCount;
- (void *)kernelWrapper;
@end

