/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBOpenGLContext.h>

@interface PBOpenGLContext (PBOpenGLContextPrivate)
- (BOOL)_registerFilter:(id)arg1;
- (id)_compileFilter:(id)arg1;
- (void)_createPixelBuffer:(struct __CVBuffer **)arg1 withSize:(struct CGSize)arg2;
- (void)_createPixelBufferPools;
- (unsigned int)_compileShader:(const char *)arg1 type:(unsigned int)arg2;
- (unsigned int)_textureForLookupTableName:(id)arg1;
@end

