/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBContext.h>

@interface PBOpenGLContext : PBContext
{
    void *_priv;
}

- (void)setSmallPool:(struct __CVPixelBufferPool *)arg1;
- (void)setLargePool:(struct __CVPixelBufferPool *)arg1;
- (struct __CVPixelBufferPool *)smallPool;
- (struct __CVPixelBufferPool *)largePool;
- (id)init;
- (void)dealloc;
- (struct _CAImageQueue *)outputImageQueue;
- (void)setOutputImageQueue:(struct _CAImageQueue *)arg1;
- (struct __CVBuffer *)createCVPixelBufferForFilter:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2 mirrored:(BOOL)arg3;
- (void)preloadFilter:(id)arg1;
- (void)renderFilter:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2;
- (void)renderFilter:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2 mirrored:(BOOL)arg3;
- (void)renderNineUp:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2;
- (void)renderNineUp:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2 mirrored:(BOOL)arg3;
- (struct CGImage *)createCGImageForFilterViaGL:(id)arg1 inputPixelBuffer:(struct __CVBuffer *)arg2;

@end

