/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBRuntimeWrapper.h>

@interface PBRuntimeWrapper (Private)
- (void)_applyFilter:(id)arg1 onInputSurface:(struct __IOSurface *)arg2 mirrored:(BOOL)arg3 withResultHandler:(id)arg4;
- (void)_setKernelArg:(void *)arg1 withSize:(unsigned long)arg2;
- (void)_setKernelArgAsBuffer:(void *)arg1 withSize:(unsigned long)arg2;
- (void)_setKernelCleanupHandler:(id *)arg1;
@end

