/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PBRuntimeWrapper : NSObject
{
    void **argList;
    unsigned int *argSizeList;
    unsigned int argIndex;
    struct __CFArray *extraArgsList;
    id *cleanupHandler;
    struct CGSize imageDims;
}

- (id)init;
- (void)dealloc;
- (void)applyFilter:(id)arg1 onInputSurface:(struct __IOSurface *)arg2 mirrored:(BOOL)arg3 withResultHandler:(id)arg4;
- (void)setKernelArg:(void *)arg1 withSize:(unsigned long)arg2;
- (void)setKernelArgAsBuffer:(void *)arg1 withSize:(unsigned long)arg2;
- (void)setKernelCleanupHandler:(id *)arg1;
@property(nonatomic) struct CGSize imageDims; // @synthesize imageDims;
@property(nonatomic) struct __CFArray *extraArgsList; // @synthesize extraArgsList;
@property(nonatomic) id *cleanupHandler; // @synthesize cleanupHandler;
@property(nonatomic) unsigned int argIndex; // @synthesize argIndex;
@property(nonatomic) unsigned int *argSizeList; // @synthesize argSizeList;
@property(nonatomic) void **argList; // @synthesize argList;

@end

