/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBRuntimeWrapper.h>

@interface PBRuntimeWrapper (IOSurfaceConvenience)
- (struct __IOSurface *)createIOSurfaceForWidth:(unsigned long)arg1 height:(unsigned long)arg2 pixelFormat:(unsigned int)arg3 workOnRawData:(id)arg4;
@end

